/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    /**
     * @component sg-skeleton
     * @description Skeleton loading placeholder component for SageBox
     * @example <sg-skeleton variant="text" width="200px" height="1rem"></sg-skeleton>
     * <sg-skeleton variant="rect" width="100%" height="200px"></sg-skeleton>
     * <sg-skeleton variant="circle" width="48px" height="48px"></sg-skeleton>
     */
    interface SgSkeleton {
        /**
          * Animation type - shimmer: Gradient animation (default) - pulse: Opacity pulse animation - none: No animation
          * @default 'shimmer'
         */
        "animation": 'shimmer' | 'pulse' | 'none';
        /**
          * The height of the skeleton
          * @default '1rem'
         */
        "height": string;
        /**
          * The shape variant of the skeleton - text: Slightly rounded, good for text placeholders - rect: More rounded, good for cards/images - circle: Fully rounded, good for avatars
          * @default 'text'
         */
        "variant": 'text' | 'rect' | 'circle';
        /**
          * The width of the skeleton
          * @default '100%'
         */
        "width": string;
    }
}
declare global {
    /**
     * @component sg-skeleton
     * @description Skeleton loading placeholder component for SageBox
     * @example <sg-skeleton variant="text" width="200px" height="1rem"></sg-skeleton>
     * <sg-skeleton variant="rect" width="100%" height="200px"></sg-skeleton>
     * <sg-skeleton variant="circle" width="48px" height="48px"></sg-skeleton>
     */
    interface HTMLSgSkeletonElement extends Components.SgSkeleton, HTMLStencilElement {
    }
    var HTMLSgSkeletonElement: {
        prototype: HTMLSgSkeletonElement;
        new (): HTMLSgSkeletonElement;
    };
    interface HTMLElementTagNameMap {
        "sg-skeleton": HTMLSgSkeletonElement;
    }
}
declare namespace LocalJSX {
    /**
     * @component sg-skeleton
     * @description Skeleton loading placeholder component for SageBox
     * @example <sg-skeleton variant="text" width="200px" height="1rem"></sg-skeleton>
     * <sg-skeleton variant="rect" width="100%" height="200px"></sg-skeleton>
     * <sg-skeleton variant="circle" width="48px" height="48px"></sg-skeleton>
     */
    interface SgSkeleton {
        /**
          * Animation type - shimmer: Gradient animation (default) - pulse: Opacity pulse animation - none: No animation
          * @default 'shimmer'
         */
        "animation"?: 'shimmer' | 'pulse' | 'none';
        /**
          * The height of the skeleton
          * @default '1rem'
         */
        "height"?: string;
        /**
          * The shape variant of the skeleton - text: Slightly rounded, good for text placeholders - rect: More rounded, good for cards/images - circle: Fully rounded, good for avatars
          * @default 'text'
         */
        "variant"?: 'text' | 'rect' | 'circle';
        /**
          * The width of the skeleton
          * @default '100%'
         */
        "width"?: string;
    }
    interface IntrinsicElements {
        "sg-skeleton": SgSkeleton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * @component sg-skeleton
             * @description Skeleton loading placeholder component for SageBox
             * @example <sg-skeleton variant="text" width="200px" height="1rem"></sg-skeleton>
             * <sg-skeleton variant="rect" width="100%" height="200px"></sg-skeleton>
             * <sg-skeleton variant="circle" width="48px" height="48px"></sg-skeleton>
             */
            "sg-skeleton": LocalJSX.SgSkeleton & JSXBase.HTMLAttributes<HTMLSgSkeletonElement>;
        }
    }
}
