/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { BreadcrumbSeparator, BreadcrumbSize } from "./components/breadcrumb/breadcrumb";
export { BreadcrumbSeparator, BreadcrumbSize } from "./components/breadcrumb/breadcrumb";
export namespace Components {
    /**
     * @component sg-breadcrumb
     * @description Navigation breadcrumb component showing the current page location within a hierarchy.
     * @example ```html
     * <sg-breadcrumb>
     *   <sg-breadcrumb-item href="/">Home</sg-breadcrumb-item>
     *   <sg-breadcrumb-item href="/products">Products</sg-breadcrumb-item>
     *   <sg-breadcrumb-item active>Details</sg-breadcrumb-item>
     * </sg-breadcrumb>
     * ```
     */
    interface SgBreadcrumb {
        /**
          * Collapse items on mobile (show only first and last)
          * @default false
         */
        "collapsible": boolean;
        /**
          * Custom separator character (overrides separator prop)
         */
        "customSeparator": string;
        /**
          * Maximum items to show before collapsing (when collapsible)
          * @default 4
         */
        "maxItems": number;
        /**
          * Separator style between items
          * @default 'chevron'
         */
        "separator": BreadcrumbSeparator;
        /**
          * Show home icon for first item
          * @default false
         */
        "showHomeIcon": boolean;
        /**
          * Size variant
          * @default 'md'
         */
        "size": BreadcrumbSize;
    }
    /**
     * @component sg-breadcrumb-item
     * @description Individual breadcrumb item. Must be used inside sg-breadcrumb.
     * @example ```html
     * <sg-breadcrumb-item href="/home">
     *   <sg-icon slot="icon" name="home" size="14"></sg-icon>
     *   Home
     * </sg-breadcrumb-item>
     * ```
     */
    interface SgBreadcrumbItem {
        /**
          * Whether this is the current/active page
          * @default false
         */
        "active": boolean;
        /**
          * Disable the item
          * @default false
         */
        "disabled": boolean;
        /**
          * URL to navigate to
         */
        "href": string;
        /**
          * Icon name to display (uses sg-icon)
         */
        "icon": string;
        /**
          * Target for the link
          * @default '_self'
         */
        "target": string;
    }
}
declare global {
    /**
     * @component sg-breadcrumb
     * @description Navigation breadcrumb component showing the current page location within a hierarchy.
     * @example ```html
     * <sg-breadcrumb>
     *   <sg-breadcrumb-item href="/">Home</sg-breadcrumb-item>
     *   <sg-breadcrumb-item href="/products">Products</sg-breadcrumb-item>
     *   <sg-breadcrumb-item active>Details</sg-breadcrumb-item>
     * </sg-breadcrumb>
     * ```
     */
    interface HTMLSgBreadcrumbElement extends Components.SgBreadcrumb, HTMLStencilElement {
    }
    var HTMLSgBreadcrumbElement: {
        prototype: HTMLSgBreadcrumbElement;
        new (): HTMLSgBreadcrumbElement;
    };
    /**
     * @component sg-breadcrumb-item
     * @description Individual breadcrumb item. Must be used inside sg-breadcrumb.
     * @example ```html
     * <sg-breadcrumb-item href="/home">
     *   <sg-icon slot="icon" name="home" size="14"></sg-icon>
     *   Home
     * </sg-breadcrumb-item>
     * ```
     */
    interface HTMLSgBreadcrumbItemElement extends Components.SgBreadcrumbItem, HTMLStencilElement {
    }
    var HTMLSgBreadcrumbItemElement: {
        prototype: HTMLSgBreadcrumbItemElement;
        new (): HTMLSgBreadcrumbItemElement;
    };
    interface HTMLElementTagNameMap {
        "sg-breadcrumb": HTMLSgBreadcrumbElement;
        "sg-breadcrumb-item": HTMLSgBreadcrumbItemElement;
    }
}
declare namespace LocalJSX {
    /**
     * @component sg-breadcrumb
     * @description Navigation breadcrumb component showing the current page location within a hierarchy.
     * @example ```html
     * <sg-breadcrumb>
     *   <sg-breadcrumb-item href="/">Home</sg-breadcrumb-item>
     *   <sg-breadcrumb-item href="/products">Products</sg-breadcrumb-item>
     *   <sg-breadcrumb-item active>Details</sg-breadcrumb-item>
     * </sg-breadcrumb>
     * ```
     */
    interface SgBreadcrumb {
        /**
          * Collapse items on mobile (show only first and last)
          * @default false
         */
        "collapsible"?: boolean;
        /**
          * Custom separator character (overrides separator prop)
         */
        "customSeparator"?: string;
        /**
          * Maximum items to show before collapsing (when collapsible)
          * @default 4
         */
        "maxItems"?: number;
        /**
          * Separator style between items
          * @default 'chevron'
         */
        "separator"?: BreadcrumbSeparator;
        /**
          * Show home icon for first item
          * @default false
         */
        "showHomeIcon"?: boolean;
        /**
          * Size variant
          * @default 'md'
         */
        "size"?: BreadcrumbSize;
    }
    /**
     * @component sg-breadcrumb-item
     * @description Individual breadcrumb item. Must be used inside sg-breadcrumb.
     * @example ```html
     * <sg-breadcrumb-item href="/home">
     *   <sg-icon slot="icon" name="home" size="14"></sg-icon>
     *   Home
     * </sg-breadcrumb-item>
     * ```
     */
    interface SgBreadcrumbItem {
        /**
          * Whether this is the current/active page
          * @default false
         */
        "active"?: boolean;
        /**
          * Disable the item
          * @default false
         */
        "disabled"?: boolean;
        /**
          * URL to navigate to
         */
        "href"?: string;
        /**
          * Icon name to display (uses sg-icon)
         */
        "icon"?: string;
        /**
          * Target for the link
          * @default '_self'
         */
        "target"?: string;
    }
    interface IntrinsicElements {
        "sg-breadcrumb": SgBreadcrumb;
        "sg-breadcrumb-item": SgBreadcrumbItem;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * @component sg-breadcrumb
             * @description Navigation breadcrumb component showing the current page location within a hierarchy.
             * @example ```html
             * <sg-breadcrumb>
             *   <sg-breadcrumb-item href="/">Home</sg-breadcrumb-item>
             *   <sg-breadcrumb-item href="/products">Products</sg-breadcrumb-item>
             *   <sg-breadcrumb-item active>Details</sg-breadcrumb-item>
             * </sg-breadcrumb>
             * ```
             */
            "sg-breadcrumb": LocalJSX.SgBreadcrumb & JSXBase.HTMLAttributes<HTMLSgBreadcrumbElement>;
            /**
             * @component sg-breadcrumb-item
             * @description Individual breadcrumb item. Must be used inside sg-breadcrumb.
             * @example ```html
             * <sg-breadcrumb-item href="/home">
             *   <sg-icon slot="icon" name="home" size="14"></sg-icon>
             *   Home
             * </sg-breadcrumb-item>
             * ```
             */
            "sg-breadcrumb-item": LocalJSX.SgBreadcrumbItem & JSXBase.HTMLAttributes<HTMLSgBreadcrumbItemElement>;
        }
    }
}
