/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { InfoFieldType, StatusMapItem } from "./components/info-field/info-field";
export { InfoFieldType, StatusMapItem } from "./components/info-field/info-field";
export namespace Components {
    /**
     * @component sg-info-field
     * @description Display label-value pairs with automatic formatting based on type.
     * Supports text, dates, status badges, currency, booleans, arrays and custom formatters.
     * @example <sg-info-field label="Name" value="John Doe"></sg-info-field>
     * <sg-info-field label="Created" value="2024-01-15" type="date"></sg-info-field>
     * <sg-info-field label="Status" value="active" type="status"></sg-info-field>
     * <sg-info-field label="Price" value="99.99" type="currency"></sg-info-field>
     */
    interface SgInfoField {
        /**
          * Currency symbol for currency type
          * @default '€'
         */
        "currencySymbol": string;
        /**
          * Placeholder text when value is empty
          * @default 'No especificado'
         */
        "emptyText": string;
        /**
          * Boolean text for false value
          * @default 'No'
         */
        "falseText": string;
        /**
          * Label text for the field
          * @default ''
         */
        "label": string;
        /**
          * Date format locale
          * @default 'es-ES'
         */
        "locale": string;
        /**
          * Custom status map for status type
          * @default {     active: { label: 'Activo', bgColor: '#dcfce7', textColor: '#166534' },     inactive: { label: 'Inactivo', bgColor: '#fee2e2', textColor: '#991b1b' },     pending: { label: 'Pendiente', bgColor: '#fef3c7', textColor: '#92400e' },     draft: { label: 'Borrador', bgColor: '#f3f4f6', textColor: '#374151' },     completed: { label: 'Completado', bgColor: '#dbeafe', textColor: '#1e40af' },     cancelled: { label: 'Cancelado', bgColor: '#fce7f3', textColor: '#9d174d' },   }
         */
        "statusMap": Record<string, StatusMapItem>;
        /**
          * Boolean text for true value
          * @default 'Sí'
         */
        "trueText": string;
        /**
          * Type of value formatting
          * @default 'text'
         */
        "type": InfoFieldType;
        /**
          * Value to display (can be string, number, boolean, array, etc.)
         */
        "value": any;
    }
}
declare global {
    /**
     * @component sg-info-field
     * @description Display label-value pairs with automatic formatting based on type.
     * Supports text, dates, status badges, currency, booleans, arrays and custom formatters.
     * @example <sg-info-field label="Name" value="John Doe"></sg-info-field>
     * <sg-info-field label="Created" value="2024-01-15" type="date"></sg-info-field>
     * <sg-info-field label="Status" value="active" type="status"></sg-info-field>
     * <sg-info-field label="Price" value="99.99" type="currency"></sg-info-field>
     */
    interface HTMLSgInfoFieldElement extends Components.SgInfoField, HTMLStencilElement {
    }
    var HTMLSgInfoFieldElement: {
        prototype: HTMLSgInfoFieldElement;
        new (): HTMLSgInfoFieldElement;
    };
    interface HTMLElementTagNameMap {
        "sg-info-field": HTMLSgInfoFieldElement;
    }
}
declare namespace LocalJSX {
    /**
     * @component sg-info-field
     * @description Display label-value pairs with automatic formatting based on type.
     * Supports text, dates, status badges, currency, booleans, arrays and custom formatters.
     * @example <sg-info-field label="Name" value="John Doe"></sg-info-field>
     * <sg-info-field label="Created" value="2024-01-15" type="date"></sg-info-field>
     * <sg-info-field label="Status" value="active" type="status"></sg-info-field>
     * <sg-info-field label="Price" value="99.99" type="currency"></sg-info-field>
     */
    interface SgInfoField {
        /**
          * Currency symbol for currency type
          * @default '€'
         */
        "currencySymbol"?: string;
        /**
          * Placeholder text when value is empty
          * @default 'No especificado'
         */
        "emptyText"?: string;
        /**
          * Boolean text for false value
          * @default 'No'
         */
        "falseText"?: string;
        /**
          * Label text for the field
          * @default ''
         */
        "label"?: string;
        /**
          * Date format locale
          * @default 'es-ES'
         */
        "locale"?: string;
        /**
          * Custom status map for status type
          * @default {     active: { label: 'Activo', bgColor: '#dcfce7', textColor: '#166534' },     inactive: { label: 'Inactivo', bgColor: '#fee2e2', textColor: '#991b1b' },     pending: { label: 'Pendiente', bgColor: '#fef3c7', textColor: '#92400e' },     draft: { label: 'Borrador', bgColor: '#f3f4f6', textColor: '#374151' },     completed: { label: 'Completado', bgColor: '#dbeafe', textColor: '#1e40af' },     cancelled: { label: 'Cancelado', bgColor: '#fce7f3', textColor: '#9d174d' },   }
         */
        "statusMap"?: Record<string, StatusMapItem>;
        /**
          * Boolean text for true value
          * @default 'Sí'
         */
        "trueText"?: string;
        /**
          * Type of value formatting
          * @default 'text'
         */
        "type"?: InfoFieldType;
        /**
          * Value to display (can be string, number, boolean, array, etc.)
         */
        "value"?: any;
    }
    interface IntrinsicElements {
        "sg-info-field": SgInfoField;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * @component sg-info-field
             * @description Display label-value pairs with automatic formatting based on type.
             * Supports text, dates, status badges, currency, booleans, arrays and custom formatters.
             * @example <sg-info-field label="Name" value="John Doe"></sg-info-field>
             * <sg-info-field label="Created" value="2024-01-15" type="date"></sg-info-field>
             * <sg-info-field label="Status" value="active" type="status"></sg-info-field>
             * <sg-info-field label="Price" value="99.99" type="currency"></sg-info-field>
             */
            "sg-info-field": LocalJSX.SgInfoField & JSXBase.HTMLAttributes<HTMLSgInfoFieldElement>;
        }
    }
}
