/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
export namespace Components {
  /**
   * @example ### Angular
   * ```html
   * <sg-dropdown align="start" position="bottom">
   *   <button slot="trigger">Open Menu</button>
   *   <div slot="header">Settings</div>
   *   <button>Option 1</button>
   *   <button>Option 2</button>
   *   <div slot="footer">Logged in as Admin</div>
   * </sg-dropdown>
   * ```
   * ### React
   * ```jsx
   * <sg-dropdown align="start" closeOnSelect={false}>
   *   <button slot="trigger">Menu</button>
   *   <div>Content here</div>
   * </sg-dropdown>
   * ```
   * ### Vanilla JS
   * ```html
   * <sg-dropdown id="myDropdown" align="end" close-on-select="false">
   *   <button slot="trigger">Options</button>
   *   <ul>
   *     <li>Item 1</li>
   *     <li>Item 2</li>
   *   </ul>
   * </sg-dropdown>
   * <script>
   *   const dropdown = document.querySelector('#myDropdown');
   *   dropdown.addEventListener('sgOpen', (e) => console.log('Opened'));
   *   dropdown.addEventListener('sgClose', (e) => console.log('Closed'));
   * </script>
   * ```
   */
  interface SgDropdown {
    /**
     * Horizontal alignment of the dropdown content relative to trigger
     * @default 'start'
     */
    align: 'start' | 'end' | 'center';
    /**
     * Horizontal alignment of the dropdown
     */
    align?: 'start' | 'end' | 'center';
    /**
     * Closes the dropdown programmatically
     */
    closeDropdown: () => Promise<void>;
    /**
     * Whether to close the dropdown when an item is selected/clicked
     * @default true
     */
    closeOnSelect: boolean;
    /**
     * Whether the dropdown is disabled
     * @default false
     */
    disabled: boolean;
    /**
     * Maximum height of the dropdown content for scrolling
     * @default '320px'
     */
    maxHeight: string;
    /**
     * Minimum width of the dropdown content (e.g., "200px", "12rem")
     * @default '200px'
     */
    minWidth: string;
    /**
     * Whether the dropdown is currently open
     * @default false
     */
    open: boolean;
    /**
     * Opens the dropdown programmatically
     */
    openDropdown: () => Promise<void>;
    /**
     * Vertical position of the dropdown content
     * @default 'bottom'
     */
    position: 'bottom' | 'top';
    /**
     * Position of the dropdown relative to trigger
     */
    position?: 'bottom' | 'top';
    /**
     * Show a backdrop overlay (useful on mobile)
     * @default false
     */
    showBackdrop: boolean;
    /**
     * Size variant
     * @default 'md'
     */
    size: 'sm' | 'md' | 'lg';
    /**
     * Toggles the dropdown open/closed
     */
    toggle: () => Promise<void>;
  }
}
export interface SgDropdownCustomEvent<T> extends CustomEvent<T> {
  detail: T;
  target: HTMLSgDropdownElement;
}
declare global {
  interface HTMLSgDropdownElementEventMap {
    sgOpen: void;
    sgClose: void;
    sgToggle: boolean;
  }
  /**
   * @example ### Angular
   * ```html
   * <sg-dropdown align="start" position="bottom">
   *   <button slot="trigger">Open Menu</button>
   *   <div slot="header">Settings</div>
   *   <button>Option 1</button>
   *   <button>Option 2</button>
   *   <div slot="footer">Logged in as Admin</div>
   * </sg-dropdown>
   * ```
   * ### React
   * ```jsx
   * <sg-dropdown align="start" closeOnSelect={false}>
   *   <button slot="trigger">Menu</button>
   *   <div>Content here</div>
   * </sg-dropdown>
   * ```
   * ### Vanilla JS
   * ```html
   * <sg-dropdown id="myDropdown" align="end" close-on-select="false">
   *   <button slot="trigger">Options</button>
   *   <ul>
   *     <li>Item 1</li>
   *     <li>Item 2</li>
   *   </ul>
   * </sg-dropdown>
   * <script>
   *   const dropdown = document.querySelector('#myDropdown');
   *   dropdown.addEventListener('sgOpen', (e) => console.log('Opened'));
   *   dropdown.addEventListener('sgClose', (e) => console.log('Closed'));
   * </script>
   * ```
   */
  interface HTMLSgDropdownElement extends Components.SgDropdown, HTMLStencilElement {
    addEventListener<K extends keyof HTMLSgDropdownElementEventMap>(
      type: K,
      listener: (this: HTMLSgDropdownElement, ev: SgDropdownCustomEvent<HTMLSgDropdownElementEventMap[K]>) => any,
      options?: boolean | AddEventListenerOptions
    ): void;
    addEventListener<K extends keyof DocumentEventMap>(
      type: K,
      listener: (this: Document, ev: DocumentEventMap[K]) => any,
      options?: boolean | AddEventListenerOptions
    ): void;
    addEventListener<K extends keyof HTMLElementEventMap>(
      type: K,
      listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any,
      options?: boolean | AddEventListenerOptions
    ): void;
    addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
    removeEventListener<K extends keyof HTMLSgDropdownElementEventMap>(
      type: K,
      listener: (this: HTMLSgDropdownElement, ev: SgDropdownCustomEvent<HTMLSgDropdownElementEventMap[K]>) => any,
      options?: boolean | EventListenerOptions
    ): void;
    removeEventListener<K extends keyof DocumentEventMap>(
      type: K,
      listener: (this: Document, ev: DocumentEventMap[K]) => any,
      options?: boolean | EventListenerOptions
    ): void;
    removeEventListener<K extends keyof HTMLElementEventMap>(
      type: K,
      listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any,
      options?: boolean | EventListenerOptions
    ): void;
    removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
  }
  var HTMLSgDropdownElement: {
    prototype: HTMLSgDropdownElement;
    new (): HTMLSgDropdownElement;
  };
  interface HTMLElementTagNameMap {
    'sg-dropdown': HTMLSgDropdownElement;
  }
}
declare namespace LocalJSX {
  /**
   * @example ### Angular
   * ```html
   * <sg-dropdown align="start" position="bottom">
   *   <button slot="trigger">Open Menu</button>
   *   <div slot="header">Settings</div>
   *   <button>Option 1</button>
   *   <button>Option 2</button>
   *   <div slot="footer">Logged in as Admin</div>
   * </sg-dropdown>
   * ```
   * ### React
   * ```jsx
   * <sg-dropdown align="start" closeOnSelect={false}>
   *   <button slot="trigger">Menu</button>
   *   <div>Content here</div>
   * </sg-dropdown>
   * ```
   * ### Vanilla JS
   * ```html
   * <sg-dropdown id="myDropdown" align="end" close-on-select="false">
   *   <button slot="trigger">Options</button>
   *   <ul>
   *     <li>Item 1</li>
   *     <li>Item 2</li>
   *   </ul>
   * </sg-dropdown>
   * <script>
   *   const dropdown = document.querySelector('#myDropdown');
   *   dropdown.addEventListener('sgOpen', (e) => console.log('Opened'));
   *   dropdown.addEventListener('sgClose', (e) => console.log('Closed'));
   * </script>
   * ```
   */
  interface SgDropdown {
    /**
     * Horizontal alignment of the dropdown content relative to trigger
     * @default 'start'
     */
    align?: 'start' | 'end' | 'center';
    /**
     * Horizontal alignment of the dropdown
     */
    align?: 'start' | 'end' | 'center';
    /**
     * Whether to close the dropdown when an item is selected/clicked
     * @default true
     */
    closeOnSelect?: boolean;
    /**
     * Whether the dropdown is disabled
     * @default false
     */
    disabled?: boolean;
    /**
     * Maximum height of the dropdown content for scrolling
     * @default '320px'
     */
    maxHeight?: string;
    /**
     * Minimum width of the dropdown content (e.g., "200px", "12rem")
     * @default '200px'
     */
    minWidth?: string;
    /**
     * Emitted when the dropdown closes
     */
    onSgClose?: (event: SgDropdownCustomEvent<void>) => void;
    /**
     * Emitted when the dropdown opens
     */
    onSgOpen?: (event: SgDropdownCustomEvent<void>) => void;
    /**
     * Emitted when the open state changes
     */
    onSgToggle?: (event: SgDropdownCustomEvent<boolean>) => void;
    /**
     * Whether the dropdown is currently open
     * @default false
     */
    open?: boolean;
    /**
     * Vertical position of the dropdown content
     * @default 'bottom'
     */
    position?: 'bottom' | 'top';
    /**
     * Position of the dropdown relative to trigger
     */
    position?: 'bottom' | 'top';
    /**
     * Show a backdrop overlay (useful on mobile)
     * @default false
     */
    showBackdrop?: boolean;
    /**
     * Size variant
     * @default 'md'
     */
    size?: 'sm' | 'md' | 'lg';
  }
  interface IntrinsicElements {
    'sg-dropdown': SgDropdown;
  }
}
export { LocalJSX as JSX };
declare module '@stencil/core' {
  export namespace JSX {
    interface IntrinsicElements {
      /**
       * @example ### Angular
       * ```html
       * <sg-dropdown align="start" position="bottom">
       *   <button slot="trigger">Open Menu</button>
       *   <div slot="header">Settings</div>
       *   <button>Option 1</button>
       *   <button>Option 2</button>
       *   <div slot="footer">Logged in as Admin</div>
       * </sg-dropdown>
       * ```
       * ### React
       * ```jsx
       * <sg-dropdown align="start" closeOnSelect={false}>
       *   <button slot="trigger">Menu</button>
       *   <div>Content here</div>
       * </sg-dropdown>
       * ```
       * ### Vanilla JS
       * ```html
       * <sg-dropdown id="myDropdown" align="end" close-on-select="false">
       *   <button slot="trigger">Options</button>
       *   <ul>
       *     <li>Item 1</li>
       *     <li>Item 2</li>
       *   </ul>
       * </sg-dropdown>
       * <script>
       *   const dropdown = document.querySelector('#myDropdown');
       *   dropdown.addEventListener('sgOpen', (e) => console.log('Opened'));
       *   dropdown.addEventListener('sgClose', (e) => console.log('Closed'));
       * </script>
       * ```
       */
      'sg-dropdown': LocalJSX.SgDropdown & JSXBase.HTMLAttributes<HTMLSgDropdownElement>;
    }
  }
}
