/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ContentType, ContentTypeChangeEvent, EditorChangeEvent, MediaItem, ViewMode, ViewModeChangeEvent } from "./packages/article-editor/src/utils";
import { EditorTranslations, SupportedLocale } from "./packages/article-editor/src/utils/i18n";
import { BadgeSize, BadgeVariant } from "./packages/badge/src/components/badge/badge";
import { ButtonShape, ButtonSize, ButtonVariant } from "./packages/button/src/components/button/button";
import { IconDefinition } from "./packages/icons/src/components/svg-icon/icons/builtin";
import { ModalSize } from "./packages/modal/src/components/modal/modal";
import { ThemeMode } from "./packages/theme-toggle/src/components/theme-toggle/theme-toggle";
export { ContentType, ContentTypeChangeEvent, EditorChangeEvent, MediaItem, ViewMode, ViewModeChangeEvent } from "./packages/article-editor/src/utils";
export { EditorTranslations, SupportedLocale } from "./packages/article-editor/src/utils/i18n";
export { BadgeSize, BadgeVariant } from "./packages/badge/src/components/badge/badge";
export { ButtonShape, ButtonSize, ButtonVariant } from "./packages/button/src/components/button/button";
export { IconDefinition } from "./packages/icons/src/components/svg-icon/icons/builtin";
export { ModalSize } from "./packages/modal/src/components/modal/modal";
export { ThemeMode } from "./packages/theme-toggle/src/components/theme-toggle/theme-toggle";
export namespace Components {
    /**
     * SageBox - Article Editor Component
     * A headless-ready article editor supporting HTML and Markdown modes
     * with live preview, formatting toolbar, and optional media library integration.
     * @example ```html
     * <sg-article-editor
     *   value="<p>Hello World</p>"
     *   mode="html"
     *   placeholder="Start writing..."
     * ></sg-article-editor>
     * ```
     */
    interface SgArticleEditor {
        /**
          * Available content types (comma-separated or array)
          * @default 'html,markdown'
         */
        "availableContentTypes": string;
        /**
          * @deprecated Use availableContentTypes instead
          * @default 'html,markdown'
         */
        "availableModes": string;
        /**
          * Available view modes (comma-separated or array)
          * @default 'editor,preview,split'
         */
        "availableViewModes": string;
        /**
          * Content syntax type (html or markdown)
          * @default 'html'
         */
        "contentType": ContentType;
        /**
          * Custom translations to override defaults
         */
        "customTranslations": Partial<EditorTranslations>;
        /**
          * Disabled state
          * @default false
         */
        "disabled": boolean;
        /**
          * Custom accent color (buttons, links)
         */
        "editorAccent": string;
        /**
          * Custom background color for the editor
         */
        "editorBg": string;
        /**
          * Custom secondary background color
         */
        "editorBgSecondary": string;
        /**
          * Custom tertiary background color
         */
        "editorBgTertiary": string;
        /**
          * Custom border color
         */
        "editorBorder": string;
        /**
          * Custom border radius
         */
        "editorBorderRadius": string;
        /**
          * Custom font family for code
         */
        "editorFontMono": string;
        /**
          * Custom font family for text
         */
        "editorFontSans": string;
        /**
          * Custom font size
         */
        "editorFontSize": string;
        /**
          * Custom text color
         */
        "editorText": string;
        /**
          * Custom secondary text color
         */
        "editorTextSecondary": string;
        /**
          * Enable external preview window
          * @default true
         */
        "enableExternalPreview": boolean;
        /**
          * Focus the editor
         */
        "focusEditor": () => Promise<void>;
        /**
          * Get the current content
         */
        "getContent": () => Promise<string>;
        /**
          * Get content as HTML (converts if in markdown mode)
         */
        "getHtml": () => Promise<string>;
        /**
          * Insert content at cursor position
         */
        "insertAtCursor": (content: string) => Promise<void>;
        /**
          * Insert a media item
         */
        "insertMedia": (media: MediaItem) => Promise<void>;
        /**
          * Locale for UI text (en, es, fr, de, pt, it, zh, ja, ko, ar)
          * @default 'en'
         */
        "locale": SupportedLocale;
        /**
          * Minimum height in pixels
          * @default 400
         */
        "minHeight": number;
        /**
          * @deprecated Use contentType instead
          * @default 'html'
         */
        "mode": ContentType;
        /**
          * Placeholder text when editor is empty
          * @default 'Start writing...'
         */
        "placeholder": string;
        /**
          * Read-only state
          * @default false
         */
        "readonly": boolean;
        /**
          * Set the content programmatically
         */
        "setContent": (content: string) => Promise<void>;
        /**
          * Show word/character count
          * @default true
         */
        "showWordCount": boolean;
        /**
          * Enable spell checking
          * @default true
         */
        "spellcheck": boolean;
        /**
          * The content value of the editor
          * @default ''
         */
        "value": string;
        /**
          * View mode (editor, preview, or split)
          * @default 'editor'
         */
        "viewMode": ViewMode;
    }
    /**
     * @example ### Angular
     * ```html
     * <sg-badge variant="success">Active</sg-badge>
     * <sg-badge variant="error" size="sm" dot>Offline</sg-badge>
     * <sg-badge variant="info" pill>New Feature</sg-badge>
     * <sg-badge variant="warning">
     *   <sg-icon slot="icon" name="alert-triangle" size="12"></sg-icon>
     *   Warning
     * </sg-badge>
     * ```
     * ### React
     * ```jsx
     * <sg-badge variant="primary" outlined>Beta</sg-badge>
     * <sg-badge variant="success" pulse>Live</sg-badge>
     * ```
     * ### Vanilla JS
     * ```html
     * <sg-badge variant="info" size="lg">Featured</sg-badge>
     * <sg-badge variant="neutral" removable id="tag1">Tag 1</sg-badge>
     * <script>
     *   document.querySelector('#tag1').addEventListener('sgRemove', (e) => {
     *     e.target.remove();
     *   });
     * </script>
     * ```
     */
    interface SgBadge {
        /**
          * Make the badge clickable/interactive
          * @default false
         */
        "clickable": boolean;
        /**
          * Show a status dot indicator
          * @default false
         */
        "dot": boolean;
        /**
          * Custom icon name (if using sg-icon internally)
         */
        "icon": string;
        /**
          * Display as outlined style (transparent background with border)
          * @default false
         */
        "outlined": boolean;
        /**
          * Display as pill shape (fully rounded)
          * @default false
         */
        "pill": boolean;
        /**
          * Apply pulse animation to the dot
          * @default false
         */
        "pulse": boolean;
        /**
          * Size of the badge
          * @default 'md'
         */
        "size": BadgeSize;
        /**
          * Size of the badge
         */
        "size"?: "xs" | "sm" | "md" | "lg";
        /**
          * Display as soft/subtle style (lighter background)
          * @default false
         */
        "soft": boolean;
        /**
          * Color variant of the badge
          * @default 'primary'
         */
        "variant": BadgeVariant;
        /**
          * Color variant
         */
        "variant"?: "primary" | "secondary" | "success" | "warning" | "error" | "info" | "neutral" | "purple" | "cyan";
    }
    /**
     * @component sg-button
     * @description A versatile button component with multiple variants, sizes, and states.
     * Framework-agnostic: works with Angular, React, Vue, and vanilla JS without wrappers.
     * @example <!-- ═══════════════════════════════════════════════════════════════════════════════
     *      VANILLA HTML / JS
     *      ═══════════════════════════════════════════════════════════════════════════════ -->
     * <sg-button>Click me</sg-button>
     * <sg-button variant="primary">Primary</sg-button>
     * <sg-button variant="outline" size="lg">Large Outline</sg-button>
     * <sg-button variant="success" leading-icon="check">Save</sg-button>
     * <sg-button loading>Loading...</sg-button>
     * <sg-button disabled>Disabled</sg-button>
     * <sg-button shape="pill" variant="secondary">Pill Button</sg-button>
     * <script>
     *   document.querySelector('sg-button').addEventListener('sgClick', (e) => {
     *     console.log('Button clicked!', e.detail);
     *   });
     * </script>
     * <!-- ═══════════════════════════════════════════════════════════════════════════════
     *      ANGULAR (no wrapper needed, add CUSTOM_ELEMENTS_SCHEMA)
     *      ═══════════════════════════════════════════════════════════════════════════════ -->
     * <sg-button
     *   variant="primary"
     *   [attr.loading]="isLoading || null"
     *   [attr.disabled]="isDisabled || null"
     *   (sgClick)="handleClick($event)">
     *   Save Changes
     * </sg-button>
     * <!-- ═══════════════════════════════════════════════════════════════════════════════
     *      REACT (use kebab-case attributes)
     *      ═══════════════════════════════════════════════════════════════════════════════ -->
     * <sg-button
     *   variant="primary"
     *   leading-icon="save"
     *   loading={isLoading}
     *   onSgClick={(e) => handleClick(e.detail)}>
     *   Save Changes
     * </sg-button>
     * @fires sgClick - Emitted when button is clicked (not disabled/loading)
     * @cssprop --sg-btn-bg - Button background color
     * @cssprop --sg-btn-color - Button text color
     * @cssprop --sg-btn-border-color - Button border color
     * @cssprop --sg-btn-radius - Button border radius
     * @cssprop --sg-btn-shadow - Button box shadow
     */
    interface SgButton {
        /**
          * Disable the button
          * @attr disabled
          * @default false
         */
        "disabled": boolean;
        /**
          * Accessible label
         */
        "label"?: string;
        /**
          * Leading icon name (from sg-icon)
          * @attr leading-icon
         */
        "leadingIcon"?: string;
        /**
          * Show loading spinner
          * @attr loading
          * @default false
         */
        "loading": boolean;
        /**
          * Loading text (replaces content while loading)
          * @attr loading-text
         */
        "loadingText"?: string;
        /**
          * Button shape
          * @attr shape
          * @default 'default'
         */
        "shape": ButtonShape;
        /**
          * Button size
          * @attr size
          * @default 'md'
         */
        "size": ButtonSize;
        /**
          * Trailing icon name (from sg-icon)
          * @attr trailing-icon
         */
        "trailingIcon"?: string;
        /**
          * Button type attribute
          * @attr type
          * @default 'button'
         */
        "type": 'button' | 'submit' | 'reset';
        /**
          * Button color variant
          * @attr variant
          * @default 'primary'
         */
        "variant": ButtonVariant;
    }
    /**
     * @example ### Angular
     * ```html
     * <sg-dropdown align="start" position="bottom">
     *   <button slot="trigger">Open Menu</button>
     *   <div slot="header">Settings</div>
     *   <button>Option 1</button>
     *   <button>Option 2</button>
     *   <div slot="footer">Logged in as Admin</div>
     * </sg-dropdown>
     * ```
     * ### React
     * ```jsx
     * <sg-dropdown align="start" closeOnSelect={false}>
     *   <button slot="trigger">Menu</button>
     *   <div>Content here</div>
     * </sg-dropdown>
     * ```
     * ### Vanilla JS
     * ```html
     * <sg-dropdown id="myDropdown" align="end" close-on-select="false">
     *   <button slot="trigger">Options</button>
     *   <ul>
     *     <li>Item 1</li>
     *     <li>Item 2</li>
     *   </ul>
     * </sg-dropdown>
     * <script>
     *   const dropdown = document.querySelector('#myDropdown');
     *   dropdown.addEventListener('sgOpen', (e) => console.log('Opened'));
     *   dropdown.addEventListener('sgClose', (e) => console.log('Closed'));
     * </script>
     * ```
     */
    interface SgDropdown {
        /**
          * Horizontal alignment of the dropdown content relative to trigger
          * @default 'start'
         */
        "align": 'start' | 'end' | 'center';
        /**
          * Horizontal alignment of the dropdown
         */
        "align"?: "start" | "end" | "center";
        /**
          * Closes the dropdown programmatically
         */
        "closeDropdown": () => Promise<void>;
        /**
          * Whether to close the dropdown when an item is selected/clicked
          * @default true
         */
        "closeOnSelect": boolean;
        /**
          * Whether the dropdown is disabled
          * @default false
         */
        "disabled": boolean;
        /**
          * Maximum height of the dropdown content for scrolling
          * @default '320px'
         */
        "maxHeight": string;
        /**
          * Minimum width of the dropdown content (e.g., "200px", "12rem")
          * @default '200px'
         */
        "minWidth": string;
        /**
          * Whether the dropdown is currently open
          * @default false
         */
        "open": boolean;
        /**
          * Opens the dropdown programmatically
         */
        "openDropdown": () => Promise<void>;
        /**
          * Vertical position of the dropdown content
          * @default 'bottom'
         */
        "position": 'bottom' | 'top';
        /**
          * Position of the dropdown relative to trigger
         */
        "position"?: "bottom" | "top";
        /**
          * Show a backdrop overlay (useful on mobile)
          * @default false
         */
        "showBackdrop": boolean;
        /**
          * Size variant
          * @default 'md'
         */
        "size": 'sm' | 'md' | 'lg';
        /**
          * Toggles the dropdown open/closed
         */
        "toggle": () => Promise<void>;
    }
    /**
     * @component sg-icon
     * @description SVG Icon component for SageBox - A flexible, accessible icon system
     * @example <!-- Basic usage with built-in icons -->
     * <sg-icon name="home"></sg-icon>
     * <sg-icon name="icon-home"></sg-icon>
     * <!-- With custom size -->
     * <sg-icon name="settings" size="32"></sg-icon>
     * <!-- With custom color (fill is an alias for color) -->
     * <sg-icon name="heart" color="#ff0000"></sg-icon>
     * <sg-icon name="heart" fill="#ff0000"></sg-icon>
     * <!-- Custom icon via src (fetches SVG file) -->
     * <sg-icon src="/assets/custom-icon.svg"></sg-icon>
     * <!-- Load icons from JSON file -->
     * <sg-icon name="my-icon" json-src="/assets/icons.json"></sg-icon>
     */
    interface SgIcon {
        /**
          * Color of the icon (CSS color value)
          * @default 'currentColor'
         */
        "color": string;
        /**
          * Whether the icon is decorative (hidden from screen readers)
          * @default false
         */
        "decorative": boolean;
        /**
          * Alias for color (for compatibility with legacy svg-icon components)
          * @default undefined
         */
        "fill"?: string;
        /**
          * Flip the icon horizontally
          * @default false
         */
        "flipH": boolean;
        /**
          * Flip the icon vertically
          * @default false
         */
        "flipV": boolean;
        /**
          * Get list of all registered user icons
         */
        "getRegisteredIcons": () => Promise<string[]>;
        /**
          * Check if an icon exists (built-in or user-registered)
         */
        "hasIcon": (name: string) => Promise<boolean>;
        /**
          * Height of the icon (overrides size)
         */
        "height"?: number | string;
        /**
          * URL to a JSON file containing icon definitions. The JSON should be an object mapping icon names to SVG strings. Icons are loaded once and cached globally.
          * @example <sg-icon name="my-icon" json-src="/assets/custom-icons.json"></sg-icon>
         */
        "jsonSrc"?: string;
        /**
          * Accessible label for screen readers. If not provided, defaults to "{name} icon" for non-decorative icons.
         */
        "label"?: string;
        /**
          * The name of the icon from the built-in library. Supports both 'name' and 'icon-name' formats for compatibility.
         */
        "name"?: string;
        /**
          * Register a single icon
          * @param name - Icon name to register
          * @param icon - SVG string or IconDefinition
          * @example SgIcon.registerIcon('my-custom-icon', '<svg viewBox="0 0 24 24">...</svg>');
         */
        "registerIcon": (name: string, icon: IconDefinition | string) => Promise<void>;
        /**
          * Register multiple icons at once
          * @param icons - Object with icon names as keys and SVG strings or IconDefinition as values
          * @example // Using SVG strings (recommended for users) SgIcon.registerIcons({   'my-icon': '<svg viewBox="0 0 24 24">...</svg>',   'another-icon': '<svg>...</svg>' });  // Using IconDefinition objects SgIcon.registerIcons({   'my-icon': { paths: ['M12 2...'], viewBox: '0 0 24 24' } });
         */
        "registerIcons": (icons: Record<string, IconDefinition | string>) => Promise<void>;
        /**
          * Rotation angle in degrees
         */
        "rotate"?: number;
        /**
          * Size of the icon in pixels
          * @default 24
         */
        "size": number | string;
        /**
          * Whether the icon should spin (useful for loading icons)
          * @default false
         */
        "spin": boolean;
        /**
          * URL to a custom SVG icon (alternative to name)
         */
        "src"?: string;
        /**
          * Stroke width for outline icons
         */
        "strokeWidth"?: number;
        /**
          * Width of the icon (overrides size)
         */
        "width"?: number | string;
    }
    /**
     * @component sg-modal
     * @description A modern modal dialog component built on the native HTML <dialog> element.
     * Provides built-in accessibility, focus trapping, and backdrop handling.
     * @example <!-- ═══════════════════════════════════════════════════════════════════════════════
     *      VANILLA HTML / JS
     *      ═══════════════════════════════════════════════════════════════════════════════ -->
     * <sg-modal id="myModal" header="Confirm Action">
     *   <p>Are you sure you want to continue?</p>
     *   <div slot="footer">
     *     <sg-button variant="secondary" onclick="document.getElementById('myModal').close()">Cancel</sg-button>
     *     <sg-button variant="primary">Confirm</sg-button>
     *   </div>
     * </sg-modal>
     * <sg-button onclick="document.getElementById('myModal').showModal()">Open Modal</sg-button>
     * <script>
     *   document.getElementById('myModal').addEventListener('sgClose', (e) => {
     *     console.log('Modal closed with:', e.detail);
     *   });
     * </script>
     * <!-- ═══════════════════════════════════════════════════════════════════════════════
     *      ANGULAR
     *      ═══════════════════════════════════════════════════════════════════════════════ -->
     * <sg-modal
     *   #modal
     *   header="Edit Profile"
     *   [attr.open]="isOpen || null"
     *   (sgClose)="onClose($event)"
     *   (sgCancel)="onCancel()">
     *   <form>...</form>
     *   <div slot="footer">
     *     <sg-button (sgClick)="modal.close()">Cancel</sg-button>
     *     <sg-button variant="primary" (sgClick)="save()">Save</sg-button>
     *   </div>
     * </sg-modal>
     * <!-- ═══════════════════════════════════════════════════════════════════════════════
     *      REACT
     *      ═══════════════════════════════════════════════════════════════════════════════ -->
     * <sg-modal
     *   ref={modalRef}
     *   header="Delete Item"
     *   size="sm"
     *   onSgClose={(e) => handleClose(e.detail)}
     *   onSgCancel={() => handleCancel()}>
     *   <p>This action cannot be undone.</p>
     *   <div slot="footer">
     *     <sg-button onClick={() => modalRef.current.close()}>Cancel</sg-button>
     *     <sg-button variant="error" onClick={() => handleDelete()}>Delete</sg-button>
     *   </div>
     * </sg-modal>
     * @fires sgOpen - Emitted when the modal opens
     * @fires sgClose - Emitted when the modal closes, detail contains returnValue
     * @fires sgCancel - Emitted when user cancels (Escape or backdrop click)
     * @cssprop --sg-modal-width - Modal width (default: auto based on size)
     * @cssprop --sg-modal-max-width - Modal max width
     * @cssprop --sg-modal-max-height - Modal max height
     * @cssprop --sg-modal-padding - Modal content padding
     * @cssprop --sg-modal-radius - Modal border radius
     * @cssprop --sg-modal-backdrop-color - Backdrop overlay color
     * @cssprop --sg-modal-shadow - Modal box shadow
     */
    interface SgModal {
        /**
          * Closes the modal dialog
          * @param returnValue - Optional value to pass to the close event
         */
        "close": (returnValue?: string) => Promise<void>;
        /**
          * Whether the modal can be closed by clicking the backdrop
          * @default true
         */
        "closeOnBackdrop": boolean;
        /**
          * Whether the modal can be closed by pressing Escape
          * @default true
         */
        "closeOnEscape": boolean;
        /**
          * Modal header text
         */
        "header"?: string;
        /**
          * Whether the modal is a non-modal dialog (doesn't block interaction)
          * @default false
         */
        "nonModal": boolean;
        /**
          * Whether the modal is open
          * @default false
         */
        "open": boolean;
        /**
          * Whether to show the backdrop overlay
          * @default true
         */
        "overlay": boolean;
        /**
          * Opens as non-modal dialog
         */
        "show": () => Promise<void>;
        /**
          * Whether to show the close button in the header
          * @default true
         */
        "showCloseButton": boolean;
        /**
          * Opens the modal dialog
         */
        "showModal": () => Promise<void>;
        /**
          * Modal size preset
          * @default 'md'
         */
        "size": ModalSize;
    }
    /**
     * @component sg-skeleton
     * @description Skeleton loading placeholder component for SageBox
     * @example <sg-skeleton variant="text" width="200px" height="1rem"></sg-skeleton>
     * <sg-skeleton variant="rect" width="100%" height="200px"></sg-skeleton>
     * <sg-skeleton variant="circle" width="48px" height="48px"></sg-skeleton>
     */
    interface SgSkeleton {
        /**
          * Animation type - shimmer: Gradient animation (default) - pulse: Opacity pulse animation - none: No animation
          * @default 'shimmer'
         */
        "animation": 'shimmer' | 'pulse' | 'none';
        /**
          * The height of the skeleton
          * @default '1rem'
         */
        "height": string;
        /**
          * The shape variant of the skeleton - text: Slightly rounded, good for text placeholders - rect: More rounded, good for cards/images - circle: Fully rounded, good for avatars
          * @default 'text'
         */
        "variant": 'text' | 'rect' | 'circle';
        /**
          * The width of the skeleton
          * @default '100%'
         */
        "width": string;
    }
    interface SgThemeToggle {
        /**
          * Size of the toggle button
          * @default 'md'
         */
        "size": 'sm' | 'md' | 'lg';
        /**
          * The current theme mode
          * @default 'system'
         */
        "theme": ThemeMode;
    }
}
export interface SgArticleEditorCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSgArticleEditorElement;
}
export interface SgButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSgButtonElement;
}
export interface SgDropdownCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSgDropdownElement;
}
export interface SgModalCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSgModalElement;
}
export interface SgThemeToggleCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSgThemeToggleElement;
}
declare global {
    interface HTMLSgArticleEditorElementEventMap {
        "editorChange": EditorChangeEvent;
        "contentTypeChange": ContentTypeChangeEvent;
        "viewModeChange": ViewModeChangeEvent;
        "editorModeChange": ContentTypeChangeEvent;
        "mediaLibraryOpen": void;
        "mediaInsert": MediaItem;
    }
    /**
     * SageBox - Article Editor Component
     * A headless-ready article editor supporting HTML and Markdown modes
     * with live preview, formatting toolbar, and optional media library integration.
     * @example ```html
     * <sg-article-editor
     *   value="<p>Hello World</p>"
     *   mode="html"
     *   placeholder="Start writing..."
     * ></sg-article-editor>
     * ```
     */
    interface HTMLSgArticleEditorElement extends Components.SgArticleEditor, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSgArticleEditorElementEventMap>(type: K, listener: (this: HTMLSgArticleEditorElement, ev: SgArticleEditorCustomEvent<HTMLSgArticleEditorElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSgArticleEditorElementEventMap>(type: K, listener: (this: HTMLSgArticleEditorElement, ev: SgArticleEditorCustomEvent<HTMLSgArticleEditorElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSgArticleEditorElement: {
        prototype: HTMLSgArticleEditorElement;
        new (): HTMLSgArticleEditorElement;
    };
    /**
     * @example ### Angular
     * ```html
     * <sg-badge variant="success">Active</sg-badge>
     * <sg-badge variant="error" size="sm" dot>Offline</sg-badge>
     * <sg-badge variant="info" pill>New Feature</sg-badge>
     * <sg-badge variant="warning">
     *   <sg-icon slot="icon" name="alert-triangle" size="12"></sg-icon>
     *   Warning
     * </sg-badge>
     * ```
     * ### React
     * ```jsx
     * <sg-badge variant="primary" outlined>Beta</sg-badge>
     * <sg-badge variant="success" pulse>Live</sg-badge>
     * ```
     * ### Vanilla JS
     * ```html
     * <sg-badge variant="info" size="lg">Featured</sg-badge>
     * <sg-badge variant="neutral" removable id="tag1">Tag 1</sg-badge>
     * <script>
     *   document.querySelector('#tag1').addEventListener('sgRemove', (e) => {
     *     e.target.remove();
     *   });
     * </script>
     * ```
     */
    interface HTMLSgBadgeElement extends Components.SgBadge, HTMLStencilElement {
    }
    var HTMLSgBadgeElement: {
        prototype: HTMLSgBadgeElement;
        new (): HTMLSgBadgeElement;
    };
    interface HTMLSgButtonElementEventMap {
        "sgClick": MouseEvent;
    }
    /**
     * @component sg-button
     * @description A versatile button component with multiple variants, sizes, and states.
     * Framework-agnostic: works with Angular, React, Vue, and vanilla JS without wrappers.
     * @example <!-- ═══════════════════════════════════════════════════════════════════════════════
     *      VANILLA HTML / JS
     *      ═══════════════════════════════════════════════════════════════════════════════ -->
     * <sg-button>Click me</sg-button>
     * <sg-button variant="primary">Primary</sg-button>
     * <sg-button variant="outline" size="lg">Large Outline</sg-button>
     * <sg-button variant="success" leading-icon="check">Save</sg-button>
     * <sg-button loading>Loading...</sg-button>
     * <sg-button disabled>Disabled</sg-button>
     * <sg-button shape="pill" variant="secondary">Pill Button</sg-button>
     * <script>
     *   document.querySelector('sg-button').addEventListener('sgClick', (e) => {
     *     console.log('Button clicked!', e.detail);
     *   });
     * </script>
     * <!-- ═══════════════════════════════════════════════════════════════════════════════
     *      ANGULAR (no wrapper needed, add CUSTOM_ELEMENTS_SCHEMA)
     *      ═══════════════════════════════════════════════════════════════════════════════ -->
     * <sg-button
     *   variant="primary"
     *   [attr.loading]="isLoading || null"
     *   [attr.disabled]="isDisabled || null"
     *   (sgClick)="handleClick($event)">
     *   Save Changes
     * </sg-button>
     * <!-- ═══════════════════════════════════════════════════════════════════════════════
     *      REACT (use kebab-case attributes)
     *      ═══════════════════════════════════════════════════════════════════════════════ -->
     * <sg-button
     *   variant="primary"
     *   leading-icon="save"
     *   loading={isLoading}
     *   onSgClick={(e) => handleClick(e.detail)}>
     *   Save Changes
     * </sg-button>
     * @fires sgClick - Emitted when button is clicked (not disabled/loading)
     * @cssprop --sg-btn-bg - Button background color
     * @cssprop --sg-btn-color - Button text color
     * @cssprop --sg-btn-border-color - Button border color
     * @cssprop --sg-btn-radius - Button border radius
     * @cssprop --sg-btn-shadow - Button box shadow
     */
    interface HTMLSgButtonElement extends Components.SgButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSgButtonElementEventMap>(type: K, listener: (this: HTMLSgButtonElement, ev: SgButtonCustomEvent<HTMLSgButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSgButtonElementEventMap>(type: K, listener: (this: HTMLSgButtonElement, ev: SgButtonCustomEvent<HTMLSgButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSgButtonElement: {
        prototype: HTMLSgButtonElement;
        new (): HTMLSgButtonElement;
    };
    interface HTMLSgDropdownElementEventMap {
        "sgOpen": void;
        "sgClose": void;
        "sgToggle": boolean;
    }
    /**
     * @example ### Angular
     * ```html
     * <sg-dropdown align="start" position="bottom">
     *   <button slot="trigger">Open Menu</button>
     *   <div slot="header">Settings</div>
     *   <button>Option 1</button>
     *   <button>Option 2</button>
     *   <div slot="footer">Logged in as Admin</div>
     * </sg-dropdown>
     * ```
     * ### React
     * ```jsx
     * <sg-dropdown align="start" closeOnSelect={false}>
     *   <button slot="trigger">Menu</button>
     *   <div>Content here</div>
     * </sg-dropdown>
     * ```
     * ### Vanilla JS
     * ```html
     * <sg-dropdown id="myDropdown" align="end" close-on-select="false">
     *   <button slot="trigger">Options</button>
     *   <ul>
     *     <li>Item 1</li>
     *     <li>Item 2</li>
     *   </ul>
     * </sg-dropdown>
     * <script>
     *   const dropdown = document.querySelector('#myDropdown');
     *   dropdown.addEventListener('sgOpen', (e) => console.log('Opened'));
     *   dropdown.addEventListener('sgClose', (e) => console.log('Closed'));
     * </script>
     * ```
     */
    interface HTMLSgDropdownElement extends Components.SgDropdown, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSgDropdownElementEventMap>(type: K, listener: (this: HTMLSgDropdownElement, ev: SgDropdownCustomEvent<HTMLSgDropdownElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSgDropdownElementEventMap>(type: K, listener: (this: HTMLSgDropdownElement, ev: SgDropdownCustomEvent<HTMLSgDropdownElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSgDropdownElement: {
        prototype: HTMLSgDropdownElement;
        new (): HTMLSgDropdownElement;
    };
    /**
     * @component sg-icon
     * @description SVG Icon component for SageBox - A flexible, accessible icon system
     * @example <!-- Basic usage with built-in icons -->
     * <sg-icon name="home"></sg-icon>
     * <sg-icon name="icon-home"></sg-icon>
     * <!-- With custom size -->
     * <sg-icon name="settings" size="32"></sg-icon>
     * <!-- With custom color (fill is an alias for color) -->
     * <sg-icon name="heart" color="#ff0000"></sg-icon>
     * <sg-icon name="heart" fill="#ff0000"></sg-icon>
     * <!-- Custom icon via src (fetches SVG file) -->
     * <sg-icon src="/assets/custom-icon.svg"></sg-icon>
     * <!-- Load icons from JSON file -->
     * <sg-icon name="my-icon" json-src="/assets/icons.json"></sg-icon>
     */
    interface HTMLSgIconElement extends Components.SgIcon, HTMLStencilElement {
    }
    var HTMLSgIconElement: {
        prototype: HTMLSgIconElement;
        new (): HTMLSgIconElement;
    };
    interface HTMLSgModalElementEventMap {
        "sgOpen": void;
        "sgClose": string;
        "sgCancel": void;
    }
    /**
     * @component sg-modal
     * @description A modern modal dialog component built on the native HTML <dialog> element.
     * Provides built-in accessibility, focus trapping, and backdrop handling.
     * @example <!-- ═══════════════════════════════════════════════════════════════════════════════
     *      VANILLA HTML / JS
     *      ═══════════════════════════════════════════════════════════════════════════════ -->
     * <sg-modal id="myModal" header="Confirm Action">
     *   <p>Are you sure you want to continue?</p>
     *   <div slot="footer">
     *     <sg-button variant="secondary" onclick="document.getElementById('myModal').close()">Cancel</sg-button>
     *     <sg-button variant="primary">Confirm</sg-button>
     *   </div>
     * </sg-modal>
     * <sg-button onclick="document.getElementById('myModal').showModal()">Open Modal</sg-button>
     * <script>
     *   document.getElementById('myModal').addEventListener('sgClose', (e) => {
     *     console.log('Modal closed with:', e.detail);
     *   });
     * </script>
     * <!-- ═══════════════════════════════════════════════════════════════════════════════
     *      ANGULAR
     *      ═══════════════════════════════════════════════════════════════════════════════ -->
     * <sg-modal
     *   #modal
     *   header="Edit Profile"
     *   [attr.open]="isOpen || null"
     *   (sgClose)="onClose($event)"
     *   (sgCancel)="onCancel()">
     *   <form>...</form>
     *   <div slot="footer">
     *     <sg-button (sgClick)="modal.close()">Cancel</sg-button>
     *     <sg-button variant="primary" (sgClick)="save()">Save</sg-button>
     *   </div>
     * </sg-modal>
     * <!-- ═══════════════════════════════════════════════════════════════════════════════
     *      REACT
     *      ═══════════════════════════════════════════════════════════════════════════════ -->
     * <sg-modal
     *   ref={modalRef}
     *   header="Delete Item"
     *   size="sm"
     *   onSgClose={(e) => handleClose(e.detail)}
     *   onSgCancel={() => handleCancel()}>
     *   <p>This action cannot be undone.</p>
     *   <div slot="footer">
     *     <sg-button onClick={() => modalRef.current.close()}>Cancel</sg-button>
     *     <sg-button variant="error" onClick={() => handleDelete()}>Delete</sg-button>
     *   </div>
     * </sg-modal>
     * @fires sgOpen - Emitted when the modal opens
     * @fires sgClose - Emitted when the modal closes, detail contains returnValue
     * @fires sgCancel - Emitted when user cancels (Escape or backdrop click)
     * @cssprop --sg-modal-width - Modal width (default: auto based on size)
     * @cssprop --sg-modal-max-width - Modal max width
     * @cssprop --sg-modal-max-height - Modal max height
     * @cssprop --sg-modal-padding - Modal content padding
     * @cssprop --sg-modal-radius - Modal border radius
     * @cssprop --sg-modal-backdrop-color - Backdrop overlay color
     * @cssprop --sg-modal-shadow - Modal box shadow
     */
    interface HTMLSgModalElement extends Components.SgModal, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSgModalElementEventMap>(type: K, listener: (this: HTMLSgModalElement, ev: SgModalCustomEvent<HTMLSgModalElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSgModalElementEventMap>(type: K, listener: (this: HTMLSgModalElement, ev: SgModalCustomEvent<HTMLSgModalElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSgModalElement: {
        prototype: HTMLSgModalElement;
        new (): HTMLSgModalElement;
    };
    /**
     * @component sg-skeleton
     * @description Skeleton loading placeholder component for SageBox
     * @example <sg-skeleton variant="text" width="200px" height="1rem"></sg-skeleton>
     * <sg-skeleton variant="rect" width="100%" height="200px"></sg-skeleton>
     * <sg-skeleton variant="circle" width="48px" height="48px"></sg-skeleton>
     */
    interface HTMLSgSkeletonElement extends Components.SgSkeleton, HTMLStencilElement {
    }
    var HTMLSgSkeletonElement: {
        prototype: HTMLSgSkeletonElement;
        new (): HTMLSgSkeletonElement;
    };
    interface HTMLSgThemeToggleElementEventMap {
        "sgThemeChange": ThemeMode;
    }
    interface HTMLSgThemeToggleElement extends Components.SgThemeToggle, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSgThemeToggleElementEventMap>(type: K, listener: (this: HTMLSgThemeToggleElement, ev: SgThemeToggleCustomEvent<HTMLSgThemeToggleElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSgThemeToggleElementEventMap>(type: K, listener: (this: HTMLSgThemeToggleElement, ev: SgThemeToggleCustomEvent<HTMLSgThemeToggleElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSgThemeToggleElement: {
        prototype: HTMLSgThemeToggleElement;
        new (): HTMLSgThemeToggleElement;
    };
    interface HTMLElementTagNameMap {
        "sg-article-editor": HTMLSgArticleEditorElement;
        "sg-badge": HTMLSgBadgeElement;
        "sg-button": HTMLSgButtonElement;
        "sg-dropdown": HTMLSgDropdownElement;
        "sg-icon": HTMLSgIconElement;
        "sg-modal": HTMLSgModalElement;
        "sg-skeleton": HTMLSgSkeletonElement;
        "sg-theme-toggle": HTMLSgThemeToggleElement;
    }
}
declare namespace LocalJSX {
    /**
     * SageBox - Article Editor Component
     * A headless-ready article editor supporting HTML and Markdown modes
     * with live preview, formatting toolbar, and optional media library integration.
     * @example ```html
     * <sg-article-editor
     *   value="<p>Hello World</p>"
     *   mode="html"
     *   placeholder="Start writing..."
     * ></sg-article-editor>
     * ```
     */
    interface SgArticleEditor {
        /**
          * Available content types (comma-separated or array)
          * @default 'html,markdown'
         */
        "availableContentTypes"?: string;
        /**
          * @deprecated Use availableContentTypes instead
          * @default 'html,markdown'
         */
        "availableModes"?: string;
        /**
          * Available view modes (comma-separated or array)
          * @default 'editor,preview,split'
         */
        "availableViewModes"?: string;
        /**
          * Content syntax type (html or markdown)
          * @default 'html'
         */
        "contentType"?: ContentType;
        /**
          * Custom translations to override defaults
         */
        "customTranslations"?: Partial<EditorTranslations>;
        /**
          * Disabled state
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Custom accent color (buttons, links)
         */
        "editorAccent"?: string;
        /**
          * Custom background color for the editor
         */
        "editorBg"?: string;
        /**
          * Custom secondary background color
         */
        "editorBgSecondary"?: string;
        /**
          * Custom tertiary background color
         */
        "editorBgTertiary"?: string;
        /**
          * Custom border color
         */
        "editorBorder"?: string;
        /**
          * Custom border radius
         */
        "editorBorderRadius"?: string;
        /**
          * Custom font family for code
         */
        "editorFontMono"?: string;
        /**
          * Custom font family for text
         */
        "editorFontSans"?: string;
        /**
          * Custom font size
         */
        "editorFontSize"?: string;
        /**
          * Custom text color
         */
        "editorText"?: string;
        /**
          * Custom secondary text color
         */
        "editorTextSecondary"?: string;
        /**
          * Enable external preview window
          * @default true
         */
        "enableExternalPreview"?: boolean;
        /**
          * Locale for UI text (en, es, fr, de, pt, it, zh, ja, ko, ar)
          * @default 'en'
         */
        "locale"?: SupportedLocale;
        /**
          * Minimum height in pixels
          * @default 400
         */
        "minHeight"?: number;
        /**
          * @deprecated Use contentType instead
          * @default 'html'
         */
        "mode"?: ContentType;
        /**
          * Emitted when the content type changes
         */
        "onContentTypeChange"?: (event: SgArticleEditorCustomEvent<ContentTypeChangeEvent>) => void;
        /**
          * Emitted when the content changes
         */
        "onEditorChange"?: (event: SgArticleEditorCustomEvent<EditorChangeEvent>) => void;
        /**
          * @deprecated Use contentTypeChange instead
         */
        "onEditorModeChange"?: (event: SgArticleEditorCustomEvent<ContentTypeChangeEvent>) => void;
        /**
          * Emitted when a media item should be inserted
         */
        "onMediaInsert"?: (event: SgArticleEditorCustomEvent<MediaItem>) => void;
        /**
          * Emitted when media library is requested
         */
        "onMediaLibraryOpen"?: (event: SgArticleEditorCustomEvent<void>) => void;
        /**
          * Emitted when the view mode changes
         */
        "onViewModeChange"?: (event: SgArticleEditorCustomEvent<ViewModeChangeEvent>) => void;
        /**
          * Placeholder text when editor is empty
          * @default 'Start writing...'
         */
        "placeholder"?: string;
        /**
          * Read-only state
          * @default false
         */
        "readonly"?: boolean;
        /**
          * Show word/character count
          * @default true
         */
        "showWordCount"?: boolean;
        /**
          * Enable spell checking
          * @default true
         */
        "spellcheck"?: boolean;
        /**
          * The content value of the editor
          * @default ''
         */
        "value"?: string;
        /**
          * View mode (editor, preview, or split)
          * @default 'editor'
         */
        "viewMode"?: ViewMode;
    }
    /**
     * @example ### Angular
     * ```html
     * <sg-badge variant="success">Active</sg-badge>
     * <sg-badge variant="error" size="sm" dot>Offline</sg-badge>
     * <sg-badge variant="info" pill>New Feature</sg-badge>
     * <sg-badge variant="warning">
     *   <sg-icon slot="icon" name="alert-triangle" size="12"></sg-icon>
     *   Warning
     * </sg-badge>
     * ```
     * ### React
     * ```jsx
     * <sg-badge variant="primary" outlined>Beta</sg-badge>
     * <sg-badge variant="success" pulse>Live</sg-badge>
     * ```
     * ### Vanilla JS
     * ```html
     * <sg-badge variant="info" size="lg">Featured</sg-badge>
     * <sg-badge variant="neutral" removable id="tag1">Tag 1</sg-badge>
     * <script>
     *   document.querySelector('#tag1').addEventListener('sgRemove', (e) => {
     *     e.target.remove();
     *   });
     * </script>
     * ```
     */
    interface SgBadge {
        /**
          * Make the badge clickable/interactive
          * @default false
         */
        "clickable"?: boolean;
        /**
          * Show a status dot indicator
          * @default false
         */
        "dot"?: boolean;
        /**
          * Custom icon name (if using sg-icon internally)
         */
        "icon"?: string;
        /**
          * Display as outlined style (transparent background with border)
          * @default false
         */
        "outlined"?: boolean;
        /**
          * Display as pill shape (fully rounded)
          * @default false
         */
        "pill"?: boolean;
        /**
          * Apply pulse animation to the dot
          * @default false
         */
        "pulse"?: boolean;
        /**
          * Size of the badge
          * @default 'md'
         */
        "size"?: BadgeSize;
        /**
          * Size of the badge
         */
        "size"?: "xs" | "sm" | "md" | "lg";
        /**
          * Display as soft/subtle style (lighter background)
          * @default false
         */
        "soft"?: boolean;
        /**
          * Color variant of the badge
          * @default 'primary'
         */
        "variant"?: BadgeVariant;
        /**
          * Color variant
         */
        "variant"?: "primary" | "secondary" | "success" | "warning" | "error" | "info" | "neutral" | "purple" | "cyan";
    }
    /**
     * @component sg-button
     * @description A versatile button component with multiple variants, sizes, and states.
     * Framework-agnostic: works with Angular, React, Vue, and vanilla JS without wrappers.
     * @example <!-- ═══════════════════════════════════════════════════════════════════════════════
     *      VANILLA HTML / JS
     *      ═══════════════════════════════════════════════════════════════════════════════ -->
     * <sg-button>Click me</sg-button>
     * <sg-button variant="primary">Primary</sg-button>
     * <sg-button variant="outline" size="lg">Large Outline</sg-button>
     * <sg-button variant="success" leading-icon="check">Save</sg-button>
     * <sg-button loading>Loading...</sg-button>
     * <sg-button disabled>Disabled</sg-button>
     * <sg-button shape="pill" variant="secondary">Pill Button</sg-button>
     * <script>
     *   document.querySelector('sg-button').addEventListener('sgClick', (e) => {
     *     console.log('Button clicked!', e.detail);
     *   });
     * </script>
     * <!-- ═══════════════════════════════════════════════════════════════════════════════
     *      ANGULAR (no wrapper needed, add CUSTOM_ELEMENTS_SCHEMA)
     *      ═══════════════════════════════════════════════════════════════════════════════ -->
     * <sg-button
     *   variant="primary"
     *   [attr.loading]="isLoading || null"
     *   [attr.disabled]="isDisabled || null"
     *   (sgClick)="handleClick($event)">
     *   Save Changes
     * </sg-button>
     * <!-- ═══════════════════════════════════════════════════════════════════════════════
     *      REACT (use kebab-case attributes)
     *      ═══════════════════════════════════════════════════════════════════════════════ -->
     * <sg-button
     *   variant="primary"
     *   leading-icon="save"
     *   loading={isLoading}
     *   onSgClick={(e) => handleClick(e.detail)}>
     *   Save Changes
     * </sg-button>
     * @fires sgClick - Emitted when button is clicked (not disabled/loading)
     * @cssprop --sg-btn-bg - Button background color
     * @cssprop --sg-btn-color - Button text color
     * @cssprop --sg-btn-border-color - Button border color
     * @cssprop --sg-btn-radius - Button border radius
     * @cssprop --sg-btn-shadow - Button box shadow
     */
    interface SgButton {
        /**
          * Disable the button
          * @attr disabled
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Accessible label
         */
        "label"?: string;
        /**
          * Leading icon name (from sg-icon)
          * @attr leading-icon
         */
        "leadingIcon"?: string;
        /**
          * Show loading spinner
          * @attr loading
          * @default false
         */
        "loading"?: boolean;
        /**
          * Loading text (replaces content while loading)
          * @attr loading-text
         */
        "loadingText"?: string;
        /**
          * Click event (emitted when not disabled/loading)
         */
        "onSgClick"?: (event: SgButtonCustomEvent<MouseEvent>) => void;
        /**
          * Button shape
          * @attr shape
          * @default 'default'
         */
        "shape"?: ButtonShape;
        /**
          * Button size
          * @attr size
          * @default 'md'
         */
        "size"?: ButtonSize;
        /**
          * Trailing icon name (from sg-icon)
          * @attr trailing-icon
         */
        "trailingIcon"?: string;
        /**
          * Button type attribute
          * @attr type
          * @default 'button'
         */
        "type"?: 'button' | 'submit' | 'reset';
        /**
          * Button color variant
          * @attr variant
          * @default 'primary'
         */
        "variant"?: ButtonVariant;
    }
    /**
     * @example ### Angular
     * ```html
     * <sg-dropdown align="start" position="bottom">
     *   <button slot="trigger">Open Menu</button>
     *   <div slot="header">Settings</div>
     *   <button>Option 1</button>
     *   <button>Option 2</button>
     *   <div slot="footer">Logged in as Admin</div>
     * </sg-dropdown>
     * ```
     * ### React
     * ```jsx
     * <sg-dropdown align="start" closeOnSelect={false}>
     *   <button slot="trigger">Menu</button>
     *   <div>Content here</div>
     * </sg-dropdown>
     * ```
     * ### Vanilla JS
     * ```html
     * <sg-dropdown id="myDropdown" align="end" close-on-select="false">
     *   <button slot="trigger">Options</button>
     *   <ul>
     *     <li>Item 1</li>
     *     <li>Item 2</li>
     *   </ul>
     * </sg-dropdown>
     * <script>
     *   const dropdown = document.querySelector('#myDropdown');
     *   dropdown.addEventListener('sgOpen', (e) => console.log('Opened'));
     *   dropdown.addEventListener('sgClose', (e) => console.log('Closed'));
     * </script>
     * ```
     */
    interface SgDropdown {
        /**
          * Horizontal alignment of the dropdown content relative to trigger
          * @default 'start'
         */
        "align"?: 'start' | 'end' | 'center';
        /**
          * Horizontal alignment of the dropdown
         */
        "align"?: "start" | "end" | "center";
        /**
          * Whether to close the dropdown when an item is selected/clicked
          * @default true
         */
        "closeOnSelect"?: boolean;
        /**
          * Whether the dropdown is disabled
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Maximum height of the dropdown content for scrolling
          * @default '320px'
         */
        "maxHeight"?: string;
        /**
          * Minimum width of the dropdown content (e.g., "200px", "12rem")
          * @default '200px'
         */
        "minWidth"?: string;
        /**
          * Emitted when the dropdown closes
         */
        "onSgClose"?: (event: SgDropdownCustomEvent<void>) => void;
        /**
          * Emitted when the dropdown opens
         */
        "onSgOpen"?: (event: SgDropdownCustomEvent<void>) => void;
        /**
          * Emitted when the open state changes
         */
        "onSgToggle"?: (event: SgDropdownCustomEvent<boolean>) => void;
        /**
          * Whether the dropdown is currently open
          * @default false
         */
        "open"?: boolean;
        /**
          * Vertical position of the dropdown content
          * @default 'bottom'
         */
        "position"?: 'bottom' | 'top';
        /**
          * Position of the dropdown relative to trigger
         */
        "position"?: "bottom" | "top";
        /**
          * Show a backdrop overlay (useful on mobile)
          * @default false
         */
        "showBackdrop"?: boolean;
        /**
          * Size variant
          * @default 'md'
         */
        "size"?: 'sm' | 'md' | 'lg';
    }
    /**
     * @component sg-icon
     * @description SVG Icon component for SageBox - A flexible, accessible icon system
     * @example <!-- Basic usage with built-in icons -->
     * <sg-icon name="home"></sg-icon>
     * <sg-icon name="icon-home"></sg-icon>
     * <!-- With custom size -->
     * <sg-icon name="settings" size="32"></sg-icon>
     * <!-- With custom color (fill is an alias for color) -->
     * <sg-icon name="heart" color="#ff0000"></sg-icon>
     * <sg-icon name="heart" fill="#ff0000"></sg-icon>
     * <!-- Custom icon via src (fetches SVG file) -->
     * <sg-icon src="/assets/custom-icon.svg"></sg-icon>
     * <!-- Load icons from JSON file -->
     * <sg-icon name="my-icon" json-src="/assets/icons.json"></sg-icon>
     */
    interface SgIcon {
        /**
          * Color of the icon (CSS color value)
          * @default 'currentColor'
         */
        "color"?: string;
        /**
          * Whether the icon is decorative (hidden from screen readers)
          * @default false
         */
        "decorative"?: boolean;
        /**
          * Alias for color (for compatibility with legacy svg-icon components)
          * @default undefined
         */
        "fill"?: string;
        /**
          * Flip the icon horizontally
          * @default false
         */
        "flipH"?: boolean;
        /**
          * Flip the icon vertically
          * @default false
         */
        "flipV"?: boolean;
        /**
          * Height of the icon (overrides size)
         */
        "height"?: number | string;
        /**
          * URL to a JSON file containing icon definitions. The JSON should be an object mapping icon names to SVG strings. Icons are loaded once and cached globally.
          * @example <sg-icon name="my-icon" json-src="/assets/custom-icons.json"></sg-icon>
         */
        "jsonSrc"?: string;
        /**
          * Accessible label for screen readers. If not provided, defaults to "{name} icon" for non-decorative icons.
         */
        "label"?: string;
        /**
          * The name of the icon from the built-in library. Supports both 'name' and 'icon-name' formats for compatibility.
         */
        "name"?: string;
        /**
          * Rotation angle in degrees
         */
        "rotate"?: number;
        /**
          * Size of the icon in pixels
          * @default 24
         */
        "size"?: number | string;
        /**
          * Whether the icon should spin (useful for loading icons)
          * @default false
         */
        "spin"?: boolean;
        /**
          * URL to a custom SVG icon (alternative to name)
         */
        "src"?: string;
        /**
          * Stroke width for outline icons
         */
        "strokeWidth"?: number;
        /**
          * Width of the icon (overrides size)
         */
        "width"?: number | string;
    }
    /**
     * @component sg-modal
     * @description A modern modal dialog component built on the native HTML <dialog> element.
     * Provides built-in accessibility, focus trapping, and backdrop handling.
     * @example <!-- ═══════════════════════════════════════════════════════════════════════════════
     *      VANILLA HTML / JS
     *      ═══════════════════════════════════════════════════════════════════════════════ -->
     * <sg-modal id="myModal" header="Confirm Action">
     *   <p>Are you sure you want to continue?</p>
     *   <div slot="footer">
     *     <sg-button variant="secondary" onclick="document.getElementById('myModal').close()">Cancel</sg-button>
     *     <sg-button variant="primary">Confirm</sg-button>
     *   </div>
     * </sg-modal>
     * <sg-button onclick="document.getElementById('myModal').showModal()">Open Modal</sg-button>
     * <script>
     *   document.getElementById('myModal').addEventListener('sgClose', (e) => {
     *     console.log('Modal closed with:', e.detail);
     *   });
     * </script>
     * <!-- ═══════════════════════════════════════════════════════════════════════════════
     *      ANGULAR
     *      ═══════════════════════════════════════════════════════════════════════════════ -->
     * <sg-modal
     *   #modal
     *   header="Edit Profile"
     *   [attr.open]="isOpen || null"
     *   (sgClose)="onClose($event)"
     *   (sgCancel)="onCancel()">
     *   <form>...</form>
     *   <div slot="footer">
     *     <sg-button (sgClick)="modal.close()">Cancel</sg-button>
     *     <sg-button variant="primary" (sgClick)="save()">Save</sg-button>
     *   </div>
     * </sg-modal>
     * <!-- ═══════════════════════════════════════════════════════════════════════════════
     *      REACT
     *      ═══════════════════════════════════════════════════════════════════════════════ -->
     * <sg-modal
     *   ref={modalRef}
     *   header="Delete Item"
     *   size="sm"
     *   onSgClose={(e) => handleClose(e.detail)}
     *   onSgCancel={() => handleCancel()}>
     *   <p>This action cannot be undone.</p>
     *   <div slot="footer">
     *     <sg-button onClick={() => modalRef.current.close()}>Cancel</sg-button>
     *     <sg-button variant="error" onClick={() => handleDelete()}>Delete</sg-button>
     *   </div>
     * </sg-modal>
     * @fires sgOpen - Emitted when the modal opens
     * @fires sgClose - Emitted when the modal closes, detail contains returnValue
     * @fires sgCancel - Emitted when user cancels (Escape or backdrop click)
     * @cssprop --sg-modal-width - Modal width (default: auto based on size)
     * @cssprop --sg-modal-max-width - Modal max width
     * @cssprop --sg-modal-max-height - Modal max height
     * @cssprop --sg-modal-padding - Modal content padding
     * @cssprop --sg-modal-radius - Modal border radius
     * @cssprop --sg-modal-backdrop-color - Backdrop overlay color
     * @cssprop --sg-modal-shadow - Modal box shadow
     */
    interface SgModal {
        /**
          * Whether the modal can be closed by clicking the backdrop
          * @default true
         */
        "closeOnBackdrop"?: boolean;
        /**
          * Whether the modal can be closed by pressing Escape
          * @default true
         */
        "closeOnEscape"?: boolean;
        /**
          * Modal header text
         */
        "header"?: string;
        /**
          * Whether the modal is a non-modal dialog (doesn't block interaction)
          * @default false
         */
        "nonModal"?: boolean;
        /**
          * Emitted when modal is cancelled (Escape or backdrop)
         */
        "onSgCancel"?: (event: SgModalCustomEvent<void>) => void;
        /**
          * Emitted when modal closes
         */
        "onSgClose"?: (event: SgModalCustomEvent<string>) => void;
        /**
          * Emitted when modal opens
         */
        "onSgOpen"?: (event: SgModalCustomEvent<void>) => void;
        /**
          * Whether the modal is open
          * @default false
         */
        "open"?: boolean;
        /**
          * Whether to show the backdrop overlay
          * @default true
         */
        "overlay"?: boolean;
        /**
          * Whether to show the close button in the header
          * @default true
         */
        "showCloseButton"?: boolean;
        /**
          * Modal size preset
          * @default 'md'
         */
        "size"?: ModalSize;
    }
    /**
     * @component sg-skeleton
     * @description Skeleton loading placeholder component for SageBox
     * @example <sg-skeleton variant="text" width="200px" height="1rem"></sg-skeleton>
     * <sg-skeleton variant="rect" width="100%" height="200px"></sg-skeleton>
     * <sg-skeleton variant="circle" width="48px" height="48px"></sg-skeleton>
     */
    interface SgSkeleton {
        /**
          * Animation type - shimmer: Gradient animation (default) - pulse: Opacity pulse animation - none: No animation
          * @default 'shimmer'
         */
        "animation"?: 'shimmer' | 'pulse' | 'none';
        /**
          * The height of the skeleton
          * @default '1rem'
         */
        "height"?: string;
        /**
          * The shape variant of the skeleton - text: Slightly rounded, good for text placeholders - rect: More rounded, good for cards/images - circle: Fully rounded, good for avatars
          * @default 'text'
         */
        "variant"?: 'text' | 'rect' | 'circle';
        /**
          * The width of the skeleton
          * @default '100%'
         */
        "width"?: string;
    }
    interface SgThemeToggle {
        /**
          * Emitted when the theme changes
         */
        "onSgThemeChange"?: (event: SgThemeToggleCustomEvent<ThemeMode>) => void;
        /**
          * Size of the toggle button
          * @default 'md'
         */
        "size"?: 'sm' | 'md' | 'lg';
        /**
          * The current theme mode
          * @default 'system'
         */
        "theme"?: ThemeMode;
    }
    interface IntrinsicElements {
        "sg-article-editor": SgArticleEditor;
        "sg-badge": SgBadge;
        "sg-button": SgButton;
        "sg-dropdown": SgDropdown;
        "sg-icon": SgIcon;
        "sg-modal": SgModal;
        "sg-skeleton": SgSkeleton;
        "sg-theme-toggle": SgThemeToggle;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * SageBox - Article Editor Component
             * A headless-ready article editor supporting HTML and Markdown modes
             * with live preview, formatting toolbar, and optional media library integration.
             * @example ```html
             * <sg-article-editor
             *   value="<p>Hello World</p>"
             *   mode="html"
             *   placeholder="Start writing..."
             * ></sg-article-editor>
             * ```
             */
            "sg-article-editor": LocalJSX.SgArticleEditor & JSXBase.HTMLAttributes<HTMLSgArticleEditorElement>;
            /**
             * @example ### Angular
             * ```html
             * <sg-badge variant="success">Active</sg-badge>
             * <sg-badge variant="error" size="sm" dot>Offline</sg-badge>
             * <sg-badge variant="info" pill>New Feature</sg-badge>
             * <sg-badge variant="warning">
             *   <sg-icon slot="icon" name="alert-triangle" size="12"></sg-icon>
             *   Warning
             * </sg-badge>
             * ```
             * ### React
             * ```jsx
             * <sg-badge variant="primary" outlined>Beta</sg-badge>
             * <sg-badge variant="success" pulse>Live</sg-badge>
             * ```
             * ### Vanilla JS
             * ```html
             * <sg-badge variant="info" size="lg">Featured</sg-badge>
             * <sg-badge variant="neutral" removable id="tag1">Tag 1</sg-badge>
             * <script>
             *   document.querySelector('#tag1').addEventListener('sgRemove', (e) => {
             *     e.target.remove();
             *   });
             * </script>
             * ```
             */
            "sg-badge": LocalJSX.SgBadge & JSXBase.HTMLAttributes<HTMLSgBadgeElement>;
            /**
             * @component sg-button
             * @description A versatile button component with multiple variants, sizes, and states.
             * Framework-agnostic: works with Angular, React, Vue, and vanilla JS without wrappers.
             * @example <!-- ═══════════════════════════════════════════════════════════════════════════════
             *      VANILLA HTML / JS
             *      ═══════════════════════════════════════════════════════════════════════════════ -->
             * <sg-button>Click me</sg-button>
             * <sg-button variant="primary">Primary</sg-button>
             * <sg-button variant="outline" size="lg">Large Outline</sg-button>
             * <sg-button variant="success" leading-icon="check">Save</sg-button>
             * <sg-button loading>Loading...</sg-button>
             * <sg-button disabled>Disabled</sg-button>
             * <sg-button shape="pill" variant="secondary">Pill Button</sg-button>
             * <script>
             *   document.querySelector('sg-button').addEventListener('sgClick', (e) => {
             *     console.log('Button clicked!', e.detail);
             *   });
             * </script>
             * <!-- ═══════════════════════════════════════════════════════════════════════════════
             *      ANGULAR (no wrapper needed, add CUSTOM_ELEMENTS_SCHEMA)
             *      ═══════════════════════════════════════════════════════════════════════════════ -->
             * <sg-button
             *   variant="primary"
             *   [attr.loading]="isLoading || null"
             *   [attr.disabled]="isDisabled || null"
             *   (sgClick)="handleClick($event)">
             *   Save Changes
             * </sg-button>
             * <!-- ═══════════════════════════════════════════════════════════════════════════════
             *      REACT (use kebab-case attributes)
             *      ═══════════════════════════════════════════════════════════════════════════════ -->
             * <sg-button
             *   variant="primary"
             *   leading-icon="save"
             *   loading={isLoading}
             *   onSgClick={(e) => handleClick(e.detail)}>
             *   Save Changes
             * </sg-button>
             * @fires sgClick - Emitted when button is clicked (not disabled/loading)
             * @cssprop --sg-btn-bg - Button background color
             * @cssprop --sg-btn-color - Button text color
             * @cssprop --sg-btn-border-color - Button border color
             * @cssprop --sg-btn-radius - Button border radius
             * @cssprop --sg-btn-shadow - Button box shadow
             */
            "sg-button": LocalJSX.SgButton & JSXBase.HTMLAttributes<HTMLSgButtonElement>;
            /**
             * @example ### Angular
             * ```html
             * <sg-dropdown align="start" position="bottom">
             *   <button slot="trigger">Open Menu</button>
             *   <div slot="header">Settings</div>
             *   <button>Option 1</button>
             *   <button>Option 2</button>
             *   <div slot="footer">Logged in as Admin</div>
             * </sg-dropdown>
             * ```
             * ### React
             * ```jsx
             * <sg-dropdown align="start" closeOnSelect={false}>
             *   <button slot="trigger">Menu</button>
             *   <div>Content here</div>
             * </sg-dropdown>
             * ```
             * ### Vanilla JS
             * ```html
             * <sg-dropdown id="myDropdown" align="end" close-on-select="false">
             *   <button slot="trigger">Options</button>
             *   <ul>
             *     <li>Item 1</li>
             *     <li>Item 2</li>
             *   </ul>
             * </sg-dropdown>
             * <script>
             *   const dropdown = document.querySelector('#myDropdown');
             *   dropdown.addEventListener('sgOpen', (e) => console.log('Opened'));
             *   dropdown.addEventListener('sgClose', (e) => console.log('Closed'));
             * </script>
             * ```
             */
            "sg-dropdown": LocalJSX.SgDropdown & JSXBase.HTMLAttributes<HTMLSgDropdownElement>;
            /**
             * @component sg-icon
             * @description SVG Icon component for SageBox - A flexible, accessible icon system
             * @example <!-- Basic usage with built-in icons -->
             * <sg-icon name="home"></sg-icon>
             * <sg-icon name="icon-home"></sg-icon>
             * <!-- With custom size -->
             * <sg-icon name="settings" size="32"></sg-icon>
             * <!-- With custom color (fill is an alias for color) -->
             * <sg-icon name="heart" color="#ff0000"></sg-icon>
             * <sg-icon name="heart" fill="#ff0000"></sg-icon>
             * <!-- Custom icon via src (fetches SVG file) -->
             * <sg-icon src="/assets/custom-icon.svg"></sg-icon>
             * <!-- Load icons from JSON file -->
             * <sg-icon name="my-icon" json-src="/assets/icons.json"></sg-icon>
             */
            "sg-icon": LocalJSX.SgIcon & JSXBase.HTMLAttributes<HTMLSgIconElement>;
            /**
             * @component sg-modal
             * @description A modern modal dialog component built on the native HTML <dialog> element.
             * Provides built-in accessibility, focus trapping, and backdrop handling.
             * @example <!-- ═══════════════════════════════════════════════════════════════════════════════
             *      VANILLA HTML / JS
             *      ═══════════════════════════════════════════════════════════════════════════════ -->
             * <sg-modal id="myModal" header="Confirm Action">
             *   <p>Are you sure you want to continue?</p>
             *   <div slot="footer">
             *     <sg-button variant="secondary" onclick="document.getElementById('myModal').close()">Cancel</sg-button>
             *     <sg-button variant="primary">Confirm</sg-button>
             *   </div>
             * </sg-modal>
             * <sg-button onclick="document.getElementById('myModal').showModal()">Open Modal</sg-button>
             * <script>
             *   document.getElementById('myModal').addEventListener('sgClose', (e) => {
             *     console.log('Modal closed with:', e.detail);
             *   });
             * </script>
             * <!-- ═══════════════════════════════════════════════════════════════════════════════
             *      ANGULAR
             *      ═══════════════════════════════════════════════════════════════════════════════ -->
             * <sg-modal
             *   #modal
             *   header="Edit Profile"
             *   [attr.open]="isOpen || null"
             *   (sgClose)="onClose($event)"
             *   (sgCancel)="onCancel()">
             *   <form>...</form>
             *   <div slot="footer">
             *     <sg-button (sgClick)="modal.close()">Cancel</sg-button>
             *     <sg-button variant="primary" (sgClick)="save()">Save</sg-button>
             *   </div>
             * </sg-modal>
             * <!-- ═══════════════════════════════════════════════════════════════════════════════
             *      REACT
             *      ═══════════════════════════════════════════════════════════════════════════════ -->
             * <sg-modal
             *   ref={modalRef}
             *   header="Delete Item"
             *   size="sm"
             *   onSgClose={(e) => handleClose(e.detail)}
             *   onSgCancel={() => handleCancel()}>
             *   <p>This action cannot be undone.</p>
             *   <div slot="footer">
             *     <sg-button onClick={() => modalRef.current.close()}>Cancel</sg-button>
             *     <sg-button variant="error" onClick={() => handleDelete()}>Delete</sg-button>
             *   </div>
             * </sg-modal>
             * @fires sgOpen - Emitted when the modal opens
             * @fires sgClose - Emitted when the modal closes, detail contains returnValue
             * @fires sgCancel - Emitted when user cancels (Escape or backdrop click)
             * @cssprop --sg-modal-width - Modal width (default: auto based on size)
             * @cssprop --sg-modal-max-width - Modal max width
             * @cssprop --sg-modal-max-height - Modal max height
             * @cssprop --sg-modal-padding - Modal content padding
             * @cssprop --sg-modal-radius - Modal border radius
             * @cssprop --sg-modal-backdrop-color - Backdrop overlay color
             * @cssprop --sg-modal-shadow - Modal box shadow
             */
            "sg-modal": LocalJSX.SgModal & JSXBase.HTMLAttributes<HTMLSgModalElement>;
            /**
             * @component sg-skeleton
             * @description Skeleton loading placeholder component for SageBox
             * @example <sg-skeleton variant="text" width="200px" height="1rem"></sg-skeleton>
             * <sg-skeleton variant="rect" width="100%" height="200px"></sg-skeleton>
             * <sg-skeleton variant="circle" width="48px" height="48px"></sg-skeleton>
             */
            "sg-skeleton": LocalJSX.SgSkeleton & JSXBase.HTMLAttributes<HTMLSgSkeletonElement>;
            "sg-theme-toggle": LocalJSX.SgThemeToggle & JSXBase.HTMLAttributes<HTMLSgThemeToggleElement>;
        }
    }
}
