/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import { ContentType, ContentTypeChangeEvent, EditorChangeEvent, MediaItem, ViewMode, ViewModeChangeEvent } from './utils';
import { EditorTranslations, SupportedLocale } from './utils/i18n';
export { ContentType, ContentTypeChangeEvent, EditorChangeEvent, MediaItem, ViewMode, ViewModeChangeEvent } from './utils';
export { EditorTranslations, SupportedLocale } from './utils/i18n';
export namespace Components {
  /**
   * SageBox - Article Editor Component
   * A headless-ready article editor supporting HTML and Markdown modes
   * with live preview, formatting toolbar, and optional media library integration.
   * @example ```html
   * <sg-article-editor
   *   value="<p>Hello World</p>"
   *   mode="html"
   *   placeholder="Start writing..."
   * ></sg-article-editor>
   * ```
   */
  interface SgArticleEditor {
    /**
     * Available content types (comma-separated or array)
     * @default 'html,markdown'
     */
    availableContentTypes: string;
    /**
     * @deprecated Use availableContentTypes instead
     * @default 'html,markdown'
     */
    availableModes: string;
    /**
     * Available view modes (comma-separated or array)
     * @default 'editor,preview,split'
     */
    availableViewModes: string;
    /**
     * Content syntax type (html or markdown)
     * @default 'html'
     */
    contentType: ContentType;
    /**
     * Custom translations to override defaults
     */
    customTranslations: Partial<EditorTranslations>;
    /**
     * Disabled state
     * @default false
     */
    disabled: boolean;
    /**
     * Custom accent color (buttons, links)
     */
    editorAccent: string;
    /**
     * Custom background color for the editor
     */
    editorBg: string;
    /**
     * Custom secondary background color
     */
    editorBgSecondary: string;
    /**
     * Custom tertiary background color
     */
    editorBgTertiary: string;
    /**
     * Custom border color
     */
    editorBorder: string;
    /**
     * Custom border radius
     */
    editorBorderRadius: string;
    /**
     * Custom font family for code
     */
    editorFontMono: string;
    /**
     * Custom font family for text
     */
    editorFontSans: string;
    /**
     * Custom font size
     */
    editorFontSize: string;
    /**
     * Custom text color
     */
    editorText: string;
    /**
     * Custom secondary text color
     */
    editorTextSecondary: string;
    /**
     * Enable external preview window
     * @default true
     */
    enableExternalPreview: boolean;
    /**
     * Focus the editor
     */
    focusEditor: () => Promise<void>;
    /**
     * Get the current content
     */
    getContent: () => Promise<string>;
    /**
     * Get content as HTML (converts if in markdown mode)
     */
    getHtml: () => Promise<string>;
    /**
     * Insert content at cursor position
     */
    insertAtCursor: (content: string) => Promise<void>;
    /**
     * Insert a media item
     */
    insertMedia: (media: MediaItem) => Promise<void>;
    /**
     * Locale for UI text (en, es, fr, de, pt, it, zh, ja, ko, ar)
     * @default 'en'
     */
    locale: SupportedLocale;
    /**
     * Minimum height in pixels
     * @default 400
     */
    minHeight: number;
    /**
     * @deprecated Use contentType instead
     * @default 'html'
     */
    mode: ContentType;
    /**
     * Placeholder text when editor is empty
     * @default 'Start writing...'
     */
    placeholder: string;
    /**
     * Read-only state
     * @default false
     */
    readonly: boolean;
    /**
     * Set the content programmatically
     */
    setContent: (content: string) => Promise<void>;
    /**
     * Show word/character count
     * @default true
     */
    showWordCount: boolean;
    /**
     * Enable spell checking
     * @default true
     */
    spellcheck: boolean;
    /**
     * The content value of the editor
     * @default ''
     */
    value: string;
    /**
     * View mode (editor, preview, or split)
     * @default 'editor'
     */
    viewMode: ViewMode;
  }
}
export interface SgArticleEditorCustomEvent<T> extends CustomEvent<T> {
  detail: T;
  target: HTMLSgArticleEditorElement;
}
declare global {
  interface HTMLSgArticleEditorElementEventMap {
    editorChange: EditorChangeEvent;
    contentTypeChange: ContentTypeChangeEvent;
    viewModeChange: ViewModeChangeEvent;
    editorModeChange: ContentTypeChangeEvent;
    mediaLibraryOpen: void;
    mediaInsert: MediaItem;
  }
  /**
   * SageBox - Article Editor Component
   * A headless-ready article editor supporting HTML and Markdown modes
   * with live preview, formatting toolbar, and optional media library integration.
   * @example ```html
   * <sg-article-editor
   *   value="<p>Hello World</p>"
   *   mode="html"
   *   placeholder="Start writing..."
   * ></sg-article-editor>
   * ```
   */
  interface HTMLSgArticleEditorElement extends Components.SgArticleEditor, HTMLStencilElement {
    addEventListener<K extends keyof HTMLSgArticleEditorElementEventMap>(
      type: K,
      listener: (this: HTMLSgArticleEditorElement, ev: SgArticleEditorCustomEvent<HTMLSgArticleEditorElementEventMap[K]>) => any,
      options?: boolean | AddEventListenerOptions
    ): void;
    addEventListener<K extends keyof DocumentEventMap>(
      type: K,
      listener: (this: Document, ev: DocumentEventMap[K]) => any,
      options?: boolean | AddEventListenerOptions
    ): void;
    addEventListener<K extends keyof HTMLElementEventMap>(
      type: K,
      listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any,
      options?: boolean | AddEventListenerOptions
    ): void;
    addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
    removeEventListener<K extends keyof HTMLSgArticleEditorElementEventMap>(
      type: K,
      listener: (this: HTMLSgArticleEditorElement, ev: SgArticleEditorCustomEvent<HTMLSgArticleEditorElementEventMap[K]>) => any,
      options?: boolean | EventListenerOptions
    ): void;
    removeEventListener<K extends keyof DocumentEventMap>(
      type: K,
      listener: (this: Document, ev: DocumentEventMap[K]) => any,
      options?: boolean | EventListenerOptions
    ): void;
    removeEventListener<K extends keyof HTMLElementEventMap>(
      type: K,
      listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any,
      options?: boolean | EventListenerOptions
    ): void;
    removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
  }
  var HTMLSgArticleEditorElement: {
    prototype: HTMLSgArticleEditorElement;
    new (): HTMLSgArticleEditorElement;
  };
  interface HTMLElementTagNameMap {
    'sg-article-editor': HTMLSgArticleEditorElement;
  }
}
declare namespace LocalJSX {
  /**
   * SageBox - Article Editor Component
   * A headless-ready article editor supporting HTML and Markdown modes
   * with live preview, formatting toolbar, and optional media library integration.
   * @example ```html
   * <sg-article-editor
   *   value="<p>Hello World</p>"
   *   mode="html"
   *   placeholder="Start writing..."
   * ></sg-article-editor>
   * ```
   */
  interface SgArticleEditor {
    /**
     * Available content types (comma-separated or array)
     * @default 'html,markdown'
     */
    availableContentTypes?: string;
    /**
     * @deprecated Use availableContentTypes instead
     * @default 'html,markdown'
     */
    availableModes?: string;
    /**
     * Available view modes (comma-separated or array)
     * @default 'editor,preview,split'
     */
    availableViewModes?: string;
    /**
     * Content syntax type (html or markdown)
     * @default 'html'
     */
    contentType?: ContentType;
    /**
     * Custom translations to override defaults
     */
    customTranslations?: Partial<EditorTranslations>;
    /**
     * Disabled state
     * @default false
     */
    disabled?: boolean;
    /**
     * Custom accent color (buttons, links)
     */
    editorAccent?: string;
    /**
     * Custom background color for the editor
     */
    editorBg?: string;
    /**
     * Custom secondary background color
     */
    editorBgSecondary?: string;
    /**
     * Custom tertiary background color
     */
    editorBgTertiary?: string;
    /**
     * Custom border color
     */
    editorBorder?: string;
    /**
     * Custom border radius
     */
    editorBorderRadius?: string;
    /**
     * Custom font family for code
     */
    editorFontMono?: string;
    /**
     * Custom font family for text
     */
    editorFontSans?: string;
    /**
     * Custom font size
     */
    editorFontSize?: string;
    /**
     * Custom text color
     */
    editorText?: string;
    /**
     * Custom secondary text color
     */
    editorTextSecondary?: string;
    /**
     * Enable external preview window
     * @default true
     */
    enableExternalPreview?: boolean;
    /**
     * Locale for UI text (en, es, fr, de, pt, it, zh, ja, ko, ar)
     * @default 'en'
     */
    locale?: SupportedLocale;
    /**
     * Minimum height in pixels
     * @default 400
     */
    minHeight?: number;
    /**
     * @deprecated Use contentType instead
     * @default 'html'
     */
    mode?: ContentType;
    /**
     * Emitted when the content type changes
     */
    onContentTypeChange?: (event: SgArticleEditorCustomEvent<ContentTypeChangeEvent>) => void;
    /**
     * Emitted when the content changes
     */
    onEditorChange?: (event: SgArticleEditorCustomEvent<EditorChangeEvent>) => void;
    /**
     * @deprecated Use contentTypeChange instead
     */
    onEditorModeChange?: (event: SgArticleEditorCustomEvent<ContentTypeChangeEvent>) => void;
    /**
     * Emitted when a media item should be inserted
     */
    onMediaInsert?: (event: SgArticleEditorCustomEvent<MediaItem>) => void;
    /**
     * Emitted when media library is requested
     */
    onMediaLibraryOpen?: (event: SgArticleEditorCustomEvent<void>) => void;
    /**
     * Emitted when the view mode changes
     */
    onViewModeChange?: (event: SgArticleEditorCustomEvent<ViewModeChangeEvent>) => void;
    /**
     * Placeholder text when editor is empty
     * @default 'Start writing...'
     */
    placeholder?: string;
    /**
     * Read-only state
     * @default false
     */
    readonly?: boolean;
    /**
     * Show word/character count
     * @default true
     */
    showWordCount?: boolean;
    /**
     * Enable spell checking
     * @default true
     */
    spellcheck?: boolean;
    /**
     * The content value of the editor
     * @default ''
     */
    value?: string;
    /**
     * View mode (editor, preview, or split)
     * @default 'editor'
     */
    viewMode?: ViewMode;
  }
  interface IntrinsicElements {
    'sg-article-editor': SgArticleEditor;
  }
}
export { LocalJSX as JSX };
declare module '@stencil/core' {
  export namespace JSX {
    interface IntrinsicElements {
      /**
       * SageBox - Article Editor Component
       * A headless-ready article editor supporting HTML and Markdown modes
       * with live preview, formatting toolbar, and optional media library integration.
       * @example ```html
       * <sg-article-editor
       *   value="<p>Hello World</p>"
       *   mode="html"
       *   placeholder="Start writing..."
       * ></sg-article-editor>
       * ```
       */
      'sg-article-editor': LocalJSX.SgArticleEditor & JSXBase.HTMLAttributes<HTMLSgArticleEditorElement>;
    }
  }
}
