/**
 * SageBox Angular Wrappers
 * 
 * Auto-generated by @stencil/angular-output-target
 */

// Re-export components and DIRECTIVES array
export {
  SgArticleEditor,
  SgBadge,
  SgButton,
  SgDropdown,
  SgIcon,
  SgSkeleton,
  SgThemeToggle,
} from './directives/proxies';

export { DIRECTIVES } from './directives/index';