/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { CardSize, CardVariant } from "./components/card/card";
export { CardSize, CardVariant } from "./components/card/card";
export namespace Components {
    /**
     * @component sg-card
     * @description A flexible card component with multiple variants, optional header/footer, icons and actions.
     * Framework-agnostic: works with Angular, React, Vue, and vanilla JS.
     * @example ### Basic Usage
     * ```html
     * <sg-card title="Card Title" subtitle="Card subtitle">
     *   <p>Card content goes here</p>
     * </sg-card>
     * ```
     * ### With Icon and Action
     * ```html
     * <sg-card
     *   title="Users"
     *   subtitle="Manage your team"
     *   icon="users"
     *   variant="primary"
     *   action-label="View All"
     *   clickable>
     *   <p>You have 24 active users</p>
     * </sg-card>
     * ```
     * ### With Custom Slots
     * ```html
     * <sg-card variant="gradient">
     *   <img slot="media" src="image.jpg" alt="Cover" />
     *   <div slot="header">
     *     <h3>Custom Header</h3>
     *   </div>
     *   <p>Content here</p>
     *   <div slot="footer">
     *     <sg-button variant="primary">Action</sg-button>
     *   </div>
     * </sg-card>
     * ```
     */
    interface SgCard {
        /**
          * Label for the action button in footer
         */
        "actionLabel": string;
        /**
          * Variant for the action button
          * @default 'primary'
         */
        "actionVariant": 'primary' | 'secondary' | 'ghost';
        /**
          * Card title displayed in the header
         */
        "cardTitle": string;
        /**
          * Makes the entire card clickable
          * @default false
         */
        "clickable": boolean;
        /**
          * Disables the card (reduces opacity, no interactions)
          * @default false
         */
        "disabled": boolean;
        /**
          * Removes shadow from the card
          * @default false
         */
        "flat": boolean;
        /**
          * Optional header text (displays above title with accent background)
         */
        "header": string;
        /**
          * Adds hover elevation effect
          * @default false
         */
        "hoverable": boolean;
        /**
          * URL for navigation (makes card a link)
         */
        "href": string;
        /**
          * Icon name to display (uses sg-icon internally)
         */
        "icon": string;
        /**
          * Icon color (CSS color value)
         */
        "iconColor": string;
        /**
          * Icon size in pixels
          * @default 48
         */
        "iconSize": number | string;
        /**
          * Applies loading state with skeleton effect
          * @default false
         */
        "loading": boolean;
        /**
          * Size preset for padding and typography
          * @default 'md'
         */
        "size": CardSize;
        /**
          * Card subtitle displayed below the title
         */
        "subtitle": string;
        /**
          * Target for href link
          * @default '_self'
         */
        "target": string;
        /**
          * Visual variant of the card
          * @default 'default'
         */
        "variant": CardVariant;
    }
}
export interface SgCardCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSgCardElement;
}
declare global {
    interface HTMLSgCardElementEventMap {
        "sgClick": void;
        "sgAction": void;
    }
    /**
     * @component sg-card
     * @description A flexible card component with multiple variants, optional header/footer, icons and actions.
     * Framework-agnostic: works with Angular, React, Vue, and vanilla JS.
     * @example ### Basic Usage
     * ```html
     * <sg-card title="Card Title" subtitle="Card subtitle">
     *   <p>Card content goes here</p>
     * </sg-card>
     * ```
     * ### With Icon and Action
     * ```html
     * <sg-card
     *   title="Users"
     *   subtitle="Manage your team"
     *   icon="users"
     *   variant="primary"
     *   action-label="View All"
     *   clickable>
     *   <p>You have 24 active users</p>
     * </sg-card>
     * ```
     * ### With Custom Slots
     * ```html
     * <sg-card variant="gradient">
     *   <img slot="media" src="image.jpg" alt="Cover" />
     *   <div slot="header">
     *     <h3>Custom Header</h3>
     *   </div>
     *   <p>Content here</p>
     *   <div slot="footer">
     *     <sg-button variant="primary">Action</sg-button>
     *   </div>
     * </sg-card>
     * ```
     */
    interface HTMLSgCardElement extends Components.SgCard, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSgCardElementEventMap>(type: K, listener: (this: HTMLSgCardElement, ev: SgCardCustomEvent<HTMLSgCardElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSgCardElementEventMap>(type: K, listener: (this: HTMLSgCardElement, ev: SgCardCustomEvent<HTMLSgCardElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSgCardElement: {
        prototype: HTMLSgCardElement;
        new (): HTMLSgCardElement;
    };
    interface HTMLElementTagNameMap {
        "sg-card": HTMLSgCardElement;
    }
}
declare namespace LocalJSX {
    /**
     * @component sg-card
     * @description A flexible card component with multiple variants, optional header/footer, icons and actions.
     * Framework-agnostic: works with Angular, React, Vue, and vanilla JS.
     * @example ### Basic Usage
     * ```html
     * <sg-card title="Card Title" subtitle="Card subtitle">
     *   <p>Card content goes here</p>
     * </sg-card>
     * ```
     * ### With Icon and Action
     * ```html
     * <sg-card
     *   title="Users"
     *   subtitle="Manage your team"
     *   icon="users"
     *   variant="primary"
     *   action-label="View All"
     *   clickable>
     *   <p>You have 24 active users</p>
     * </sg-card>
     * ```
     * ### With Custom Slots
     * ```html
     * <sg-card variant="gradient">
     *   <img slot="media" src="image.jpg" alt="Cover" />
     *   <div slot="header">
     *     <h3>Custom Header</h3>
     *   </div>
     *   <p>Content here</p>
     *   <div slot="footer">
     *     <sg-button variant="primary">Action</sg-button>
     *   </div>
     * </sg-card>
     * ```
     */
    interface SgCard {
        /**
          * Label for the action button in footer
         */
        "actionLabel"?: string;
        /**
          * Variant for the action button
          * @default 'primary'
         */
        "actionVariant"?: 'primary' | 'secondary' | 'ghost';
        /**
          * Card title displayed in the header
         */
        "cardTitle"?: string;
        /**
          * Makes the entire card clickable
          * @default false
         */
        "clickable"?: boolean;
        /**
          * Disables the card (reduces opacity, no interactions)
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Removes shadow from the card
          * @default false
         */
        "flat"?: boolean;
        /**
          * Optional header text (displays above title with accent background)
         */
        "header"?: string;
        /**
          * Adds hover elevation effect
          * @default false
         */
        "hoverable"?: boolean;
        /**
          * URL for navigation (makes card a link)
         */
        "href"?: string;
        /**
          * Icon name to display (uses sg-icon internally)
         */
        "icon"?: string;
        /**
          * Icon color (CSS color value)
         */
        "iconColor"?: string;
        /**
          * Icon size in pixels
          * @default 48
         */
        "iconSize"?: number | string;
        /**
          * Applies loading state with skeleton effect
          * @default false
         */
        "loading"?: boolean;
        /**
          * Emitted when the action button is clicked
         */
        "onSgAction"?: (event: SgCardCustomEvent<void>) => void;
        /**
          * Emitted when the card is clicked (if clickable)
         */
        "onSgClick"?: (event: SgCardCustomEvent<void>) => void;
        /**
          * Size preset for padding and typography
          * @default 'md'
         */
        "size"?: CardSize;
        /**
          * Card subtitle displayed below the title
         */
        "subtitle"?: string;
        /**
          * Target for href link
          * @default '_self'
         */
        "target"?: string;
        /**
          * Visual variant of the card
          * @default 'default'
         */
        "variant"?: CardVariant;
    }
    interface IntrinsicElements {
        "sg-card": SgCard;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * @component sg-card
             * @description A flexible card component with multiple variants, optional header/footer, icons and actions.
             * Framework-agnostic: works with Angular, React, Vue, and vanilla JS.
             * @example ### Basic Usage
             * ```html
             * <sg-card title="Card Title" subtitle="Card subtitle">
             *   <p>Card content goes here</p>
             * </sg-card>
             * ```
             * ### With Icon and Action
             * ```html
             * <sg-card
             *   title="Users"
             *   subtitle="Manage your team"
             *   icon="users"
             *   variant="primary"
             *   action-label="View All"
             *   clickable>
             *   <p>You have 24 active users</p>
             * </sg-card>
             * ```
             * ### With Custom Slots
             * ```html
             * <sg-card variant="gradient">
             *   <img slot="media" src="image.jpg" alt="Cover" />
             *   <div slot="header">
             *     <h3>Custom Header</h3>
             *   </div>
             *   <p>Content here</p>
             *   <div slot="footer">
             *     <sg-button variant="primary">Action</sg-button>
             *   </div>
             * </sg-card>
             * ```
             */
            "sg-card": LocalJSX.SgCard & JSXBase.HTMLAttributes<HTMLSgCardElement>;
        }
    }
}
