'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import { type ContentTypeChangeEvent, type EditorChangeEvent, type MediaItem, type SgArticleEditorCustomEvent, type SgButtonCustomEvent, type SgThemeToggleCustomEvent, type ThemeMode, type ViewModeChangeEvent } from "sagebox";
import { SgArticleEditor as SgArticleEditorElement, defineCustomElement as defineSgArticleEditor } from "sagebox/dist/components/sg-article-editor.js";
import { SgBadge as SgBadgeElement, defineCustomElement as defineSgBadge } from "sagebox/dist/components/sg-badge.js";
import { SgButton as SgButtonElement, defineCustomElement as defineSgButton } from "sagebox/dist/components/sg-button.js";
import { SgDropdown as SgDropdownElement, defineCustomElement as defineSgDropdown } from "sagebox/dist/components/sg-dropdown.js";
import { SgIcon as SgIconElement, defineCustomElement as defineSgIcon } from "sagebox/dist/components/sg-icon.js";
import { SgSkeleton as SgSkeletonElement, defineCustomElement as defineSgSkeleton } from "sagebox/dist/components/sg-skeleton.js";
import { SgThemeToggle as SgThemeToggleElement, defineCustomElement as defineSgThemeToggle } from "sagebox/dist/components/sg-theme-toggle.js";

export type SgArticleEditorEvents = {
    onEditorChange: EventName<SgArticleEditorCustomEvent<EditorChangeEvent>>,
    onContentTypeChange: EventName<SgArticleEditorCustomEvent<ContentTypeChangeEvent>>,
    onViewModeChange: EventName<SgArticleEditorCustomEvent<ViewModeChangeEvent>>,
    onEditorModeChange: EventName<SgArticleEditorCustomEvent<ContentTypeChangeEvent>>,
    onMediaLibraryOpen: EventName<CustomEvent<void>>,
    onMediaInsert: EventName<SgArticleEditorCustomEvent<MediaItem>>
};

export const SgArticleEditor: StencilReactComponent<SgArticleEditorElement, SgArticleEditorEvents> = /*@__PURE__*/ createComponent<SgArticleEditorElement, SgArticleEditorEvents>({
    tagName: 'sg-article-editor',
    elementClass: SgArticleEditorElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onEditorChange: 'editorChange',
        onContentTypeChange: 'contentTypeChange',
        onViewModeChange: 'viewModeChange',
        onEditorModeChange: 'editorModeChange',
        onMediaLibraryOpen: 'mediaLibraryOpen',
        onMediaInsert: 'mediaInsert'
    } as SgArticleEditorEvents,
    defineCustomElement: defineSgArticleEditor
});

export type SgBadgeEvents = NonNullable<unknown>;

export const SgBadge: StencilReactComponent<SgBadgeElement, SgBadgeEvents> = /*@__PURE__*/ createComponent<SgBadgeElement, SgBadgeEvents>({
    tagName: 'sg-badge',
    elementClass: SgBadgeElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SgBadgeEvents,
    defineCustomElement: defineSgBadge
});

export type SgButtonEvents = { onSgClick: EventName<SgButtonCustomEvent<MouseEvent>> };

export const SgButton: StencilReactComponent<SgButtonElement, SgButtonEvents> = /*@__PURE__*/ createComponent<SgButtonElement, SgButtonEvents>({
    tagName: 'sg-button',
    elementClass: SgButtonElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onSgClick: 'sgClick' } as SgButtonEvents,
    defineCustomElement: defineSgButton
});

export type SgDropdownEvents = {
    onSgOpen: EventName<CustomEvent<void>>,
    onSgClose: EventName<CustomEvent<void>>,
    onSgToggle: EventName<CustomEvent<boolean>>
};

export const SgDropdown: StencilReactComponent<SgDropdownElement, SgDropdownEvents> = /*@__PURE__*/ createComponent<SgDropdownElement, SgDropdownEvents>({
    tagName: 'sg-dropdown',
    elementClass: SgDropdownElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onSgOpen: 'sgOpen',
        onSgClose: 'sgClose',
        onSgToggle: 'sgToggle'
    } as SgDropdownEvents,
    defineCustomElement: defineSgDropdown
});

export type SgIconEvents = NonNullable<unknown>;

export const SgIcon: StencilReactComponent<SgIconElement, SgIconEvents> = /*@__PURE__*/ createComponent<SgIconElement, SgIconEvents>({
    tagName: 'sg-icon',
    elementClass: SgIconElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SgIconEvents,
    defineCustomElement: defineSgIcon
});

export type SgSkeletonEvents = NonNullable<unknown>;

export const SgSkeleton: StencilReactComponent<SgSkeletonElement, SgSkeletonEvents> = /*@__PURE__*/ createComponent<SgSkeletonElement, SgSkeletonEvents>({
    tagName: 'sg-skeleton',
    elementClass: SgSkeletonElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SgSkeletonEvents,
    defineCustomElement: defineSgSkeleton
});

export type SgThemeToggleEvents = { onSgThemeChange: EventName<SgThemeToggleCustomEvent<ThemeMode>> };

export const SgThemeToggle: StencilReactComponent<SgThemeToggleElement, SgThemeToggleEvents> = /*@__PURE__*/ createComponent<SgThemeToggleElement, SgThemeToggleEvents>({
    tagName: 'sg-theme-toggle',
    elementClass: SgThemeToggleElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onSgThemeChange: 'sgThemeChange' } as SgThemeToggleEvents,
    defineCustomElement: defineSgThemeToggle
});
