/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { InputSize, InputType, InputVariant, ValidationState } from "./components/input/input";
export { InputSize, InputType, InputVariant, ValidationState } from "./components/input/input";
export namespace Components {
    /**
     * @component sg-input
     * @description A versatile input component with validation, icons, and multiple variants.
     * Supports all standard HTML input types with enhanced styling and accessibility.
     * @example <!-- ═══════════════════════════════════════════════════════════════════════════════
     *      VANILLA HTML / JS
     *      ═══════════════════════════════════════════════════════════════════════════════ -->
     * <sg-input placeholder="Enter your name"></sg-input>
     * <sg-input type="email" label="Email" required></sg-input>
     * <sg-input type="password" label="Password" leading-icon="lock"></sg-input>
     * <sg-input label="Username" helper-text="Choose a unique username"></sg-input>
     * <sg-input label="Email" validation-state="error" error-message="Invalid email format"></sg-input>
     * <script>
     *   document.querySelector('sg-input').addEventListener('sgInput', (e) => {
     *     console.log('Value changed:', e.detail.value);
     *   });
     * </script>
     * <!-- ═══════════════════════════════════════════════════════════════════════════════
     *      ANGULAR
     *      ═══════════════════════════════════════════════════════════════════════════════ -->
     * <sg-input
     *   label="Email"
     *   type="email"
     *   [attr.value]="email"
     *   [attr.validation-state]="emailError ? 'error' : 'default'"
     *   [attr.error-message]="emailError"
     *   (sgInput)="onEmailChange($event)">
     * </sg-input>
     * <!-- ═══════════════════════════════════════════════════════════════════════════════
     *      REACT
     *      ═══════════════════════════════════════════════════════════════════════════════ -->
     * <sg-input
     *   label="Search"
     *   type="search"
     *   leading-icon="search"
     *   clearable
     *   onSgInput={(e) => setSearch(e.detail.value)}
     * />
     * @fires sgInput - Emitted when the input value changes
     * @fires sgChange - Emitted when the input loses focus after value change
     * @fires sgFocus - Emitted when the input gains focus
     * @fires sgBlur - Emitted when the input loses focus
     * @fires sgClear - Emitted when the clear button is clicked
     * @cssprop --sg-input-bg - Input background color
     * @cssprop --sg-input-color - Input text color
     * @cssprop --sg-input-border-color - Input border color
     * @cssprop --sg-input-border-radius - Input border radius
     * @cssprop --sg-input-focus-ring - Focus ring color
     */
    interface SgInput {
        /**
          * Autocomplete attribute
          * @attr autocomplete
         */
        "autocomplete"?: string;
        /**
          * Autofocus attribute
          * @attr autofocus
          * @default false
         */
        "autofocus": boolean;
        /**
          * Clears the input value
         */
        "clear": () => Promise<void>;
        /**
          * Show clear button when input has value
          * @attr clearable
          * @default false
         */
        "clearable": boolean;
        /**
          * Whether the input is disabled
          * @attr disabled
          * @default false
         */
        "disabled": boolean;
        /**
          * Error message (displayed when validation-state is 'error')
          * @attr error-message
         */
        "errorMessage"?: string;
        /**
          * Returns the native input element
         */
        "getInputElement": () => Promise<HTMLInputElement | undefined>;
        /**
          * Helper text displayed below the input
          * @attr helper-text
         */
        "helperText"?: string;
        /**
          * Label text displayed above the input
          * @attr label
         */
        "label"?: string;
        /**
          * Leading icon name (from sg-icon)
          * @attr leading-icon
         */
        "leadingIcon"?: string;
        /**
          * Maximum value for number/date inputs
          * @attr max
         */
        "max"?: string | number;
        /**
          * Maximum length for text inputs
          * @attr maxlength
         */
        "maxlength"?: number;
        /**
          * Minimum value for number/date inputs
          * @attr min
         */
        "min"?: string | number;
        /**
          * Minimum length for text inputs
          * @attr minlength
         */
        "minlength"?: number;
        /**
          * Input name attribute
          * @attr name
         */
        "name"?: string;
        /**
          * Pattern for validation (regex)
          * @attr pattern
         */
        "pattern"?: string;
        /**
          * Placeholder text
          * @attr placeholder
         */
        "placeholder"?: string;
        /**
          * Whether the input is readonly
          * @attr readonly
          * @default false
         */
        "readonly": boolean;
        /**
          * Whether the input is required
          * @attr required
          * @default false
         */
        "required": boolean;
        /**
          * Selects all text in the input
         */
        "select": () => Promise<void>;
        /**
          * Removes focus from the input
         */
        "setBlur": () => Promise<void>;
        /**
          * Sets focus on the input
         */
        "setFocus": () => Promise<void>;
        /**
          * Input size variant
          * @attr size
          * @default 'md'
         */
        "size": InputSize;
        /**
          * Step value for number inputs
          * @attr step
         */
        "step"?: string | number;
        /**
          * Trailing icon name (from sg-icon)
          * @attr trailing-icon
         */
        "trailingIcon"?: string;
        /**
          * Input type
          * @attr type
          * @default 'text'
         */
        "type": InputType;
        /**
          * Validation state
          * @attr validation-state
          * @default 'default'
         */
        "validationState": ValidationState;
        /**
          * Input value
          * @attr value
          * @default ''
         */
        "value": string;
        /**
          * Visual variant
          * @attr variant
          * @default 'default'
         */
        "variant": InputVariant;
    }
}
export interface SgInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSgInputElement;
}
declare global {
    interface HTMLSgInputElementEventMap {
        "sgInput": { value: string; event: InputEvent };
        "sgChange": { value: string };
        "sgFocus": void;
        "sgBlur": void;
        "sgClear": void;
    }
    /**
     * @component sg-input
     * @description A versatile input component with validation, icons, and multiple variants.
     * Supports all standard HTML input types with enhanced styling and accessibility.
     * @example <!-- ═══════════════════════════════════════════════════════════════════════════════
     *      VANILLA HTML / JS
     *      ═══════════════════════════════════════════════════════════════════════════════ -->
     * <sg-input placeholder="Enter your name"></sg-input>
     * <sg-input type="email" label="Email" required></sg-input>
     * <sg-input type="password" label="Password" leading-icon="lock"></sg-input>
     * <sg-input label="Username" helper-text="Choose a unique username"></sg-input>
     * <sg-input label="Email" validation-state="error" error-message="Invalid email format"></sg-input>
     * <script>
     *   document.querySelector('sg-input').addEventListener('sgInput', (e) => {
     *     console.log('Value changed:', e.detail.value);
     *   });
     * </script>
     * <!-- ═══════════════════════════════════════════════════════════════════════════════
     *      ANGULAR
     *      ═══════════════════════════════════════════════════════════════════════════════ -->
     * <sg-input
     *   label="Email"
     *   type="email"
     *   [attr.value]="email"
     *   [attr.validation-state]="emailError ? 'error' : 'default'"
     *   [attr.error-message]="emailError"
     *   (sgInput)="onEmailChange($event)">
     * </sg-input>
     * <!-- ═══════════════════════════════════════════════════════════════════════════════
     *      REACT
     *      ═══════════════════════════════════════════════════════════════════════════════ -->
     * <sg-input
     *   label="Search"
     *   type="search"
     *   leading-icon="search"
     *   clearable
     *   onSgInput={(e) => setSearch(e.detail.value)}
     * />
     * @fires sgInput - Emitted when the input value changes
     * @fires sgChange - Emitted when the input loses focus after value change
     * @fires sgFocus - Emitted when the input gains focus
     * @fires sgBlur - Emitted when the input loses focus
     * @fires sgClear - Emitted when the clear button is clicked
     * @cssprop --sg-input-bg - Input background color
     * @cssprop --sg-input-color - Input text color
     * @cssprop --sg-input-border-color - Input border color
     * @cssprop --sg-input-border-radius - Input border radius
     * @cssprop --sg-input-focus-ring - Focus ring color
     */
    interface HTMLSgInputElement extends Components.SgInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSgInputElementEventMap>(type: K, listener: (this: HTMLSgInputElement, ev: SgInputCustomEvent<HTMLSgInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSgInputElementEventMap>(type: K, listener: (this: HTMLSgInputElement, ev: SgInputCustomEvent<HTMLSgInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSgInputElement: {
        prototype: HTMLSgInputElement;
        new (): HTMLSgInputElement;
    };
    interface HTMLElementTagNameMap {
        "sg-input": HTMLSgInputElement;
    }
}
declare namespace LocalJSX {
    /**
     * @component sg-input
     * @description A versatile input component with validation, icons, and multiple variants.
     * Supports all standard HTML input types with enhanced styling and accessibility.
     * @example <!-- ═══════════════════════════════════════════════════════════════════════════════
     *      VANILLA HTML / JS
     *      ═══════════════════════════════════════════════════════════════════════════════ -->
     * <sg-input placeholder="Enter your name"></sg-input>
     * <sg-input type="email" label="Email" required></sg-input>
     * <sg-input type="password" label="Password" leading-icon="lock"></sg-input>
     * <sg-input label="Username" helper-text="Choose a unique username"></sg-input>
     * <sg-input label="Email" validation-state="error" error-message="Invalid email format"></sg-input>
     * <script>
     *   document.querySelector('sg-input').addEventListener('sgInput', (e) => {
     *     console.log('Value changed:', e.detail.value);
     *   });
     * </script>
     * <!-- ═══════════════════════════════════════════════════════════════════════════════
     *      ANGULAR
     *      ═══════════════════════════════════════════════════════════════════════════════ -->
     * <sg-input
     *   label="Email"
     *   type="email"
     *   [attr.value]="email"
     *   [attr.validation-state]="emailError ? 'error' : 'default'"
     *   [attr.error-message]="emailError"
     *   (sgInput)="onEmailChange($event)">
     * </sg-input>
     * <!-- ═══════════════════════════════════════════════════════════════════════════════
     *      REACT
     *      ═══════════════════════════════════════════════════════════════════════════════ -->
     * <sg-input
     *   label="Search"
     *   type="search"
     *   leading-icon="search"
     *   clearable
     *   onSgInput={(e) => setSearch(e.detail.value)}
     * />
     * @fires sgInput - Emitted when the input value changes
     * @fires sgChange - Emitted when the input loses focus after value change
     * @fires sgFocus - Emitted when the input gains focus
     * @fires sgBlur - Emitted when the input loses focus
     * @fires sgClear - Emitted when the clear button is clicked
     * @cssprop --sg-input-bg - Input background color
     * @cssprop --sg-input-color - Input text color
     * @cssprop --sg-input-border-color - Input border color
     * @cssprop --sg-input-border-radius - Input border radius
     * @cssprop --sg-input-focus-ring - Focus ring color
     */
    interface SgInput {
        /**
          * Autocomplete attribute
          * @attr autocomplete
         */
        "autocomplete"?: string;
        /**
          * Autofocus attribute
          * @attr autofocus
          * @default false
         */
        "autofocus"?: boolean;
        /**
          * Show clear button when input has value
          * @attr clearable
          * @default false
         */
        "clearable"?: boolean;
        /**
          * Whether the input is disabled
          * @attr disabled
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Error message (displayed when validation-state is 'error')
          * @attr error-message
         */
        "errorMessage"?: string;
        /**
          * Helper text displayed below the input
          * @attr helper-text
         */
        "helperText"?: string;
        /**
          * Label text displayed above the input
          * @attr label
         */
        "label"?: string;
        /**
          * Leading icon name (from sg-icon)
          * @attr leading-icon
         */
        "leadingIcon"?: string;
        /**
          * Maximum value for number/date inputs
          * @attr max
         */
        "max"?: string | number;
        /**
          * Maximum length for text inputs
          * @attr maxlength
         */
        "maxlength"?: number;
        /**
          * Minimum value for number/date inputs
          * @attr min
         */
        "min"?: string | number;
        /**
          * Minimum length for text inputs
          * @attr minlength
         */
        "minlength"?: number;
        /**
          * Input name attribute
          * @attr name
         */
        "name"?: string;
        /**
          * Emitted when the input loses focus
         */
        "onSgBlur"?: (event: SgInputCustomEvent<void>) => void;
        /**
          * Emitted when the input loses focus after value change
         */
        "onSgChange"?: (event: SgInputCustomEvent<{ value: string }>) => void;
        /**
          * Emitted when the clear button is clicked
         */
        "onSgClear"?: (event: SgInputCustomEvent<void>) => void;
        /**
          * Emitted when the input gains focus
         */
        "onSgFocus"?: (event: SgInputCustomEvent<void>) => void;
        /**
          * Emitted when the input value changes
         */
        "onSgInput"?: (event: SgInputCustomEvent<{ value: string; event: InputEvent }>) => void;
        /**
          * Pattern for validation (regex)
          * @attr pattern
         */
        "pattern"?: string;
        /**
          * Placeholder text
          * @attr placeholder
         */
        "placeholder"?: string;
        /**
          * Whether the input is readonly
          * @attr readonly
          * @default false
         */
        "readonly"?: boolean;
        /**
          * Whether the input is required
          * @attr required
          * @default false
         */
        "required"?: boolean;
        /**
          * Input size variant
          * @attr size
          * @default 'md'
         */
        "size"?: InputSize;
        /**
          * Step value for number inputs
          * @attr step
         */
        "step"?: string | number;
        /**
          * Trailing icon name (from sg-icon)
          * @attr trailing-icon
         */
        "trailingIcon"?: string;
        /**
          * Input type
          * @attr type
          * @default 'text'
         */
        "type"?: InputType;
        /**
          * Validation state
          * @attr validation-state
          * @default 'default'
         */
        "validationState"?: ValidationState;
        /**
          * Input value
          * @attr value
          * @default ''
         */
        "value"?: string;
        /**
          * Visual variant
          * @attr variant
          * @default 'default'
         */
        "variant"?: InputVariant;
    }
    interface IntrinsicElements {
        "sg-input": SgInput;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * @component sg-input
             * @description A versatile input component with validation, icons, and multiple variants.
             * Supports all standard HTML input types with enhanced styling and accessibility.
             * @example <!-- ═══════════════════════════════════════════════════════════════════════════════
             *      VANILLA HTML / JS
             *      ═══════════════════════════════════════════════════════════════════════════════ -->
             * <sg-input placeholder="Enter your name"></sg-input>
             * <sg-input type="email" label="Email" required></sg-input>
             * <sg-input type="password" label="Password" leading-icon="lock"></sg-input>
             * <sg-input label="Username" helper-text="Choose a unique username"></sg-input>
             * <sg-input label="Email" validation-state="error" error-message="Invalid email format"></sg-input>
             * <script>
             *   document.querySelector('sg-input').addEventListener('sgInput', (e) => {
             *     console.log('Value changed:', e.detail.value);
             *   });
             * </script>
             * <!-- ═══════════════════════════════════════════════════════════════════════════════
             *      ANGULAR
             *      ═══════════════════════════════════════════════════════════════════════════════ -->
             * <sg-input
             *   label="Email"
             *   type="email"
             *   [attr.value]="email"
             *   [attr.validation-state]="emailError ? 'error' : 'default'"
             *   [attr.error-message]="emailError"
             *   (sgInput)="onEmailChange($event)">
             * </sg-input>
             * <!-- ═══════════════════════════════════════════════════════════════════════════════
             *      REACT
             *      ═══════════════════════════════════════════════════════════════════════════════ -->
             * <sg-input
             *   label="Search"
             *   type="search"
             *   leading-icon="search"
             *   clearable
             *   onSgInput={(e) => setSearch(e.detail.value)}
             * />
             * @fires sgInput - Emitted when the input value changes
             * @fires sgChange - Emitted when the input loses focus after value change
             * @fires sgFocus - Emitted when the input gains focus
             * @fires sgBlur - Emitted when the input loses focus
             * @fires sgClear - Emitted when the clear button is clicked
             * @cssprop --sg-input-bg - Input background color
             * @cssprop --sg-input-color - Input text color
             * @cssprop --sg-input-border-color - Input border color
             * @cssprop --sg-input-border-radius - Input border radius
             * @cssprop --sg-input-focus-ring - Focus ring color
             */
            "sg-input": LocalJSX.SgInput & JSXBase.HTMLAttributes<HTMLSgInputElement>;
        }
    }
}
