name: 🐛 Bug Report
description: Report a bug in SagedUI
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out this form as completely as possible.

  - type: input
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      placeholder: "e.g., sg-button, sg-icon, sg-badge"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Import the component...
        2. Add props...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: dropdown
    id: framework
    attributes:
      label: Framework
      description: Which framework are you using?
      options:
        - Vanilla JS / HTML
        - React
        - Angular
        - Vue
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: SagedUI Version
      placeholder: "e.g., 1.3.0"
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: Browser & Version
      placeholder: "e.g., Chrome 120, Firefox 121"

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or code snippets here.
