/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import { IconDefinition } from './components/svg-icon/icons/builtin';
export { IconDefinition } from './components/svg-icon/icons/builtin';
export namespace Components {
  /**
   * @component sg-icon
   * @description SVG Icon component for SageBox - A flexible, accessible icon system
   * @example <!-- Basic usage with built-in icons -->
   * <sg-icon name="home"></sg-icon>
   * <sg-icon name="icon-home"></sg-icon>
   * <!-- With custom size -->
   * <sg-icon name="settings" size="32"></sg-icon>
   * <!-- With custom color (fill is an alias for color) -->
   * <sg-icon name="heart" color="#ff0000"></sg-icon>
   * <sg-icon name="heart" fill="#ff0000"></sg-icon>
   * <!-- Custom icon via src (fetches SVG file) -->
   * <sg-icon src="/assets/custom-icon.svg"></sg-icon>
   * <!-- Load icons from JSON file -->
   * <sg-icon name="my-icon" json-src="/assets/icons.json"></sg-icon>
   */
  interface SgIcon {
    /**
     * Accessible label for screen readers. If not provided, defaults to "{name} icon" for non-decorative icons.
     */
    ariaLabel?: string;
    /**
     * Color of the icon (CSS color value)
     * @default 'currentColor'
     */
    color: string;
    /**
     * Whether the icon is decorative (hidden from screen readers)
     * @default false
     */
    decorative: boolean;
    /**
     * Alias for color (for compatibility with legacy svg-icon components)
     * @default undefined
     */
    fill?: string;
    /**
     * Flip the icon horizontally
     * @default false
     */
    flipH: boolean;
    /**
     * Flip the icon vertically
     * @default false
     */
    flipV: boolean;
    /**
     * Get list of all registered user icons
     */
    getRegisteredIcons: () => Promise<string[]>;
    /**
     * Check if an icon exists (built-in or user-registered)
     */
    hasIcon: (name: string) => Promise<boolean>;
    /**
     * Height of the icon (overrides size)
     */
    height?: number | string;
    /**
     * URL to a JSON file containing icon definitions. The JSON should be an object mapping icon names to SVG strings. Icons are loaded once and cached globally.
     * @example <sg-icon name="my-icon" json-src="/assets/custom-icons.json"></sg-icon>
     */
    jsonSrc?: string;
    /**
     * The name of the icon from the built-in library. Supports both 'name' and 'icon-name' formats for compatibility.
     */
    name?: string;
    /**
     * Register a single icon
     * @param name - Icon name to register
     * @param icon - SVG string or IconDefinition
     * @example SgIcon.registerIcon('my-custom-icon', '<svg viewBox="0 0 24 24">...</svg>');
     */
    registerIcon: (name: string, icon: IconDefinition | string) => Promise<void>;
    /**
     * Register multiple icons at once
     * @param icons - Object with icon names as keys and SVG strings or IconDefinition as values
     * @example // Using SVG strings (recommended for users) SgIcon.registerIcons({   'my-icon': '<svg viewBox="0 0 24 24">...</svg>',   'another-icon': '<svg>...</svg>' });  // Using IconDefinition objects SgIcon.registerIcons({   'my-icon': { paths: ['M12 2...'], viewBox: '0 0 24 24' } });
     */
    registerIcons: (icons: Record<string, IconDefinition | string>) => Promise<void>;
    /**
     * Rotation angle in degrees
     */
    rotate?: number;
    /**
     * Size of the icon in pixels
     * @default 24
     */
    size: number | string;
    /**
     * Whether the icon should spin (useful for loading icons)
     * @default false
     */
    spin: boolean;
    /**
     * URL to a custom SVG icon (alternative to name)
     */
    src?: string;
    /**
     * Stroke width for outline icons
     */
    strokeWidth?: number;
    /**
     * Width of the icon (overrides size)
     */
    width?: number | string;
  }
}
declare global {
  /**
   * @component sg-icon
   * @description SVG Icon component for SageBox - A flexible, accessible icon system
   * @example <!-- Basic usage with built-in icons -->
   * <sg-icon name="home"></sg-icon>
   * <sg-icon name="icon-home"></sg-icon>
   * <!-- With custom size -->
   * <sg-icon name="settings" size="32"></sg-icon>
   * <!-- With custom color (fill is an alias for color) -->
   * <sg-icon name="heart" color="#ff0000"></sg-icon>
   * <sg-icon name="heart" fill="#ff0000"></sg-icon>
   * <!-- Custom icon via src (fetches SVG file) -->
   * <sg-icon src="/assets/custom-icon.svg"></sg-icon>
   * <!-- Load icons from JSON file -->
   * <sg-icon name="my-icon" json-src="/assets/icons.json"></sg-icon>
   */
  interface HTMLSgIconElement extends Components.SgIcon, HTMLStencilElement {}
  var HTMLSgIconElement: {
    prototype: HTMLSgIconElement;
    new (): HTMLSgIconElement;
  };
  interface HTMLElementTagNameMap {
    'sg-icon': HTMLSgIconElement;
  }
}
declare namespace LocalJSX {
  /**
   * @component sg-icon
   * @description SVG Icon component for SageBox - A flexible, accessible icon system
   * @example <!-- Basic usage with built-in icons -->
   * <sg-icon name="home"></sg-icon>
   * <sg-icon name="icon-home"></sg-icon>
   * <!-- With custom size -->
   * <sg-icon name="settings" size="32"></sg-icon>
   * <!-- With custom color (fill is an alias for color) -->
   * <sg-icon name="heart" color="#ff0000"></sg-icon>
   * <sg-icon name="heart" fill="#ff0000"></sg-icon>
   * <!-- Custom icon via src (fetches SVG file) -->
   * <sg-icon src="/assets/custom-icon.svg"></sg-icon>
   * <!-- Load icons from JSON file -->
   * <sg-icon name="my-icon" json-src="/assets/icons.json"></sg-icon>
   */
  interface SgIcon {
    /**
     * Accessible label for screen readers. If not provided, defaults to "{name} icon" for non-decorative icons.
     */
    ariaLabel?: string;
    /**
     * Color of the icon (CSS color value)
     * @default 'currentColor'
     */
    color?: string;
    /**
     * Whether the icon is decorative (hidden from screen readers)
     * @default false
     */
    decorative?: boolean;
    /**
     * Alias for color (for compatibility with legacy svg-icon components)
     * @default undefined
     */
    fill?: string;
    /**
     * Flip the icon horizontally
     * @default false
     */
    flipH?: boolean;
    /**
     * Flip the icon vertically
     * @default false
     */
    flipV?: boolean;
    /**
     * Height of the icon (overrides size)
     */
    height?: number | string;
    /**
     * URL to a JSON file containing icon definitions. The JSON should be an object mapping icon names to SVG strings. Icons are loaded once and cached globally.
     * @example <sg-icon name="my-icon" json-src="/assets/custom-icons.json"></sg-icon>
     */
    jsonSrc?: string;
    /**
     * The name of the icon from the built-in library. Supports both 'name' and 'icon-name' formats for compatibility.
     */
    name?: string;
    /**
     * Rotation angle in degrees
     */
    rotate?: number;
    /**
     * Size of the icon in pixels
     * @default 24
     */
    size?: number | string;
    /**
     * Whether the icon should spin (useful for loading icons)
     * @default false
     */
    spin?: boolean;
    /**
     * URL to a custom SVG icon (alternative to name)
     */
    src?: string;
    /**
     * Stroke width for outline icons
     */
    strokeWidth?: number;
    /**
     * Width of the icon (overrides size)
     */
    width?: number | string;
  }
  interface IntrinsicElements {
    'sg-icon': SgIcon;
  }
}
export { LocalJSX as JSX };
declare module '@stencil/core' {
  export namespace JSX {
    interface IntrinsicElements {
      /**
       * @component sg-icon
       * @description SVG Icon component for SageBox - A flexible, accessible icon system
       * @example <!-- Basic usage with built-in icons -->
       * <sg-icon name="home"></sg-icon>
       * <sg-icon name="icon-home"></sg-icon>
       * <!-- With custom size -->
       * <sg-icon name="settings" size="32"></sg-icon>
       * <!-- With custom color (fill is an alias for color) -->
       * <sg-icon name="heart" color="#ff0000"></sg-icon>
       * <sg-icon name="heart" fill="#ff0000"></sg-icon>
       * <!-- Custom icon via src (fetches SVG file) -->
       * <sg-icon src="/assets/custom-icon.svg"></sg-icon>
       * <!-- Load icons from JSON file -->
       * <sg-icon name="my-icon" json-src="/assets/icons.json"></sg-icon>
       */
      'sg-icon': LocalJSX.SgIcon & JSXBase.HTMLAttributes<HTMLSgIconElement>;
    }
  }
}
