/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ContextMenuItem } from "./components/context-menu/context-menu";
export { ContextMenuItem } from "./components/context-menu/context-menu";
export namespace Components {
    /**
     * @component sg-context-menu
     * @description Floating context menu that appears on right-click or programmatically.
     * Automatically closes on Escape key, click outside, or item selection.
     * @example <sg-context-menu id="myMenu"></sg-context-menu>
     * <script>
     *   const menu = document.getElementById('myMenu');
     *   menu.items = [
     *     { id: 'edit', label: 'Edit', icon: 'edit' },
     *     { id: 'delete', label: 'Delete', icon: 'delete', danger: true }
     *   ];
     *   document.addEventListener('contextmenu', (e) => {
     *     e.preventDefault();
     *     menu.show(e.clientX, e.clientY);
     *   });
     * </script>
     */
    interface SgContextMenu {
        /**
          * Close the context menu
         */
        "close": () => Promise<void>;
        /**
          * Menu items to display
          * @default []
         */
        "items": ContextMenuItem[];
        /**
          * Show the context menu at the specified position
         */
        "show": (x: number, y: number) => Promise<void>;
    }
}
export interface SgContextMenuCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSgContextMenuElement;
}
declare global {
    interface HTMLSgContextMenuElementEventMap {
        "itemClick": string;
        "menuClose": void;
    }
    /**
     * @component sg-context-menu
     * @description Floating context menu that appears on right-click or programmatically.
     * Automatically closes on Escape key, click outside, or item selection.
     * @example <sg-context-menu id="myMenu"></sg-context-menu>
     * <script>
     *   const menu = document.getElementById('myMenu');
     *   menu.items = [
     *     { id: 'edit', label: 'Edit', icon: 'edit' },
     *     { id: 'delete', label: 'Delete', icon: 'delete', danger: true }
     *   ];
     *   document.addEventListener('contextmenu', (e) => {
     *     e.preventDefault();
     *     menu.show(e.clientX, e.clientY);
     *   });
     * </script>
     */
    interface HTMLSgContextMenuElement extends Components.SgContextMenu, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSgContextMenuElementEventMap>(type: K, listener: (this: HTMLSgContextMenuElement, ev: SgContextMenuCustomEvent<HTMLSgContextMenuElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSgContextMenuElementEventMap>(type: K, listener: (this: HTMLSgContextMenuElement, ev: SgContextMenuCustomEvent<HTMLSgContextMenuElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSgContextMenuElement: {
        prototype: HTMLSgContextMenuElement;
        new (): HTMLSgContextMenuElement;
    };
    interface HTMLElementTagNameMap {
        "sg-context-menu": HTMLSgContextMenuElement;
    }
}
declare namespace LocalJSX {
    /**
     * @component sg-context-menu
     * @description Floating context menu that appears on right-click or programmatically.
     * Automatically closes on Escape key, click outside, or item selection.
     * @example <sg-context-menu id="myMenu"></sg-context-menu>
     * <script>
     *   const menu = document.getElementById('myMenu');
     *   menu.items = [
     *     { id: 'edit', label: 'Edit', icon: 'edit' },
     *     { id: 'delete', label: 'Delete', icon: 'delete', danger: true }
     *   ];
     *   document.addEventListener('contextmenu', (e) => {
     *     e.preventDefault();
     *     menu.show(e.clientX, e.clientY);
     *   });
     * </script>
     */
    interface SgContextMenu {
        /**
          * Menu items to display
          * @default []
         */
        "items"?: ContextMenuItem[];
        /**
          * Emitted when a menu item is clicked
         */
        "onItemClick"?: (event: SgContextMenuCustomEvent<string>) => void;
        /**
          * Emitted when menu is closed
         */
        "onMenuClose"?: (event: SgContextMenuCustomEvent<void>) => void;
    }
    interface IntrinsicElements {
        "sg-context-menu": SgContextMenu;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * @component sg-context-menu
             * @description Floating context menu that appears on right-click or programmatically.
             * Automatically closes on Escape key, click outside, or item selection.
             * @example <sg-context-menu id="myMenu"></sg-context-menu>
             * <script>
             *   const menu = document.getElementById('myMenu');
             *   menu.items = [
             *     { id: 'edit', label: 'Edit', icon: 'edit' },
             *     { id: 'delete', label: 'Delete', icon: 'delete', danger: true }
             *   ];
             *   document.addEventListener('contextmenu', (e) => {
             *     e.preventDefault();
             *     menu.show(e.clientX, e.clientY);
             *   });
             * </script>
             */
            "sg-context-menu": LocalJSX.SgContextMenu & JSXBase.HTMLAttributes<HTMLSgContextMenuElement>;
        }
    }
}
