/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    /**
     * @component sg-search-box
     * @description Search input component with search and clear buttons.
     * Supports Enter key to trigger search and emits events for search actions.
     * @example <sg-search-box 
     *   placeholder="Search users..." 
     *   search-button-label="Find"
     *   clear-button-label="Clear"
     * ></sg-search-box>
     */
    interface SgSearchBox {
        /**
          * Label for clear button
          * @default 'Limpiar'
         */
        "clearButtonLabel": string;
        /**
          * Icon name for clear button
          * @default 'delete'
         */
        "clearIcon": string;
        /**
          * Disable the search box
          * @default false
         */
        "disabled": boolean;
        /**
          * Hide clear button
          * @default false
         */
        "hideClearButton": boolean;
        /**
          * Hide search button
          * @default false
         */
        "hideSearchButton": boolean;
        /**
          * Placeholder text for the input
          * @default 'Buscar...'
         */
        "placeholder": string;
        /**
          * Label for search button
          * @default 'Buscar'
         */
        "searchButtonLabel": string;
        /**
          * Icon name for search button
          * @default 'view'
         */
        "searchIcon": string;
        /**
          * Size variant: 'sm' | 'md' | 'lg'
          * @default 'md'
         */
        "size": 'sm' | 'md' | 'lg';
        /**
          * Current search term value
          * @default ''
         */
        "value": string;
    }
}
export interface SgSearchBoxCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSgSearchBoxElement;
}
declare global {
    interface HTMLSgSearchBoxElementEventMap {
        "sgInput": string;
        "sgSearch": string;
        "sgClear": void;
    }
    /**
     * @component sg-search-box
     * @description Search input component with search and clear buttons.
     * Supports Enter key to trigger search and emits events for search actions.
     * @example <sg-search-box 
     *   placeholder="Search users..." 
     *   search-button-label="Find"
     *   clear-button-label="Clear"
     * ></sg-search-box>
     */
    interface HTMLSgSearchBoxElement extends Components.SgSearchBox, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSgSearchBoxElementEventMap>(type: K, listener: (this: HTMLSgSearchBoxElement, ev: SgSearchBoxCustomEvent<HTMLSgSearchBoxElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSgSearchBoxElementEventMap>(type: K, listener: (this: HTMLSgSearchBoxElement, ev: SgSearchBoxCustomEvent<HTMLSgSearchBoxElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSgSearchBoxElement: {
        prototype: HTMLSgSearchBoxElement;
        new (): HTMLSgSearchBoxElement;
    };
    interface HTMLElementTagNameMap {
        "sg-search-box": HTMLSgSearchBoxElement;
    }
}
declare namespace LocalJSX {
    /**
     * @component sg-search-box
     * @description Search input component with search and clear buttons.
     * Supports Enter key to trigger search and emits events for search actions.
     * @example <sg-search-box 
     *   placeholder="Search users..." 
     *   search-button-label="Find"
     *   clear-button-label="Clear"
     * ></sg-search-box>
     */
    interface SgSearchBox {
        /**
          * Label for clear button
          * @default 'Limpiar'
         */
        "clearButtonLabel"?: string;
        /**
          * Icon name for clear button
          * @default 'delete'
         */
        "clearIcon"?: string;
        /**
          * Disable the search box
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Hide clear button
          * @default false
         */
        "hideClearButton"?: boolean;
        /**
          * Hide search button
          * @default false
         */
        "hideSearchButton"?: boolean;
        /**
          * Emitted when clear button is clicked
         */
        "onSgClear"?: (event: SgSearchBoxCustomEvent<void>) => void;
        /**
          * Emitted when search term changes
         */
        "onSgInput"?: (event: SgSearchBoxCustomEvent<string>) => void;
        /**
          * Emitted when search is triggered (button click or Enter)
         */
        "onSgSearch"?: (event: SgSearchBoxCustomEvent<string>) => void;
        /**
          * Placeholder text for the input
          * @default 'Buscar...'
         */
        "placeholder"?: string;
        /**
          * Label for search button
          * @default 'Buscar'
         */
        "searchButtonLabel"?: string;
        /**
          * Icon name for search button
          * @default 'view'
         */
        "searchIcon"?: string;
        /**
          * Size variant: 'sm' | 'md' | 'lg'
          * @default 'md'
         */
        "size"?: 'sm' | 'md' | 'lg';
        /**
          * Current search term value
          * @default ''
         */
        "value"?: string;
    }
    interface IntrinsicElements {
        "sg-search-box": SgSearchBox;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * @component sg-search-box
             * @description Search input component with search and clear buttons.
             * Supports Enter key to trigger search and emits events for search actions.
             * @example <sg-search-box 
             *   placeholder="Search users..." 
             *   search-button-label="Find"
             *   clear-button-label="Clear"
             * ></sg-search-box>
             */
            "sg-search-box": LocalJSX.SgSearchBox & JSXBase.HTMLAttributes<HTMLSgSearchBoxElement>;
        }
    }
}
