/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { TooltipPosition, TooltipTrigger, TooltipVariant } from "./components/tooltip/tooltip";
export { TooltipPosition, TooltipTrigger, TooltipVariant } from "./components/tooltip/tooltip";
export namespace Components {
    /**
     * @component sg-tooltip
     * @description A tooltip component for displaying contextual information on hover, focus, or click.
     * @example ### Basic Usage
     * ```html
     * <sg-tooltip text="This is a tooltip">
     *   <button>Hover me</button>
     * </sg-tooltip>
     * ```
     * ### With Position
     * ```html
     * <sg-tooltip text="Top tooltip" position="top">...</sg-tooltip>
     * <sg-tooltip text="Right tooltip" position="right">...</sg-tooltip>
     * ```
     * ### With Trigger
     * ```html
     * <sg-tooltip text="Click to show" trigger="click">...</sg-tooltip>
     * ```
     */
    interface SgTooltip {
        /**
          * Show arrow pointer
          * @default true
         */
        "arrow": boolean;
        /**
          * Disable the tooltip
          * @default false
         */
        "disabled": boolean;
        /**
          * Hide the tooltip programmatically
         */
        "hide": () => Promise<void>;
        /**
          * Delay before hiding (ms)
          * @default 100
         */
        "hideDelay": number;
        /**
          * Interactive tooltip (can hover over tooltip content)
          * @default false
         */
        "interactive": boolean;
        /**
          * Maximum width of tooltip
          * @default '250px'
         */
        "maxWidth": string;
        /**
          * Keep tooltip visible (for manual control)
          * @default false
         */
        "open": boolean;
        /**
          * Position of the tooltip relative to trigger
          * @default 'top'
         */
        "position": TooltipPosition;
        /**
          * Show the tooltip programmatically
         */
        "show": () => Promise<void>;
        /**
          * Delay before showing (ms)
          * @default 200
         */
        "showDelay": number;
        /**
          * Tooltip text content
          * @default ''
         */
        "text": string;
        /**
          * Toggle tooltip visibility
         */
        "toggle": () => Promise<void>;
        /**
          * How to trigger the tooltip
          * @default 'hover'
         */
        "trigger": TooltipTrigger;
        /**
          * Visual variant
          * @default 'default'
         */
        "variant": TooltipVariant;
    }
}
export interface SgTooltipCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSgTooltipElement;
}
declare global {
    interface HTMLSgTooltipElementEventMap {
        "sgShow": void;
        "sgHide": void;
    }
    /**
     * @component sg-tooltip
     * @description A tooltip component for displaying contextual information on hover, focus, or click.
     * @example ### Basic Usage
     * ```html
     * <sg-tooltip text="This is a tooltip">
     *   <button>Hover me</button>
     * </sg-tooltip>
     * ```
     * ### With Position
     * ```html
     * <sg-tooltip text="Top tooltip" position="top">...</sg-tooltip>
     * <sg-tooltip text="Right tooltip" position="right">...</sg-tooltip>
     * ```
     * ### With Trigger
     * ```html
     * <sg-tooltip text="Click to show" trigger="click">...</sg-tooltip>
     * ```
     */
    interface HTMLSgTooltipElement extends Components.SgTooltip, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSgTooltipElementEventMap>(type: K, listener: (this: HTMLSgTooltipElement, ev: SgTooltipCustomEvent<HTMLSgTooltipElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSgTooltipElementEventMap>(type: K, listener: (this: HTMLSgTooltipElement, ev: SgTooltipCustomEvent<HTMLSgTooltipElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSgTooltipElement: {
        prototype: HTMLSgTooltipElement;
        new (): HTMLSgTooltipElement;
    };
    interface HTMLElementTagNameMap {
        "sg-tooltip": HTMLSgTooltipElement;
    }
}
declare namespace LocalJSX {
    /**
     * @component sg-tooltip
     * @description A tooltip component for displaying contextual information on hover, focus, or click.
     * @example ### Basic Usage
     * ```html
     * <sg-tooltip text="This is a tooltip">
     *   <button>Hover me</button>
     * </sg-tooltip>
     * ```
     * ### With Position
     * ```html
     * <sg-tooltip text="Top tooltip" position="top">...</sg-tooltip>
     * <sg-tooltip text="Right tooltip" position="right">...</sg-tooltip>
     * ```
     * ### With Trigger
     * ```html
     * <sg-tooltip text="Click to show" trigger="click">...</sg-tooltip>
     * ```
     */
    interface SgTooltip {
        /**
          * Show arrow pointer
          * @default true
         */
        "arrow"?: boolean;
        /**
          * Disable the tooltip
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Delay before hiding (ms)
          * @default 100
         */
        "hideDelay"?: number;
        /**
          * Interactive tooltip (can hover over tooltip content)
          * @default false
         */
        "interactive"?: boolean;
        /**
          * Maximum width of tooltip
          * @default '250px'
         */
        "maxWidth"?: string;
        /**
          * Emitted when tooltip is hidden
         */
        "onSgHide"?: (event: SgTooltipCustomEvent<void>) => void;
        /**
          * Emitted when tooltip is shown
         */
        "onSgShow"?: (event: SgTooltipCustomEvent<void>) => void;
        /**
          * Keep tooltip visible (for manual control)
          * @default false
         */
        "open"?: boolean;
        /**
          * Position of the tooltip relative to trigger
          * @default 'top'
         */
        "position"?: TooltipPosition;
        /**
          * Delay before showing (ms)
          * @default 200
         */
        "showDelay"?: number;
        /**
          * Tooltip text content
          * @default ''
         */
        "text"?: string;
        /**
          * How to trigger the tooltip
          * @default 'hover'
         */
        "trigger"?: TooltipTrigger;
        /**
          * Visual variant
          * @default 'default'
         */
        "variant"?: TooltipVariant;
    }
    interface IntrinsicElements {
        "sg-tooltip": SgTooltip;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * @component sg-tooltip
             * @description A tooltip component for displaying contextual information on hover, focus, or click.
             * @example ### Basic Usage
             * ```html
             * <sg-tooltip text="This is a tooltip">
             *   <button>Hover me</button>
             * </sg-tooltip>
             * ```
             * ### With Position
             * ```html
             * <sg-tooltip text="Top tooltip" position="top">...</sg-tooltip>
             * <sg-tooltip text="Right tooltip" position="right">...</sg-tooltip>
             * ```
             * ### With Trigger
             * ```html
             * <sg-tooltip text="Click to show" trigger="click">...</sg-tooltip>
             * ```
             */
            "sg-tooltip": LocalJSX.SgTooltip & JSXBase.HTMLAttributes<HTMLSgTooltipElement>;
        }
    }
}
