/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    /**
     * @component sg-form-section
     * @description Section container for forms with title, icon and step indicators.
     * Provides consistent visual structure for form sections.
     * @example <sg-form-section section-title="Personal Information" step-number="1" total-steps="3" icon-bg-class="bg-blue-100">
     *   <sg-icon slot="icon" name="user"></sg-icon>
     *   <sg-input label="Name"></sg-input>
     *   <sg-input label="Email" type="email"></sg-input>
     * </sg-form-section>
     */
    interface SgFormSection {
        /**
          * Whether section is initially collapsed (only if collapsible)
          * @default false
         */
        "collapsed": boolean;
        /**
          * Whether section is collapsible
          * @default false
         */
        "collapsible": boolean;
        /**
          * CSS class for icon background color
          * @default 'bg-blue-100'
         */
        "iconBgClass": string;
        /**
          * Title of the section
          * @default ''
         */
        "sectionTitle": string;
        /**
          * Current step number (optional)
         */
        "stepNumber"?: number;
        /**
          * Total number of steps (optional)
         */
        "totalSteps"?: number;
    }
}
declare global {
    /**
     * @component sg-form-section
     * @description Section container for forms with title, icon and step indicators.
     * Provides consistent visual structure for form sections.
     * @example <sg-form-section section-title="Personal Information" step-number="1" total-steps="3" icon-bg-class="bg-blue-100">
     *   <sg-icon slot="icon" name="user"></sg-icon>
     *   <sg-input label="Name"></sg-input>
     *   <sg-input label="Email" type="email"></sg-input>
     * </sg-form-section>
     */
    interface HTMLSgFormSectionElement extends Components.SgFormSection, HTMLStencilElement {
    }
    var HTMLSgFormSectionElement: {
        prototype: HTMLSgFormSectionElement;
        new (): HTMLSgFormSectionElement;
    };
    interface HTMLElementTagNameMap {
        "sg-form-section": HTMLSgFormSectionElement;
    }
}
declare namespace LocalJSX {
    /**
     * @component sg-form-section
     * @description Section container for forms with title, icon and step indicators.
     * Provides consistent visual structure for form sections.
     * @example <sg-form-section section-title="Personal Information" step-number="1" total-steps="3" icon-bg-class="bg-blue-100">
     *   <sg-icon slot="icon" name="user"></sg-icon>
     *   <sg-input label="Name"></sg-input>
     *   <sg-input label="Email" type="email"></sg-input>
     * </sg-form-section>
     */
    interface SgFormSection {
        /**
          * Whether section is initially collapsed (only if collapsible)
          * @default false
         */
        "collapsed"?: boolean;
        /**
          * Whether section is collapsible
          * @default false
         */
        "collapsible"?: boolean;
        /**
          * CSS class for icon background color
          * @default 'bg-blue-100'
         */
        "iconBgClass"?: string;
        /**
          * Title of the section
          * @default ''
         */
        "sectionTitle"?: string;
        /**
          * Current step number (optional)
         */
        "stepNumber"?: number;
        /**
          * Total number of steps (optional)
         */
        "totalSteps"?: number;
    }
    interface IntrinsicElements {
        "sg-form-section": SgFormSection;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * @component sg-form-section
             * @description Section container for forms with title, icon and step indicators.
             * Provides consistent visual structure for form sections.
             * @example <sg-form-section section-title="Personal Information" step-number="1" total-steps="3" icon-bg-class="bg-blue-100">
             *   <sg-icon slot="icon" name="user"></sg-icon>
             *   <sg-input label="Name"></sg-input>
             *   <sg-input label="Email" type="email"></sg-input>
             * </sg-form-section>
             */
            "sg-form-section": LocalJSX.SgFormSection & JSXBase.HTMLAttributes<HTMLSgFormSectionElement>;
        }
    }
}
