/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { StatItem, StatsCardColor } from "./components/stats-card/stats-card";
export { StatItem, StatsCardColor } from "./components/stats-card/stats-card";
export namespace Components {
    /**
     * @component sg-stats-card
     * @description A card component for displaying statistics and metrics with icon and optional breakdown.
     * @example ```html
     * <sg-stats-card
     *   title="Total Users"
     *   value="1,234"
     *   description="Active this month"
     *   icon="users"
     *   color="primary">
     * </sg-stats-card>
     * ```
     */
    interface SgStatsCard {
        /**
          * Animation delay in ms (for staggered animations)
          * @default 0
         */
        "animationDelay": number;
        /**
          * Card title/label
          * @default ''
         */
        "cardTitle": string;
        /**
          * Color theme
          * @default 'primary'
         */
        "color": StatsCardColor;
        /**
          * Description text below the value
          * @default ''
         */
        "description": string;
        /**
          * Icon name (uses sg-icon)
         */
        "icon": string;
        /**
          * Show loading skeleton
          * @default false
         */
        "loading": boolean;
        /**
          * Additional stats breakdown (JSON string or array)
         */
        "stats": string | StatItem[];
        /**
          * Trend indicator: 'up', 'down', or percentage like '+12%'
         */
        "trend": string;
        /**
          * Whether trend is positive (green) or negative (red)
          * @default true
         */
        "trendPositive": boolean;
        /**
          * Unit suffix for the value
          * @default ''
         */
        "unit": string;
        /**
          * Main value to display
          * @default ''
         */
        "value": string | number;
    }
}
declare global {
    /**
     * @component sg-stats-card
     * @description A card component for displaying statistics and metrics with icon and optional breakdown.
     * @example ```html
     * <sg-stats-card
     *   title="Total Users"
     *   value="1,234"
     *   description="Active this month"
     *   icon="users"
     *   color="primary">
     * </sg-stats-card>
     * ```
     */
    interface HTMLSgStatsCardElement extends Components.SgStatsCard, HTMLStencilElement {
    }
    var HTMLSgStatsCardElement: {
        prototype: HTMLSgStatsCardElement;
        new (): HTMLSgStatsCardElement;
    };
    interface HTMLElementTagNameMap {
        "sg-stats-card": HTMLSgStatsCardElement;
    }
}
declare namespace LocalJSX {
    /**
     * @component sg-stats-card
     * @description A card component for displaying statistics and metrics with icon and optional breakdown.
     * @example ```html
     * <sg-stats-card
     *   title="Total Users"
     *   value="1,234"
     *   description="Active this month"
     *   icon="users"
     *   color="primary">
     * </sg-stats-card>
     * ```
     */
    interface SgStatsCard {
        /**
          * Animation delay in ms (for staggered animations)
          * @default 0
         */
        "animationDelay"?: number;
        /**
          * Card title/label
          * @default ''
         */
        "cardTitle"?: string;
        /**
          * Color theme
          * @default 'primary'
         */
        "color"?: StatsCardColor;
        /**
          * Description text below the value
          * @default ''
         */
        "description"?: string;
        /**
          * Icon name (uses sg-icon)
         */
        "icon"?: string;
        /**
          * Show loading skeleton
          * @default false
         */
        "loading"?: boolean;
        /**
          * Additional stats breakdown (JSON string or array)
         */
        "stats"?: string | StatItem[];
        /**
          * Trend indicator: 'up', 'down', or percentage like '+12%'
         */
        "trend"?: string;
        /**
          * Whether trend is positive (green) or negative (red)
          * @default true
         */
        "trendPositive"?: boolean;
        /**
          * Unit suffix for the value
          * @default ''
         */
        "unit"?: string;
        /**
          * Main value to display
          * @default ''
         */
        "value"?: string | number;
    }
    interface IntrinsicElements {
        "sg-stats-card": SgStatsCard;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * @component sg-stats-card
             * @description A card component for displaying statistics and metrics with icon and optional breakdown.
             * @example ```html
             * <sg-stats-card
             *   title="Total Users"
             *   value="1,234"
             *   description="Active this month"
             *   icon="users"
             *   color="primary">
             * </sg-stats-card>
             * ```
             */
            "sg-stats-card": LocalJSX.SgStatsCard & JSXBase.HTMLAttributes<HTMLSgStatsCardElement>;
        }
    }
}
