/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import { BadgeSize, BadgeVariant } from './components/badge/badge';
export { BadgeSize, BadgeVariant } from './components/badge/badge';
export namespace Components {
  /**
   * @example ### Angular
   * ```html
   * <sg-badge variant="success">Active</sg-badge>
   * <sg-badge variant="error" size="sm" dot>Offline</sg-badge>
   * <sg-badge variant="info" pill>New Feature</sg-badge>
   * <sg-badge variant="warning">
   *   <sg-icon slot="icon" name="alert-triangle" size="12"></sg-icon>
   *   Warning
   * </sg-badge>
   * ```
   * ### React
   * ```jsx
   * <sg-badge variant="primary" outlined>Beta</sg-badge>
   * <sg-badge variant="success" pulse>Live</sg-badge>
   * ```
   * ### Vanilla JS
   * ```html
   * <sg-badge variant="info" size="lg">Featured</sg-badge>
   * <sg-badge variant="neutral" removable id="tag1">Tag 1</sg-badge>
   * <script>
   *   document.querySelector('#tag1').addEventListener('sgRemove', (e) => {
   *     e.target.remove();
   *   });
   * </script>
   * ```
   */
  interface SgBadge {
    /**
     * Make the badge clickable/interactive
     * @default false
     */
    clickable: boolean;
    /**
     * Show a status dot indicator
     * @default false
     */
    dot: boolean;
    /**
     * Custom icon name (if using sg-icon internally)
     */
    icon: string;
    /**
     * Display as outlined style (transparent background with border)
     * @default false
     */
    outlined: boolean;
    /**
     * Display as pill shape (fully rounded)
     * @default false
     */
    pill: boolean;
    /**
     * Apply pulse animation to the dot
     * @default false
     */
    pulse: boolean;
    /**
     * Size of the badge
     * @default 'md'
     */
    size: BadgeSize;
    /**
     * Size of the badge
     */
    size?: 'xs' | 'sm' | 'md' | 'lg';
    /**
     * Display as soft/subtle style (lighter background)
     * @default false
     */
    soft: boolean;
    /**
     * Color variant of the badge
     * @default 'primary'
     */
    variant: BadgeVariant;
    /**
     * Color variant
     */
    variant?: 'primary' | 'secondary' | 'success' | 'warning' | 'error' | 'info' | 'neutral' | 'purple' | 'cyan';
  }
}
declare global {
  /**
   * @example ### Angular
   * ```html
   * <sg-badge variant="success">Active</sg-badge>
   * <sg-badge variant="error" size="sm" dot>Offline</sg-badge>
   * <sg-badge variant="info" pill>New Feature</sg-badge>
   * <sg-badge variant="warning">
   *   <sg-icon slot="icon" name="alert-triangle" size="12"></sg-icon>
   *   Warning
   * </sg-badge>
   * ```
   * ### React
   * ```jsx
   * <sg-badge variant="primary" outlined>Beta</sg-badge>
   * <sg-badge variant="success" pulse>Live</sg-badge>
   * ```
   * ### Vanilla JS
   * ```html
   * <sg-badge variant="info" size="lg">Featured</sg-badge>
   * <sg-badge variant="neutral" removable id="tag1">Tag 1</sg-badge>
   * <script>
   *   document.querySelector('#tag1').addEventListener('sgRemove', (e) => {
   *     e.target.remove();
   *   });
   * </script>
   * ```
   */
  interface HTMLSgBadgeElement extends Components.SgBadge, HTMLStencilElement {}
  var HTMLSgBadgeElement: {
    prototype: HTMLSgBadgeElement;
    new (): HTMLSgBadgeElement;
  };
  interface HTMLElementTagNameMap {
    'sg-badge': HTMLSgBadgeElement;
  }
}
declare namespace LocalJSX {
  /**
   * @example ### Angular
   * ```html
   * <sg-badge variant="success">Active</sg-badge>
   * <sg-badge variant="error" size="sm" dot>Offline</sg-badge>
   * <sg-badge variant="info" pill>New Feature</sg-badge>
   * <sg-badge variant="warning">
   *   <sg-icon slot="icon" name="alert-triangle" size="12"></sg-icon>
   *   Warning
   * </sg-badge>
   * ```
   * ### React
   * ```jsx
   * <sg-badge variant="primary" outlined>Beta</sg-badge>
   * <sg-badge variant="success" pulse>Live</sg-badge>
   * ```
   * ### Vanilla JS
   * ```html
   * <sg-badge variant="info" size="lg">Featured</sg-badge>
   * <sg-badge variant="neutral" removable id="tag1">Tag 1</sg-badge>
   * <script>
   *   document.querySelector('#tag1').addEventListener('sgRemove', (e) => {
   *     e.target.remove();
   *   });
   * </script>
   * ```
   */
  interface SgBadge {
    /**
     * Make the badge clickable/interactive
     * @default false
     */
    clickable?: boolean;
    /**
     * Show a status dot indicator
     * @default false
     */
    dot?: boolean;
    /**
     * Custom icon name (if using sg-icon internally)
     */
    icon?: string;
    /**
     * Display as outlined style (transparent background with border)
     * @default false
     */
    outlined?: boolean;
    /**
     * Display as pill shape (fully rounded)
     * @default false
     */
    pill?: boolean;
    /**
     * Apply pulse animation to the dot
     * @default false
     */
    pulse?: boolean;
    /**
     * Size of the badge
     * @default 'md'
     */
    size?: BadgeSize;
    /**
     * Size of the badge
     */
    size?: 'xs' | 'sm' | 'md' | 'lg';
    /**
     * Display as soft/subtle style (lighter background)
     * @default false
     */
    soft?: boolean;
    /**
     * Color variant of the badge
     * @default 'primary'
     */
    variant?: BadgeVariant;
    /**
     * Color variant
     */
    variant?: 'primary' | 'secondary' | 'success' | 'warning' | 'error' | 'info' | 'neutral' | 'purple' | 'cyan';
  }
  interface IntrinsicElements {
    'sg-badge': SgBadge;
  }
}
export { LocalJSX as JSX };
declare module '@stencil/core' {
  export namespace JSX {
    interface IntrinsicElements {
      /**
       * @example ### Angular
       * ```html
       * <sg-badge variant="success">Active</sg-badge>
       * <sg-badge variant="error" size="sm" dot>Offline</sg-badge>
       * <sg-badge variant="info" pill>New Feature</sg-badge>
       * <sg-badge variant="warning">
       *   <sg-icon slot="icon" name="alert-triangle" size="12"></sg-icon>
       *   Warning
       * </sg-badge>
       * ```
       * ### React
       * ```jsx
       * <sg-badge variant="primary" outlined>Beta</sg-badge>
       * <sg-badge variant="success" pulse>Live</sg-badge>
       * ```
       * ### Vanilla JS
       * ```html
       * <sg-badge variant="info" size="lg">Featured</sg-badge>
       * <sg-badge variant="neutral" removable id="tag1">Tag 1</sg-badge>
       * <script>
       *   document.querySelector('#tag1').addEventListener('sgRemove', (e) => {
       *     e.target.remove();
       *   });
       * </script>
       * ```
       */
      'sg-badge': LocalJSX.SgBadge & JSXBase.HTMLAttributes<HTMLSgBadgeElement>;
    }
  }
}
