/**
 * SageBox Vite Plugin
 *
 * Hot reload for icons and automatic TypeScript generation
 *
 * Usage in vite.config.js:
 *
 * import { SageBoxIcons } from 'sagebox/cli/plugins/vite';
 *
 * export default {
 *   plugins: [
 *     SageBoxIcons({
 *       watch: true,
 *       iconsDir: './src/icons',
 *       output: './src/icons/index.ts'
 *     })
 *   ]
 * }
 */

const fs = require('fs');
const path = require('path');
const { parseSVG } = require('../utils/svg-parser');

/**
 * Default plugin options
 */
const DEFAULT_OPTIONS = {
  watch: true,
  iconsDir: './src/icons',
  jsonFile: 'icons.json',
  output: './src/icons/index.ts',
  prefix: '',
  optimize: true
};

/**
 * Generate TypeScript from icons.json
 */
function generateTypeScript(icons, options = {}) {
  const iconNames = Object.keys(icons);

  let content = `/**
 * SVG Icon Library - Custom icon definitions
 *
 * ⚠️  AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * Generated by SageBox Vite Plugin
 * Generated: ${new Date().toISOString()}
 */

export interface IconDefinition {
  paths: string[];
  viewBox?: string;
  fillRule?: 'nonzero' | 'evenodd';
}

export const customIcons: Record<string, IconDefinition> = {\n`;

  for (const [name, def] of Object.entries(icons)) {
    content += `  '${name}': {\n`;
    content += `    paths: [\n`;
    def.paths.forEach((p, i) => {
      content += `      '${p}'${i < def.paths.length - 1 ? ',' : ''}\n`;
    });
    content += `    ],\n`;

    if (def.viewBox && def.viewBox !== '0 0 24 24') {
      content += `    viewBox: '${def.viewBox}',\n`;
    }

    if (def.fillRule && def.fillRule !== 'nonzero') {
      content += `    fillRule: '${def.fillRule}',\n`;
    }

    content += `  },\n`;
  }

  content += `};

export type CustomIconName = keyof typeof customIcons;

export const customIconNames = Object.keys(customIcons) as CustomIconName[];

export default customIcons;
`;

  return content;
}

/**
 * Process SVG files in directory
 */
function processSVGFiles(iconsDir, existingIcons = {}) {
  const icons = { ...existingIcons };

  if (!fs.existsSync(iconsDir)) {
    return icons;
  }

  const files = fs.readdirSync(iconsDir).filter(f => f.endsWith('.svg'));

  for (const file of files) {
    const filePath = path.join(iconsDir, file);
    const content = fs.readFileSync(filePath, 'utf-8');
    const parsed = parseSVG(content);

    if (parsed.paths.length > 0) {
      const name = path.basename(file, '.svg')
        .replace(/([a-z])([A-Z])/g, '$1-$2')
        .replace(/[\s_]+/g, '-')
        .toLowerCase();

      icons[name] = {
        paths: parsed.paths,
        ...(parsed.viewBox !== '0 0 24 24' && { viewBox: parsed.viewBox }),
        ...(parsed.fillRule && parsed.fillRule !== 'nonzero' && { fillRule: parsed.fillRule })
      };
    }
  }

  return icons;
}

/**
 * SageBox Icons Vite Plugin
 */
function SageBoxIcons(userOptions = {}) {
  const options = { ...DEFAULT_OPTIONS, ...userOptions };
  let root = process.cwd();

  return {
    name: 'sagebox-icons',

    configResolved(config) {
      root = config.root;
    },

    buildStart() {
      const iconsDir = path.resolve(root, options.iconsDir);
      const jsonPath = path.join(iconsDir, options.jsonFile);
      const outputPath = path.resolve(root, options.output);

      // Initial build
      generateIconsFile(iconsDir, jsonPath, outputPath, options);
    },

    configureServer(server) {
      if (!options.watch) return;

      const iconsDir = path.resolve(root, options.iconsDir);
      const jsonPath = path.join(iconsDir, options.jsonFile);
      const outputPath = path.resolve(root, options.output);

      // Watch for changes
      server.watcher.add([iconsDir]);

      server.watcher.on('change', (changedPath) => {
        if (changedPath.endsWith('.svg') || changedPath.endsWith('icons.json')) {
          console.log(`\n🎨 [sagebox] Icon changed: ${path.basename(changedPath)}`);
          generateIconsFile(iconsDir, jsonPath, outputPath, options);

          // Trigger HMR
          const mod = server.moduleGraph.getModuleById(outputPath);
          if (mod) {
            server.moduleGraph.invalidateModule(mod);
            server.ws.send({
              type: 'full-reload',
              path: '*'
            });
          }
        }
      });

      server.watcher.on('add', (addedPath) => {
        if (addedPath.endsWith('.svg')) {
          console.log(`\n🎨 [sagebox] Icon added: ${path.basename(addedPath)}`);
          generateIconsFile(iconsDir, jsonPath, outputPath, options);
        }
      });

      server.watcher.on('unlink', (removedPath) => {
        if (removedPath.endsWith('.svg')) {
          console.log(`\n🎨 [sagebox] Icon removed: ${path.basename(removedPath)}`);
          generateIconsFile(iconsDir, jsonPath, outputPath, options);
        }
      });
    },

    // Virtual module for importing icons
    resolveId(id) {
      if (id === 'virtual:sagebox-icons') {
        return '\0virtual:sagebox-icons';
      }
    },

    load(id) {
      if (id === '\0virtual:sagebox-icons') {
        const iconsDir = path.resolve(root, options.iconsDir);
        const jsonPath = path.join(iconsDir, options.jsonFile);

        let icons = {};
        if (fs.existsSync(jsonPath)) {
          icons = JSON.parse(fs.readFileSync(jsonPath, 'utf-8'));
        }
        icons = processSVGFiles(iconsDir, icons);

        return generateTypeScript(icons, options);
      }
    }
  };
}

/**
 * Generate icons file
 */
function generateIconsFile(iconsDir, jsonPath, outputPath, options) {
  try {
    // Ensure directory exists
    const outputDir = path.dirname(outputPath);
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true });
    }

    // Load existing JSON icons
    let icons = {};
    if (fs.existsSync(jsonPath)) {
      icons = JSON.parse(fs.readFileSync(jsonPath, 'utf-8'));
    }

    // Process SVG files
    icons = processSVGFiles(iconsDir, icons);

    // Generate TypeScript
    const content = generateTypeScript(icons, options);
    fs.writeFileSync(outputPath, content, 'utf-8');

    console.log(`🎨 [sagebox] Generated ${Object.keys(icons).length} icons → ${path.relative(process.cwd(), outputPath)}`);
  } catch (e) {
    console.error(`🎨 [sagebox] Error: ${e.message}`);
  }
}

module.exports = { SageBoxIcons };
module.exports.default = SageBoxIcons;
