/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ModalSize } from "./components/modal/modal";
export { ModalSize } from "./components/modal/modal";
export namespace Components {
    /**
     * @component sg-modal
     * @description A modern modal dialog component built on the native HTML <dialog> element.
     * Provides built-in accessibility, focus trapping, and backdrop handling.
     * @example <!-- ═══════════════════════════════════════════════════════════════════════════════
     *      VANILLA HTML / JS
     *      ═══════════════════════════════════════════════════════════════════════════════ -->
     * <sg-modal id="myModal" header="Confirm Action">
     *   <p>Are you sure you want to continue?</p>
     *   <div slot="footer">
     *     <sg-button variant="secondary" onclick="document.getElementById('myModal').close()">Cancel</sg-button>
     *     <sg-button variant="primary">Confirm</sg-button>
     *   </div>
     * </sg-modal>
     * <sg-button onclick="document.getElementById('myModal').showModal()">Open Modal</sg-button>
     * <script>
     *   document.getElementById('myModal').addEventListener('sgClose', (e) => {
     *     console.log('Modal closed with:', e.detail);
     *   });
     * </script>
     * <!-- ═══════════════════════════════════════════════════════════════════════════════
     *      ANGULAR
     *      ═══════════════════════════════════════════════════════════════════════════════ -->
     * <sg-modal
     *   #modal
     *   header="Edit Profile"
     *   [attr.open]="isOpen || null"
     *   (sgClose)="onClose($event)"
     *   (sgCancel)="onCancel()">
     *   <form>...</form>
     *   <div slot="footer">
     *     <sg-button (sgClick)="modal.close()">Cancel</sg-button>
     *     <sg-button variant="primary" (sgClick)="save()">Save</sg-button>
     *   </div>
     * </sg-modal>
     * <!-- ═══════════════════════════════════════════════════════════════════════════════
     *      REACT
     *      ═══════════════════════════════════════════════════════════════════════════════ -->
     * <sg-modal
     *   ref={modalRef}
     *   header="Delete Item"
     *   size="sm"
     *   onSgClose={(e) => handleClose(e.detail)}
     *   onSgCancel={() => handleCancel()}>
     *   <p>This action cannot be undone.</p>
     *   <div slot="footer">
     *     <sg-button onClick={() => modalRef.current.close()}>Cancel</sg-button>
     *     <sg-button variant="error" onClick={() => handleDelete()}>Delete</sg-button>
     *   </div>
     * </sg-modal>
     * @fires sgOpen - Emitted when the modal opens
     * @fires sgClose - Emitted when the modal closes, detail contains returnValue
     * @fires sgCancel - Emitted when user cancels (Escape or backdrop click)
     * @cssprop --sg-modal-width - Modal width (default: auto based on size)
     * @cssprop --sg-modal-max-width - Modal max width
     * @cssprop --sg-modal-max-height - Modal max height
     * @cssprop --sg-modal-padding - Modal content padding
     * @cssprop --sg-modal-radius - Modal border radius
     * @cssprop --sg-modal-backdrop-color - Backdrop overlay color
     * @cssprop --sg-modal-shadow - Modal box shadow
     */
    interface SgModal {
        /**
          * Closes the modal dialog
          * @param returnValue - Optional value to pass to the close event
         */
        "close": (returnValue?: string) => Promise<void>;
        /**
          * Whether the modal can be closed by clicking the backdrop
          * @default true
         */
        "closeOnBackdrop": boolean;
        /**
          * Whether the modal can be closed by pressing Escape
          * @default true
         */
        "closeOnEscape": boolean;
        /**
          * Modal header text
         */
        "header"?: string;
        /**
          * Whether the modal is a non-modal dialog (doesn't block interaction)
          * @default false
         */
        "nonModal": boolean;
        /**
          * Whether the modal is open
          * @default false
         */
        "open": boolean;
        /**
          * Whether to show the backdrop overlay
          * @default true
         */
        "overlay": boolean;
        /**
          * Opens as non-modal dialog
         */
        "show": () => Promise<void>;
        /**
          * Whether to show the close button in the header
          * @default true
         */
        "showCloseButton": boolean;
        /**
          * Opens the modal dialog
         */
        "showModal": () => Promise<void>;
        /**
          * Modal size preset
          * @default 'md'
         */
        "size": ModalSize;
    }
}
export interface SgModalCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSgModalElement;
}
declare global {
    interface HTMLSgModalElementEventMap {
        "sgOpen": void;
        "sgClose": string;
        "sgCancel": void;
    }
    /**
     * @component sg-modal
     * @description A modern modal dialog component built on the native HTML <dialog> element.
     * Provides built-in accessibility, focus trapping, and backdrop handling.
     * @example <!-- ═══════════════════════════════════════════════════════════════════════════════
     *      VANILLA HTML / JS
     *      ═══════════════════════════════════════════════════════════════════════════════ -->
     * <sg-modal id="myModal" header="Confirm Action">
     *   <p>Are you sure you want to continue?</p>
     *   <div slot="footer">
     *     <sg-button variant="secondary" onclick="document.getElementById('myModal').close()">Cancel</sg-button>
     *     <sg-button variant="primary">Confirm</sg-button>
     *   </div>
     * </sg-modal>
     * <sg-button onclick="document.getElementById('myModal').showModal()">Open Modal</sg-button>
     * <script>
     *   document.getElementById('myModal').addEventListener('sgClose', (e) => {
     *     console.log('Modal closed with:', e.detail);
     *   });
     * </script>
     * <!-- ═══════════════════════════════════════════════════════════════════════════════
     *      ANGULAR
     *      ═══════════════════════════════════════════════════════════════════════════════ -->
     * <sg-modal
     *   #modal
     *   header="Edit Profile"
     *   [attr.open]="isOpen || null"
     *   (sgClose)="onClose($event)"
     *   (sgCancel)="onCancel()">
     *   <form>...</form>
     *   <div slot="footer">
     *     <sg-button (sgClick)="modal.close()">Cancel</sg-button>
     *     <sg-button variant="primary" (sgClick)="save()">Save</sg-button>
     *   </div>
     * </sg-modal>
     * <!-- ═══════════════════════════════════════════════════════════════════════════════
     *      REACT
     *      ═══════════════════════════════════════════════════════════════════════════════ -->
     * <sg-modal
     *   ref={modalRef}
     *   header="Delete Item"
     *   size="sm"
     *   onSgClose={(e) => handleClose(e.detail)}
     *   onSgCancel={() => handleCancel()}>
     *   <p>This action cannot be undone.</p>
     *   <div slot="footer">
     *     <sg-button onClick={() => modalRef.current.close()}>Cancel</sg-button>
     *     <sg-button variant="error" onClick={() => handleDelete()}>Delete</sg-button>
     *   </div>
     * </sg-modal>
     * @fires sgOpen - Emitted when the modal opens
     * @fires sgClose - Emitted when the modal closes, detail contains returnValue
     * @fires sgCancel - Emitted when user cancels (Escape or backdrop click)
     * @cssprop --sg-modal-width - Modal width (default: auto based on size)
     * @cssprop --sg-modal-max-width - Modal max width
     * @cssprop --sg-modal-max-height - Modal max height
     * @cssprop --sg-modal-padding - Modal content padding
     * @cssprop --sg-modal-radius - Modal border radius
     * @cssprop --sg-modal-backdrop-color - Backdrop overlay color
     * @cssprop --sg-modal-shadow - Modal box shadow
     */
    interface HTMLSgModalElement extends Components.SgModal, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSgModalElementEventMap>(type: K, listener: (this: HTMLSgModalElement, ev: SgModalCustomEvent<HTMLSgModalElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSgModalElementEventMap>(type: K, listener: (this: HTMLSgModalElement, ev: SgModalCustomEvent<HTMLSgModalElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSgModalElement: {
        prototype: HTMLSgModalElement;
        new (): HTMLSgModalElement;
    };
    interface HTMLElementTagNameMap {
        "sg-modal": HTMLSgModalElement;
    }
}
declare namespace LocalJSX {
    /**
     * @component sg-modal
     * @description A modern modal dialog component built on the native HTML <dialog> element.
     * Provides built-in accessibility, focus trapping, and backdrop handling.
     * @example <!-- ═══════════════════════════════════════════════════════════════════════════════
     *      VANILLA HTML / JS
     *      ═══════════════════════════════════════════════════════════════════════════════ -->
     * <sg-modal id="myModal" header="Confirm Action">
     *   <p>Are you sure you want to continue?</p>
     *   <div slot="footer">
     *     <sg-button variant="secondary" onclick="document.getElementById('myModal').close()">Cancel</sg-button>
     *     <sg-button variant="primary">Confirm</sg-button>
     *   </div>
     * </sg-modal>
     * <sg-button onclick="document.getElementById('myModal').showModal()">Open Modal</sg-button>
     * <script>
     *   document.getElementById('myModal').addEventListener('sgClose', (e) => {
     *     console.log('Modal closed with:', e.detail);
     *   });
     * </script>
     * <!-- ═══════════════════════════════════════════════════════════════════════════════
     *      ANGULAR
     *      ═══════════════════════════════════════════════════════════════════════════════ -->
     * <sg-modal
     *   #modal
     *   header="Edit Profile"
     *   [attr.open]="isOpen || null"
     *   (sgClose)="onClose($event)"
     *   (sgCancel)="onCancel()">
     *   <form>...</form>
     *   <div slot="footer">
     *     <sg-button (sgClick)="modal.close()">Cancel</sg-button>
     *     <sg-button variant="primary" (sgClick)="save()">Save</sg-button>
     *   </div>
     * </sg-modal>
     * <!-- ═══════════════════════════════════════════════════════════════════════════════
     *      REACT
     *      ═══════════════════════════════════════════════════════════════════════════════ -->
     * <sg-modal
     *   ref={modalRef}
     *   header="Delete Item"
     *   size="sm"
     *   onSgClose={(e) => handleClose(e.detail)}
     *   onSgCancel={() => handleCancel()}>
     *   <p>This action cannot be undone.</p>
     *   <div slot="footer">
     *     <sg-button onClick={() => modalRef.current.close()}>Cancel</sg-button>
     *     <sg-button variant="error" onClick={() => handleDelete()}>Delete</sg-button>
     *   </div>
     * </sg-modal>
     * @fires sgOpen - Emitted when the modal opens
     * @fires sgClose - Emitted when the modal closes, detail contains returnValue
     * @fires sgCancel - Emitted when user cancels (Escape or backdrop click)
     * @cssprop --sg-modal-width - Modal width (default: auto based on size)
     * @cssprop --sg-modal-max-width - Modal max width
     * @cssprop --sg-modal-max-height - Modal max height
     * @cssprop --sg-modal-padding - Modal content padding
     * @cssprop --sg-modal-radius - Modal border radius
     * @cssprop --sg-modal-backdrop-color - Backdrop overlay color
     * @cssprop --sg-modal-shadow - Modal box shadow
     */
    interface SgModal {
        /**
          * Whether the modal can be closed by clicking the backdrop
          * @default true
         */
        "closeOnBackdrop"?: boolean;
        /**
          * Whether the modal can be closed by pressing Escape
          * @default true
         */
        "closeOnEscape"?: boolean;
        /**
          * Modal header text
         */
        "header"?: string;
        /**
          * Whether the modal is a non-modal dialog (doesn't block interaction)
          * @default false
         */
        "nonModal"?: boolean;
        /**
          * Emitted when modal is cancelled (Escape or backdrop)
         */
        "onSgCancel"?: (event: SgModalCustomEvent<void>) => void;
        /**
          * Emitted when modal closes
         */
        "onSgClose"?: (event: SgModalCustomEvent<string>) => void;
        /**
          * Emitted when modal opens
         */
        "onSgOpen"?: (event: SgModalCustomEvent<void>) => void;
        /**
          * Whether the modal is open
          * @default false
         */
        "open"?: boolean;
        /**
          * Whether to show the backdrop overlay
          * @default true
         */
        "overlay"?: boolean;
        /**
          * Whether to show the close button in the header
          * @default true
         */
        "showCloseButton"?: boolean;
        /**
          * Modal size preset
          * @default 'md'
         */
        "size"?: ModalSize;
    }
    interface IntrinsicElements {
        "sg-modal": SgModal;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * @component sg-modal
             * @description A modern modal dialog component built on the native HTML <dialog> element.
             * Provides built-in accessibility, focus trapping, and backdrop handling.
             * @example <!-- ═══════════════════════════════════════════════════════════════════════════════
             *      VANILLA HTML / JS
             *      ═══════════════════════════════════════════════════════════════════════════════ -->
             * <sg-modal id="myModal" header="Confirm Action">
             *   <p>Are you sure you want to continue?</p>
             *   <div slot="footer">
             *     <sg-button variant="secondary" onclick="document.getElementById('myModal').close()">Cancel</sg-button>
             *     <sg-button variant="primary">Confirm</sg-button>
             *   </div>
             * </sg-modal>
             * <sg-button onclick="document.getElementById('myModal').showModal()">Open Modal</sg-button>
             * <script>
             *   document.getElementById('myModal').addEventListener('sgClose', (e) => {
             *     console.log('Modal closed with:', e.detail);
             *   });
             * </script>
             * <!-- ═══════════════════════════════════════════════════════════════════════════════
             *      ANGULAR
             *      ═══════════════════════════════════════════════════════════════════════════════ -->
             * <sg-modal
             *   #modal
             *   header="Edit Profile"
             *   [attr.open]="isOpen || null"
             *   (sgClose)="onClose($event)"
             *   (sgCancel)="onCancel()">
             *   <form>...</form>
             *   <div slot="footer">
             *     <sg-button (sgClick)="modal.close()">Cancel</sg-button>
             *     <sg-button variant="primary" (sgClick)="save()">Save</sg-button>
             *   </div>
             * </sg-modal>
             * <!-- ═══════════════════════════════════════════════════════════════════════════════
             *      REACT
             *      ═══════════════════════════════════════════════════════════════════════════════ -->
             * <sg-modal
             *   ref={modalRef}
             *   header="Delete Item"
             *   size="sm"
             *   onSgClose={(e) => handleClose(e.detail)}
             *   onSgCancel={() => handleCancel()}>
             *   <p>This action cannot be undone.</p>
             *   <div slot="footer">
             *     <sg-button onClick={() => modalRef.current.close()}>Cancel</sg-button>
             *     <sg-button variant="error" onClick={() => handleDelete()}>Delete</sg-button>
             *   </div>
             * </sg-modal>
             * @fires sgOpen - Emitted when the modal opens
             * @fires sgClose - Emitted when the modal closes, detail contains returnValue
             * @fires sgCancel - Emitted when user cancels (Escape or backdrop click)
             * @cssprop --sg-modal-width - Modal width (default: auto based on size)
             * @cssprop --sg-modal-max-width - Modal max width
             * @cssprop --sg-modal-max-height - Modal max height
             * @cssprop --sg-modal-padding - Modal content padding
             * @cssprop --sg-modal-radius - Modal border radius
             * @cssprop --sg-modal-backdrop-color - Backdrop overlay color
             * @cssprop --sg-modal-shadow - Modal box shadow
             */
            "sg-modal": LocalJSX.SgModal & JSXBase.HTMLAttributes<HTMLSgModalElement>;
        }
    }
}
