/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ButtonShape, ButtonSize, ButtonVariant } from "./components/button/button";
export { ButtonShape, ButtonSize, ButtonVariant } from "./components/button/button";
export namespace Components {
    /**
     * @component sg-button
     * @description A versatile button component with multiple variants, sizes, and states.
     * Framework-agnostic: works with Angular, React, Vue, and vanilla JS without wrappers.
     * @example <!-- ═══════════════════════════════════════════════════════════════════════════════
     *      VANILLA HTML / JS
     *      ═══════════════════════════════════════════════════════════════════════════════ -->
     * <sg-button>Click me</sg-button>
     * <sg-button variant="primary">Primary</sg-button>
     * <sg-button variant="outline" size="lg">Large Outline</sg-button>
     * <sg-button variant="success" leading-icon="check">Save</sg-button>
     * <sg-button loading>Loading...</sg-button>
     * <sg-button disabled>Disabled</sg-button>
     * <sg-button shape="pill" variant="secondary">Pill Button</sg-button>
     * <script>
     *   document.querySelector('sg-button').addEventListener('sgClick', (e) => {
     *     console.log('Button clicked!', e.detail);
     *   });
     * </script>
     * <!-- ═══════════════════════════════════════════════════════════════════════════════
     *      ANGULAR (no wrapper needed, add CUSTOM_ELEMENTS_SCHEMA)
     *      ═══════════════════════════════════════════════════════════════════════════════ -->
     * <sg-button
     *   variant="primary"
     *   [attr.loading]="isLoading || null"
     *   [attr.disabled]="isDisabled || null"
     *   (sgClick)="handleClick($event)">
     *   Save Changes
     * </sg-button>
     * <!-- ═══════════════════════════════════════════════════════════════════════════════
     *      REACT (use kebab-case attributes)
     *      ═══════════════════════════════════════════════════════════════════════════════ -->
     * <sg-button
     *   variant="primary"
     *   leading-icon="save"
     *   loading={isLoading}
     *   onSgClick={(e) => handleClick(e.detail)}>
     *   Save Changes
     * </sg-button>
     * @fires sgClick - Emitted when button is clicked (not disabled/loading)
     * @cssprop --sg-btn-bg - Button background color
     * @cssprop --sg-btn-color - Button text color
     * @cssprop --sg-btn-border-color - Button border color
     * @cssprop --sg-btn-radius - Button border radius
     * @cssprop --sg-btn-shadow - Button box shadow
     */
    interface SgButton {
        /**
          * Disable the button
          * @attr disabled
          * @default false
         */
        "disabled": boolean;
        /**
          * Accessible label
         */
        "label"?: string;
        /**
          * Leading icon name (from sg-icon)
          * @attr leading-icon
         */
        "leadingIcon"?: string;
        /**
          * Show loading spinner
          * @attr loading
          * @default false
         */
        "loading": boolean;
        /**
          * Loading text (replaces content while loading)
          * @attr loading-text
         */
        "loadingText"?: string;
        /**
          * Button shape
          * @attr shape
          * @default 'default'
         */
        "shape": ButtonShape;
        /**
          * Button size
          * @attr size
          * @default 'md'
         */
        "size": ButtonSize;
        /**
          * Trailing icon name (from sg-icon)
          * @attr trailing-icon
         */
        "trailingIcon"?: string;
        /**
          * Button type attribute
          * @attr type
          * @default 'button'
         */
        "type": 'button' | 'submit' | 'reset';
        /**
          * Button color variant
          * @attr variant
          * @default 'primary'
         */
        "variant": ButtonVariant;
    }
}
export interface SgButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSgButtonElement;
}
declare global {
    interface HTMLSgButtonElementEventMap {
        "sgClick": MouseEvent;
    }
    /**
     * @component sg-button
     * @description A versatile button component with multiple variants, sizes, and states.
     * Framework-agnostic: works with Angular, React, Vue, and vanilla JS without wrappers.
     * @example <!-- ═══════════════════════════════════════════════════════════════════════════════
     *      VANILLA HTML / JS
     *      ═══════════════════════════════════════════════════════════════════════════════ -->
     * <sg-button>Click me</sg-button>
     * <sg-button variant="primary">Primary</sg-button>
     * <sg-button variant="outline" size="lg">Large Outline</sg-button>
     * <sg-button variant="success" leading-icon="check">Save</sg-button>
     * <sg-button loading>Loading...</sg-button>
     * <sg-button disabled>Disabled</sg-button>
     * <sg-button shape="pill" variant="secondary">Pill Button</sg-button>
     * <script>
     *   document.querySelector('sg-button').addEventListener('sgClick', (e) => {
     *     console.log('Button clicked!', e.detail);
     *   });
     * </script>
     * <!-- ═══════════════════════════════════════════════════════════════════════════════
     *      ANGULAR (no wrapper needed, add CUSTOM_ELEMENTS_SCHEMA)
     *      ═══════════════════════════════════════════════════════════════════════════════ -->
     * <sg-button
     *   variant="primary"
     *   [attr.loading]="isLoading || null"
     *   [attr.disabled]="isDisabled || null"
     *   (sgClick)="handleClick($event)">
     *   Save Changes
     * </sg-button>
     * <!-- ═══════════════════════════════════════════════════════════════════════════════
     *      REACT (use kebab-case attributes)
     *      ═══════════════════════════════════════════════════════════════════════════════ -->
     * <sg-button
     *   variant="primary"
     *   leading-icon="save"
     *   loading={isLoading}
     *   onSgClick={(e) => handleClick(e.detail)}>
     *   Save Changes
     * </sg-button>
     * @fires sgClick - Emitted when button is clicked (not disabled/loading)
     * @cssprop --sg-btn-bg - Button background color
     * @cssprop --sg-btn-color - Button text color
     * @cssprop --sg-btn-border-color - Button border color
     * @cssprop --sg-btn-radius - Button border radius
     * @cssprop --sg-btn-shadow - Button box shadow
     */
    interface HTMLSgButtonElement extends Components.SgButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSgButtonElementEventMap>(type: K, listener: (this: HTMLSgButtonElement, ev: SgButtonCustomEvent<HTMLSgButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSgButtonElementEventMap>(type: K, listener: (this: HTMLSgButtonElement, ev: SgButtonCustomEvent<HTMLSgButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSgButtonElement: {
        prototype: HTMLSgButtonElement;
        new (): HTMLSgButtonElement;
    };
    interface HTMLElementTagNameMap {
        "sg-button": HTMLSgButtonElement;
    }
}
declare namespace LocalJSX {
    /**
     * @component sg-button
     * @description A versatile button component with multiple variants, sizes, and states.
     * Framework-agnostic: works with Angular, React, Vue, and vanilla JS without wrappers.
     * @example <!-- ═══════════════════════════════════════════════════════════════════════════════
     *      VANILLA HTML / JS
     *      ═══════════════════════════════════════════════════════════════════════════════ -->
     * <sg-button>Click me</sg-button>
     * <sg-button variant="primary">Primary</sg-button>
     * <sg-button variant="outline" size="lg">Large Outline</sg-button>
     * <sg-button variant="success" leading-icon="check">Save</sg-button>
     * <sg-button loading>Loading...</sg-button>
     * <sg-button disabled>Disabled</sg-button>
     * <sg-button shape="pill" variant="secondary">Pill Button</sg-button>
     * <script>
     *   document.querySelector('sg-button').addEventListener('sgClick', (e) => {
     *     console.log('Button clicked!', e.detail);
     *   });
     * </script>
     * <!-- ═══════════════════════════════════════════════════════════════════════════════
     *      ANGULAR (no wrapper needed, add CUSTOM_ELEMENTS_SCHEMA)
     *      ═══════════════════════════════════════════════════════════════════════════════ -->
     * <sg-button
     *   variant="primary"
     *   [attr.loading]="isLoading || null"
     *   [attr.disabled]="isDisabled || null"
     *   (sgClick)="handleClick($event)">
     *   Save Changes
     * </sg-button>
     * <!-- ═══════════════════════════════════════════════════════════════════════════════
     *      REACT (use kebab-case attributes)
     *      ═══════════════════════════════════════════════════════════════════════════════ -->
     * <sg-button
     *   variant="primary"
     *   leading-icon="save"
     *   loading={isLoading}
     *   onSgClick={(e) => handleClick(e.detail)}>
     *   Save Changes
     * </sg-button>
     * @fires sgClick - Emitted when button is clicked (not disabled/loading)
     * @cssprop --sg-btn-bg - Button background color
     * @cssprop --sg-btn-color - Button text color
     * @cssprop --sg-btn-border-color - Button border color
     * @cssprop --sg-btn-radius - Button border radius
     * @cssprop --sg-btn-shadow - Button box shadow
     */
    interface SgButton {
        /**
          * Disable the button
          * @attr disabled
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Accessible label
         */
        "label"?: string;
        /**
          * Leading icon name (from sg-icon)
          * @attr leading-icon
         */
        "leadingIcon"?: string;
        /**
          * Show loading spinner
          * @attr loading
          * @default false
         */
        "loading"?: boolean;
        /**
          * Loading text (replaces content while loading)
          * @attr loading-text
         */
        "loadingText"?: string;
        /**
          * Click event (emitted when not disabled/loading)
         */
        "onSgClick"?: (event: SgButtonCustomEvent<MouseEvent>) => void;
        /**
          * Button shape
          * @attr shape
          * @default 'default'
         */
        "shape"?: ButtonShape;
        /**
          * Button size
          * @attr size
          * @default 'md'
         */
        "size"?: ButtonSize;
        /**
          * Trailing icon name (from sg-icon)
          * @attr trailing-icon
         */
        "trailingIcon"?: string;
        /**
          * Button type attribute
          * @attr type
          * @default 'button'
         */
        "type"?: 'button' | 'submit' | 'reset';
        /**
          * Button color variant
          * @attr variant
          * @default 'primary'
         */
        "variant"?: ButtonVariant;
    }
    interface IntrinsicElements {
        "sg-button": SgButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * @component sg-button
             * @description A versatile button component with multiple variants, sizes, and states.
             * Framework-agnostic: works with Angular, React, Vue, and vanilla JS without wrappers.
             * @example <!-- ═══════════════════════════════════════════════════════════════════════════════
             *      VANILLA HTML / JS
             *      ═══════════════════════════════════════════════════════════════════════════════ -->
             * <sg-button>Click me</sg-button>
             * <sg-button variant="primary">Primary</sg-button>
             * <sg-button variant="outline" size="lg">Large Outline</sg-button>
             * <sg-button variant="success" leading-icon="check">Save</sg-button>
             * <sg-button loading>Loading...</sg-button>
             * <sg-button disabled>Disabled</sg-button>
             * <sg-button shape="pill" variant="secondary">Pill Button</sg-button>
             * <script>
             *   document.querySelector('sg-button').addEventListener('sgClick', (e) => {
             *     console.log('Button clicked!', e.detail);
             *   });
             * </script>
             * <!-- ═══════════════════════════════════════════════════════════════════════════════
             *      ANGULAR (no wrapper needed, add CUSTOM_ELEMENTS_SCHEMA)
             *      ═══════════════════════════════════════════════════════════════════════════════ -->
             * <sg-button
             *   variant="primary"
             *   [attr.loading]="isLoading || null"
             *   [attr.disabled]="isDisabled || null"
             *   (sgClick)="handleClick($event)">
             *   Save Changes
             * </sg-button>
             * <!-- ═══════════════════════════════════════════════════════════════════════════════
             *      REACT (use kebab-case attributes)
             *      ═══════════════════════════════════════════════════════════════════════════════ -->
             * <sg-button
             *   variant="primary"
             *   leading-icon="save"
             *   loading={isLoading}
             *   onSgClick={(e) => handleClick(e.detail)}>
             *   Save Changes
             * </sg-button>
             * @fires sgClick - Emitted when button is clicked (not disabled/loading)
             * @cssprop --sg-btn-bg - Button background color
             * @cssprop --sg-btn-color - Button text color
             * @cssprop --sg-btn-border-color - Button border color
             * @cssprop --sg-btn-radius - Button border radius
             * @cssprop --sg-btn-shadow - Button box shadow
             */
            "sg-button": LocalJSX.SgButton & JSXBase.HTMLAttributes<HTMLSgButtonElement>;
        }
    }
}
