/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ThemeMode } from "./components/theme-toggle/theme-toggle";
export { ThemeMode } from "./components/theme-toggle/theme-toggle";
export namespace Components {
    interface SgThemeToggle {
        /**
          * Size of the toggle button
          * @default 'md'
         */
        "size": 'sm' | 'md' | 'lg';
        /**
          * The current theme mode
          * @default 'system'
         */
        "theme": ThemeMode;
    }
}
export interface SgThemeToggleCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSgThemeToggleElement;
}
declare global {
    interface HTMLSgThemeToggleElementEventMap {
        "sgThemeChange": ThemeMode;
    }
    interface HTMLSgThemeToggleElement extends Components.SgThemeToggle, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSgThemeToggleElementEventMap>(type: K, listener: (this: HTMLSgThemeToggleElement, ev: SgThemeToggleCustomEvent<HTMLSgThemeToggleElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSgThemeToggleElementEventMap>(type: K, listener: (this: HTMLSgThemeToggleElement, ev: SgThemeToggleCustomEvent<HTMLSgThemeToggleElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSgThemeToggleElement: {
        prototype: HTMLSgThemeToggleElement;
        new (): HTMLSgThemeToggleElement;
    };
    interface HTMLElementTagNameMap {
        "sg-theme-toggle": HTMLSgThemeToggleElement;
    }
}
declare namespace LocalJSX {
    interface SgThemeToggle {
        /**
          * Emitted when the theme changes
         */
        "onSgThemeChange"?: (event: SgThemeToggleCustomEvent<ThemeMode>) => void;
        /**
          * Size of the toggle button
          * @default 'md'
         */
        "size"?: 'sm' | 'md' | 'lg';
        /**
          * The current theme mode
          * @default 'system'
         */
        "theme"?: ThemeMode;
    }
    interface IntrinsicElements {
        "sg-theme-toggle": SgThemeToggle;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "sg-theme-toggle": LocalJSX.SgThemeToggle & JSXBase.HTMLAttributes<HTMLSgThemeToggleElement>;
        }
    }
}
