/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import { EditorChangeEvent, EditorMode, EditorModeChangeEvent, MediaItem } from './components/article-editor/utils';
import { EditorTranslations, SupportedLocale } from './components/article-editor/utils/i18n';
import { IconName } from './components/svg-icon/icons';
export { EditorChangeEvent, EditorMode, EditorModeChangeEvent, MediaItem } from './components/article-editor/utils';
export { EditorTranslations, SupportedLocale } from './components/article-editor/utils/i18n';
export { IconName } from './components/svg-icon/icons';
export namespace Components {
  /**
   * SagedUI - Article Editor Component
   * A headless-ready article editor supporting HTML and Markdown modes
   * with live preview, formatting toolbar, and optional media library integration.
   * @example ```html
   * <sg-article-editor
   *   value="<p>Hello World</p>"
   *   mode="html"
   *   placeholder="Start writing..."
   * ></sg-article-editor>
   * ```
   */
  interface SgArticleEditor {
    /**
     * Available modes (comma-separated or array)
     * @default 'html,markdown,preview,split'
     */
    availableModes: string;
    /**
     * Custom translations to override defaults
     */
    customTranslations: Partial<EditorTranslations>;
    /**
     * Disabled state
     * @default false
     */
    disabled: boolean;
    /**
     * Custom accent color (buttons, links)
     */
    editorAccent: string;
    /**
     * Custom background color for the editor
     */
    editorBg: string;
    /**
     * Custom secondary background color
     */
    editorBgSecondary: string;
    /**
     * Custom tertiary background color
     */
    editorBgTertiary: string;
    /**
     * Custom border color
     */
    editorBorder: string;
    /**
     * Custom border radius
     */
    editorBorderRadius: string;
    /**
     * Custom font family for code
     */
    editorFontMono: string;
    /**
     * Custom font family for text
     */
    editorFontSans: string;
    /**
     * Custom font size
     */
    editorFontSize: string;
    /**
     * Custom text color
     */
    editorText: string;
    /**
     * Custom secondary text color
     */
    editorTextSecondary: string;
    /**
     * Enable external preview window
     * @default true
     */
    enableExternalPreview: boolean;
    /**
     * Focus the editor
     */
    focusEditor: () => Promise<void>;
    /**
     * Get the current content
     */
    getContent: () => Promise<string>;
    /**
     * Get content as HTML (converts if in markdown mode)
     */
    getHtml: () => Promise<string>;
    /**
     * Insert content at cursor position
     */
    insertAtCursor: (content: string) => Promise<void>;
    /**
     * Insert a media item
     */
    insertMedia: (media: MediaItem) => Promise<void>;
    /**
     * Locale for UI text (en, es, fr, de, pt, it, zh, ja, ko, ar)
     * @default 'en'
     */
    locale: SupportedLocale;
    /**
     * Minimum height in pixels
     * @default 400
     */
    minHeight: number;
    /**
     * Current editor mode
     * @default 'html'
     */
    mode: EditorMode;
    /**
     * Placeholder text when editor is empty
     * @default 'Start writing...'
     */
    placeholder: string;
    /**
     * Read-only state
     * @default false
     */
    readonly: boolean;
    /**
     * Set the content programmatically
     */
    setContent: (content: string) => Promise<void>;
    /**
     * Show word/character count
     * @default true
     */
    showWordCount: boolean;
    /**
     * Enable spell checking
     * @default true
     */
    spellcheck: boolean;
    /**
     * The content value of the editor
     * @default ''
     */
    value: string;
  }
  /**
   * @component sg-icon
   * @description SVG Icon component for SagedUI - A flexible, accessible icon system
   * @example <!-- Basic usage with built-in icons -->
   * <sg-icon name="home"></sg-icon>
   * <!-- With custom size -->
   * <sg-icon name="settings" size="32"></sg-icon>
   * <!-- With custom color -->
   * <sg-icon name="heart" color="#ff0000"></sg-icon>
   * <!-- Custom icon via src (fetches SVG file) -->
   * <sg-icon src="/assets/custom-icon.svg"></sg-icon>
   */
  interface SgIcon {
    /**
     * Accessible label for screen readers
     */
    ariaLabel?: string;
    /**
     * Color of the icon (CSS color value)
     * @default 'currentColor'
     */
    color: string;
    /**
     * Whether the icon is decorative (hidden from screen readers)
     * @default false
     */
    decorative: boolean;
    /**
     * Flip the icon horizontally
     * @default false
     */
    flipH: boolean;
    /**
     * Flip the icon vertically
     * @default false
     */
    flipV: boolean;
    /**
     * Height of the icon (overrides size)
     */
    height?: number | string;
    /**
     * The name of the icon from the built-in library
     */
    name?: IconName;
    /**
     * Rotation angle in degrees
     */
    rotate?: number;
    /**
     * Size of the icon in pixels
     * @default 24
     */
    size: number | string;
    /**
     * Whether the icon should spin (useful for loading icons)
     * @default false
     */
    spin: boolean;
    /**
     * URL to a custom SVG icon (alternative to name)
     */
    src?: string;
    /**
     * Stroke width for outline icons
     */
    strokeWidth?: number;
    /**
     * Width of the icon (overrides size)
     */
    width?: number | string;
  }
  /**
   * @component sg-skeleton
   * @description Skeleton loading placeholder component for SagedUI
   * @example <sg-skeleton variant="text" width="200px" height="1rem"></sg-skeleton>
   * <sg-skeleton variant="rect" width="100%" height="200px"></sg-skeleton>
   * <sg-skeleton variant="circle" width="48px" height="48px"></sg-skeleton>
   */
  interface SgSkeleton {
    /**
     * Animation type - shimmer: Gradient animation (default) - pulse: Opacity pulse animation - none: No animation
     * @default 'shimmer'
     */
    animation: 'shimmer' | 'pulse' | 'none';
    /**
     * The height of the skeleton
     * @default '1rem'
     */
    height: string;
    /**
     * The shape variant of the skeleton - text: Slightly rounded, good for text placeholders - rect: More rounded, good for cards/images - circle: Fully rounded, good for avatars
     * @default 'text'
     */
    variant: 'text' | 'rect' | 'circle';
    /**
     * The width of the skeleton
     * @default '100%'
     */
    width: string;
  }
}
export interface SgArticleEditorCustomEvent<T> extends CustomEvent<T> {
  detail: T;
  target: HTMLSgArticleEditorElement;
}
declare global {
  interface HTMLSgArticleEditorElementEventMap {
    editorChange: EditorChangeEvent;
    editorModeChange: EditorModeChangeEvent;
    mediaLibraryOpen: void;
    mediaInsert: MediaItem;
  }
  /**
   * SagedUI - Article Editor Component
   * A headless-ready article editor supporting HTML and Markdown modes
   * with live preview, formatting toolbar, and optional media library integration.
   * @example ```html
   * <sg-article-editor
   *   value="<p>Hello World</p>"
   *   mode="html"
   *   placeholder="Start writing..."
   * ></sg-article-editor>
   * ```
   */
  interface HTMLSgArticleEditorElement extends Components.SgArticleEditor, HTMLStencilElement {
    addEventListener<K extends keyof HTMLSgArticleEditorElementEventMap>(
      type: K,
      listener: (this: HTMLSgArticleEditorElement, ev: SgArticleEditorCustomEvent<HTMLSgArticleEditorElementEventMap[K]>) => any,
      options?: boolean | AddEventListenerOptions,
    ): void;
    addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
    addEventListener<K extends keyof HTMLElementEventMap>(
      type: K,
      listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any,
      options?: boolean | AddEventListenerOptions,
    ): void;
    addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
    removeEventListener<K extends keyof HTMLSgArticleEditorElementEventMap>(
      type: K,
      listener: (this: HTMLSgArticleEditorElement, ev: SgArticleEditorCustomEvent<HTMLSgArticleEditorElementEventMap[K]>) => any,
      options?: boolean | EventListenerOptions,
    ): void;
    removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
    removeEventListener<K extends keyof HTMLElementEventMap>(
      type: K,
      listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any,
      options?: boolean | EventListenerOptions,
    ): void;
    removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
  }
  var HTMLSgArticleEditorElement: {
    prototype: HTMLSgArticleEditorElement;
    new (): HTMLSgArticleEditorElement;
  };
  /**
   * @component sg-icon
   * @description SVG Icon component for SagedUI - A flexible, accessible icon system
   * @example <!-- Basic usage with built-in icons -->
   * <sg-icon name="home"></sg-icon>
   * <!-- With custom size -->
   * <sg-icon name="settings" size="32"></sg-icon>
   * <!-- With custom color -->
   * <sg-icon name="heart" color="#ff0000"></sg-icon>
   * <!-- Custom icon via src (fetches SVG file) -->
   * <sg-icon src="/assets/custom-icon.svg"></sg-icon>
   */
  interface HTMLSgIconElement extends Components.SgIcon, HTMLStencilElement {}
  var HTMLSgIconElement: {
    prototype: HTMLSgIconElement;
    new (): HTMLSgIconElement;
  };
  /**
   * @component sg-skeleton
   * @description Skeleton loading placeholder component for SagedUI
   * @example <sg-skeleton variant="text" width="200px" height="1rem"></sg-skeleton>
   * <sg-skeleton variant="rect" width="100%" height="200px"></sg-skeleton>
   * <sg-skeleton variant="circle" width="48px" height="48px"></sg-skeleton>
   */
  interface HTMLSgSkeletonElement extends Components.SgSkeleton, HTMLStencilElement {}
  var HTMLSgSkeletonElement: {
    prototype: HTMLSgSkeletonElement;
    new (): HTMLSgSkeletonElement;
  };
  interface HTMLElementTagNameMap {
    'sg-article-editor': HTMLSgArticleEditorElement;
    'sg-icon': HTMLSgIconElement;
    'sg-skeleton': HTMLSgSkeletonElement;
  }
}
declare namespace LocalJSX {
  /**
   * SagedUI - Article Editor Component
   * A headless-ready article editor supporting HTML and Markdown modes
   * with live preview, formatting toolbar, and optional media library integration.
   * @example ```html
   * <sg-article-editor
   *   value="<p>Hello World</p>"
   *   mode="html"
   *   placeholder="Start writing..."
   * ></sg-article-editor>
   * ```
   */
  interface SgArticleEditor {
    /**
     * Available modes (comma-separated or array)
     * @default 'html,markdown,preview,split'
     */
    availableModes?: string;
    /**
     * Custom translations to override defaults
     */
    customTranslations?: Partial<EditorTranslations>;
    /**
     * Disabled state
     * @default false
     */
    disabled?: boolean;
    /**
     * Custom accent color (buttons, links)
     */
    editorAccent?: string;
    /**
     * Custom background color for the editor
     */
    editorBg?: string;
    /**
     * Custom secondary background color
     */
    editorBgSecondary?: string;
    /**
     * Custom tertiary background color
     */
    editorBgTertiary?: string;
    /**
     * Custom border color
     */
    editorBorder?: string;
    /**
     * Custom border radius
     */
    editorBorderRadius?: string;
    /**
     * Custom font family for code
     */
    editorFontMono?: string;
    /**
     * Custom font family for text
     */
    editorFontSans?: string;
    /**
     * Custom font size
     */
    editorFontSize?: string;
    /**
     * Custom text color
     */
    editorText?: string;
    /**
     * Custom secondary text color
     */
    editorTextSecondary?: string;
    /**
     * Enable external preview window
     * @default true
     */
    enableExternalPreview?: boolean;
    /**
     * Locale for UI text (en, es, fr, de, pt, it, zh, ja, ko, ar)
     * @default 'en'
     */
    locale?: SupportedLocale;
    /**
     * Minimum height in pixels
     * @default 400
     */
    minHeight?: number;
    /**
     * Current editor mode
     * @default 'html'
     */
    mode?: EditorMode;
    /**
     * Emitted when the content changes
     */
    onEditorChange?: (event: SgArticleEditorCustomEvent<EditorChangeEvent>) => void;
    /**
     * Emitted when the mode changes
     */
    onEditorModeChange?: (event: SgArticleEditorCustomEvent<EditorModeChangeEvent>) => void;
    /**
     * Emitted when a media item should be inserted
     */
    onMediaInsert?: (event: SgArticleEditorCustomEvent<MediaItem>) => void;
    /**
     * Emitted when media library is requested
     */
    onMediaLibraryOpen?: (event: SgArticleEditorCustomEvent<void>) => void;
    /**
     * Placeholder text when editor is empty
     * @default 'Start writing...'
     */
    placeholder?: string;
    /**
     * Read-only state
     * @default false
     */
    readonly?: boolean;
    /**
     * Show word/character count
     * @default true
     */
    showWordCount?: boolean;
    /**
     * Enable spell checking
     * @default true
     */
    spellcheck?: boolean;
    /**
     * The content value of the editor
     * @default ''
     */
    value?: string;
  }
  /**
   * @component sg-icon
   * @description SVG Icon component for SagedUI - A flexible, accessible icon system
   * @example <!-- Basic usage with built-in icons -->
   * <sg-icon name="home"></sg-icon>
   * <!-- With custom size -->
   * <sg-icon name="settings" size="32"></sg-icon>
   * <!-- With custom color -->
   * <sg-icon name="heart" color="#ff0000"></sg-icon>
   * <!-- Custom icon via src (fetches SVG file) -->
   * <sg-icon src="/assets/custom-icon.svg"></sg-icon>
   */
  interface SgIcon {
    /**
     * Accessible label for screen readers
     */
    ariaLabel?: string;
    /**
     * Color of the icon (CSS color value)
     * @default 'currentColor'
     */
    color?: string;
    /**
     * Whether the icon is decorative (hidden from screen readers)
     * @default false
     */
    decorative?: boolean;
    /**
     * Flip the icon horizontally
     * @default false
     */
    flipH?: boolean;
    /**
     * Flip the icon vertically
     * @default false
     */
    flipV?: boolean;
    /**
     * Height of the icon (overrides size)
     */
    height?: number | string;
    /**
     * The name of the icon from the built-in library
     */
    name?: IconName;
    /**
     * Rotation angle in degrees
     */
    rotate?: number;
    /**
     * Size of the icon in pixels
     * @default 24
     */
    size?: number | string;
    /**
     * Whether the icon should spin (useful for loading icons)
     * @default false
     */
    spin?: boolean;
    /**
     * URL to a custom SVG icon (alternative to name)
     */
    src?: string;
    /**
     * Stroke width for outline icons
     */
    strokeWidth?: number;
    /**
     * Width of the icon (overrides size)
     */
    width?: number | string;
  }
  /**
   * @component sg-skeleton
   * @description Skeleton loading placeholder component for SagedUI
   * @example <sg-skeleton variant="text" width="200px" height="1rem"></sg-skeleton>
   * <sg-skeleton variant="rect" width="100%" height="200px"></sg-skeleton>
   * <sg-skeleton variant="circle" width="48px" height="48px"></sg-skeleton>
   */
  interface SgSkeleton {
    /**
     * Animation type - shimmer: Gradient animation (default) - pulse: Opacity pulse animation - none: No animation
     * @default 'shimmer'
     */
    animation?: 'shimmer' | 'pulse' | 'none';
    /**
     * The height of the skeleton
     * @default '1rem'
     */
    height?: string;
    /**
     * The shape variant of the skeleton - text: Slightly rounded, good for text placeholders - rect: More rounded, good for cards/images - circle: Fully rounded, good for avatars
     * @default 'text'
     */
    variant?: 'text' | 'rect' | 'circle';
    /**
     * The width of the skeleton
     * @default '100%'
     */
    width?: string;
  }
  interface IntrinsicElements {
    'sg-article-editor': SgArticleEditor;
    'sg-icon': SgIcon;
    'sg-skeleton': SgSkeleton;
  }
}
export { LocalJSX as JSX };
declare module '@stencil/core' {
  export namespace JSX {
    interface IntrinsicElements {
      /**
       * SagedUI - Article Editor Component
       * A headless-ready article editor supporting HTML and Markdown modes
       * with live preview, formatting toolbar, and optional media library integration.
       * @example ```html
       * <sg-article-editor
       *   value="<p>Hello World</p>"
       *   mode="html"
       *   placeholder="Start writing..."
       * ></sg-article-editor>
       * ```
       */
      'sg-article-editor': LocalJSX.SgArticleEditor & JSXBase.HTMLAttributes<HTMLSgArticleEditorElement>;
      /**
       * @component sg-icon
       * @description SVG Icon component for SagedUI - A flexible, accessible icon system
       * @example <!-- Basic usage with built-in icons -->
       * <sg-icon name="home"></sg-icon>
       * <!-- With custom size -->
       * <sg-icon name="settings" size="32"></sg-icon>
       * <!-- With custom color -->
       * <sg-icon name="heart" color="#ff0000"></sg-icon>
       * <!-- Custom icon via src (fetches SVG file) -->
       * <sg-icon src="/assets/custom-icon.svg"></sg-icon>
       */
      'sg-icon': LocalJSX.SgIcon & JSXBase.HTMLAttributes<HTMLSgIconElement>;
      /**
       * @component sg-skeleton
       * @description Skeleton loading placeholder component for SagedUI
       * @example <sg-skeleton variant="text" width="200px" height="1rem"></sg-skeleton>
       * <sg-skeleton variant="rect" width="100%" height="200px"></sg-skeleton>
       * <sg-skeleton variant="circle" width="48px" height="48px"></sg-skeleton>
       */
      'sg-skeleton': LocalJSX.SgSkeleton & JSXBase.HTMLAttributes<HTMLSgSkeletonElement>;
    }
  }
}
