/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { EditorChangeEvent, EditorMode, EditorModeChangeEvent, MediaItem } from "./components/article-editor/utils";
import { EditorTranslations, SupportedLocale } from "./components/article-editor/utils/i18n";
import { BadgeSize, BadgeVariant } from "./components/badge/badge";
import { ButtonShape, ButtonSize, ButtonVariant } from "./components/button/button";
export { EditorChangeEvent, EditorMode, EditorModeChangeEvent, MediaItem } from "./components/article-editor/utils";
export { EditorTranslations, SupportedLocale } from "./components/article-editor/utils/i18n";
export { BadgeSize, BadgeVariant } from "./components/badge/badge";
export { ButtonShape, ButtonSize, ButtonVariant } from "./components/button/button";
export namespace Components {
    /**
     * SagedUI - Article Editor Component
     * A headless-ready article editor supporting HTML and Markdown modes
     * with live preview, formatting toolbar, and optional media library integration.
     * @example ```html
     * <sg-article-editor
     *   value="<p>Hello World</p>"
     *   mode="html"
     *   placeholder="Start writing..."
     * ></sg-article-editor>
     * ```
     */
    interface SgArticleEditor {
        /**
          * Available modes (comma-separated or array)
          * @default 'html,markdown,preview,split'
         */
        "availableModes": string;
        /**
          * Custom translations to override defaults
         */
        "customTranslations": Partial<EditorTranslations>;
        /**
          * Disabled state
          * @default false
         */
        "disabled": boolean;
        /**
          * Custom accent color (buttons, links)
         */
        "editorAccent": string;
        /**
          * Custom background color for the editor
         */
        "editorBg": string;
        /**
          * Custom secondary background color
         */
        "editorBgSecondary": string;
        /**
          * Custom tertiary background color
         */
        "editorBgTertiary": string;
        /**
          * Custom border color
         */
        "editorBorder": string;
        /**
          * Custom border radius
         */
        "editorBorderRadius": string;
        /**
          * Custom font family for code
         */
        "editorFontMono": string;
        /**
          * Custom font family for text
         */
        "editorFontSans": string;
        /**
          * Custom font size
         */
        "editorFontSize": string;
        /**
          * Custom text color
         */
        "editorText": string;
        /**
          * Custom secondary text color
         */
        "editorTextSecondary": string;
        /**
          * Enable external preview window
          * @default true
         */
        "enableExternalPreview": boolean;
        /**
          * Focus the editor
         */
        "focusEditor": () => Promise<void>;
        /**
          * Get the current content
         */
        "getContent": () => Promise<string>;
        /**
          * Get content as HTML (converts if in markdown mode)
         */
        "getHtml": () => Promise<string>;
        /**
          * Insert content at cursor position
         */
        "insertAtCursor": (content: string) => Promise<void>;
        /**
          * Insert a media item
         */
        "insertMedia": (media: MediaItem) => Promise<void>;
        /**
          * Locale for UI text (en, es, fr, de, pt, it, zh, ja, ko, ar)
          * @default 'en'
         */
        "locale": SupportedLocale;
        /**
          * Minimum height in pixels
          * @default 400
         */
        "minHeight": number;
        /**
          * Current editor mode
          * @default 'html'
         */
        "mode": EditorMode;
        /**
          * Placeholder text when editor is empty
          * @default 'Start writing...'
         */
        "placeholder": string;
        /**
          * Read-only state
          * @default false
         */
        "readonly": boolean;
        /**
          * Set the content programmatically
         */
        "setContent": (content: string) => Promise<void>;
        /**
          * Show word/character count
          * @default true
         */
        "showWordCount": boolean;
        /**
          * Enable spell checking
          * @default true
         */
        "spellcheck": boolean;
        /**
          * The content value of the editor
          * @default ''
         */
        "value": string;
    }
    /**
     * @example ### Angular
     * ```html
     * <sg-badge variant="success">Active</sg-badge>
     * <sg-badge variant="error" size="sm" dot>Offline</sg-badge>
     * <sg-badge variant="info" pill>New Feature</sg-badge>
     * <sg-badge variant="warning">
     *   <sg-icon slot="icon" name="alert-triangle" size="12"></sg-icon>
     *   Warning
     * </sg-badge>
     * ```
     * ### React
     * ```jsx
     * <sg-badge variant="primary" outlined>Beta</sg-badge>
     * <sg-badge variant="success" pulse>Live</sg-badge>
     * ```
     * ### Vanilla JS
     * ```html
     * <sg-badge variant="info" size="lg">Featured</sg-badge>
     * <sg-badge variant="neutral" removable id="tag1">Tag 1</sg-badge>
     * <script>
     *   document.querySelector('#tag1').addEventListener('sgRemove', (e) => {
     *     e.target.remove();
     *   });
     * </script>
     * ```
     */
    interface SgBadge {
        /**
          * Make the badge clickable/interactive
          * @default false
         */
        "clickable": boolean;
        /**
          * Show a status dot indicator
          * @default false
         */
        "dot": boolean;
        /**
          * Custom icon name (if using sg-icon internally)
         */
        "icon": string;
        /**
          * Display as outlined style (transparent background with border)
          * @default false
         */
        "outlined": boolean;
        /**
          * Display as pill shape (fully rounded)
          * @default false
         */
        "pill": boolean;
        /**
          * Apply pulse animation to the dot
          * @default false
         */
        "pulse": boolean;
        /**
          * Size of the badge
          * @default 'md'
         */
        "size": BadgeSize;
        /**
          * Size of the badge
         */
        "size"?: "xs" | "sm" | "md" | "lg";
        /**
          * Display as soft/subtle style (lighter background)
          * @default false
         */
        "soft": boolean;
        /**
          * Color variant of the badge
          * @default 'primary'
         */
        "variant": BadgeVariant;
        /**
          * Color variant
         */
        "variant"?: "primary" | "secondary" | "success" | "warning" | "error" | "info" | "neutral" | "purple" | "cyan";
    }
    /**
     * @component sg-button
     * @description A versatile button component with multiple variants, sizes, and states.
     * Framework-agnostic: works with Angular, React, Vue, and vanilla JS without wrappers.
     * @example <!-- ═══════════════════════════════════════════════════════════════════════════════
     *      VANILLA HTML / JS
     *      ═══════════════════════════════════════════════════════════════════════════════ -->
     * <sg-button>Click me</sg-button>
     * <sg-button variant="primary">Primary</sg-button>
     * <sg-button variant="outline" size="lg">Large Outline</sg-button>
     * <sg-button variant="success" leading-icon="check">Save</sg-button>
     * <sg-button loading>Loading...</sg-button>
     * <sg-button disabled>Disabled</sg-button>
     * <sg-button shape="pill" variant="secondary">Pill Button</sg-button>
     * <script>
     *   document.querySelector('sg-button').addEventListener('sgClick', (e) => {
     *     console.log('Button clicked!', e.detail);
     *   });
     * </script>
     * <!-- ═══════════════════════════════════════════════════════════════════════════════
     *      ANGULAR (no wrapper needed, add CUSTOM_ELEMENTS_SCHEMA)
     *      ═══════════════════════════════════════════════════════════════════════════════ -->
     * <sg-button
     *   variant="primary"
     *   [attr.loading]="isLoading || null"
     *   [attr.disabled]="isDisabled || null"
     *   (sgClick)="handleClick($event)">
     *   Save Changes
     * </sg-button>
     * <!-- ═══════════════════════════════════════════════════════════════════════════════
     *      REACT (use kebab-case attributes)
     *      ═══════════════════════════════════════════════════════════════════════════════ -->
     * <sg-button
     *   variant="primary"
     *   leading-icon="save"
     *   loading={isLoading}
     *   onSgClick={(e) => handleClick(e.detail)}>
     *   Save Changes
     * </sg-button>
     * @fires sgClick - Emitted when button is clicked (not disabled/loading)
     * @cssprop --sg-btn-bg - Button background color
     * @cssprop --sg-btn-color - Button text color
     * @cssprop --sg-btn-border-color - Button border color
     * @cssprop --sg-btn-radius - Button border radius
     * @cssprop --sg-btn-shadow - Button box shadow
     */
    interface SgButton {
        /**
          * Accessible label
          * @attr aria-label
         */
        "ariaLabel"?: string;
        /**
          * Disable the button
          * @attr disabled
          * @default false
         */
        "disabled": boolean;
        /**
          * Leading icon name (from sg-icon)
          * @attr leading-icon
         */
        "leadingIcon"?: string;
        /**
          * Show loading spinner
          * @attr loading
          * @default false
         */
        "loading": boolean;
        /**
          * Loading text (replaces content while loading)
          * @attr loading-text
         */
        "loadingText"?: string;
        /**
          * Button shape
          * @attr shape
          * @default 'default'
         */
        "shape": ButtonShape;
        /**
          * Button size
          * @attr size
          * @default 'md'
         */
        "size": ButtonSize;
        /**
          * Trailing icon name (from sg-icon)
          * @attr trailing-icon
         */
        "trailingIcon"?: string;
        /**
          * Button type attribute
          * @attr type
          * @default 'button'
         */
        "type": 'button' | 'submit' | 'reset';
        /**
          * Button color variant
          * @attr variant
          * @default 'primary'
         */
        "variant": ButtonVariant;
    }
    /**
     * @example ### Angular
     * ```html
     * <sg-dropdown align="start" position="bottom">
     *   <button slot="trigger">Open Menu</button>
     *   <div slot="header">Settings</div>
     *   <button>Option 1</button>
     *   <button>Option 2</button>
     *   <div slot="footer">Logged in as Admin</div>
     * </sg-dropdown>
     * ```
     * ### React
     * ```jsx
     * <sg-dropdown align="start" closeOnSelect={false}>
     *   <button slot="trigger">Menu</button>
     *   <div>Content here</div>
     * </sg-dropdown>
     * ```
     * ### Vanilla JS
     * ```html
     * <sg-dropdown id="myDropdown" align="end" close-on-select="false">
     *   <button slot="trigger">Options</button>
     *   <ul>
     *     <li>Item 1</li>
     *     <li>Item 2</li>
     *   </ul>
     * </sg-dropdown>
     * <script>
     *   const dropdown = document.querySelector('#myDropdown');
     *   dropdown.addEventListener('sgOpen', (e) => console.log('Opened'));
     *   dropdown.addEventListener('sgClose', (e) => console.log('Closed'));
     * </script>
     * ```
     */
    interface SgDropdown {
        /**
          * Horizontal alignment of the dropdown content relative to trigger
          * @default 'start'
         */
        "align": 'start' | 'end' | 'center';
        /**
          * Horizontal alignment of the dropdown
         */
        "align"?: "start" | "end" | "center";
        /**
          * Closes the dropdown programmatically
         */
        "closeDropdown": () => Promise<void>;
        /**
          * Whether to close the dropdown when an item is selected/clicked
          * @default true
         */
        "closeOnSelect": boolean;
        /**
          * Whether the dropdown is disabled
          * @default false
         */
        "disabled": boolean;
        /**
          * Maximum height of the dropdown content for scrolling
          * @default '320px'
         */
        "maxHeight": string;
        /**
          * Minimum width of the dropdown content (e.g., "200px", "12rem")
          * @default '200px'
         */
        "minWidth": string;
        /**
          * Whether the dropdown is currently open
          * @default false
         */
        "open": boolean;
        /**
          * Opens the dropdown programmatically
         */
        "openDropdown": () => Promise<void>;
        /**
          * Vertical position of the dropdown content
          * @default 'bottom'
         */
        "position": 'bottom' | 'top';
        /**
          * Position of the dropdown relative to trigger
         */
        "position"?: "bottom" | "top";
        /**
          * Show a backdrop overlay (useful on mobile)
          * @default false
         */
        "showBackdrop": boolean;
        /**
          * Size variant
          * @default 'md'
         */
        "size": 'sm' | 'md' | 'lg';
        /**
          * Toggles the dropdown open/closed
         */
        "toggle": () => Promise<void>;
    }
    /**
     * @component sg-icon
     * @description SVG Icon component for SagedUI - A flexible, accessible icon system
     * @example <!-- Basic usage with built-in icons -->
     * <sg-icon name="home"></sg-icon>
     * <sg-icon name="icon-home"></sg-icon>
     * <!-- With custom size -->
     * <sg-icon name="settings" size="32"></sg-icon>
     * <!-- With custom color (fill is an alias for color) -->
     * <sg-icon name="heart" color="#ff0000"></sg-icon>
     * <sg-icon name="heart" fill="#ff0000"></sg-icon>
     * <!-- Custom icon via src (fetches SVG file) -->
     * <sg-icon src="/assets/custom-icon.svg"></sg-icon>
     */
    interface SgIcon {
        /**
          * Accessible label for screen readers
         */
        "ariaLabel"?: string;
        /**
          * Color of the icon (CSS color value)
          * @default 'currentColor'
         */
        "color": string;
        /**
          * Whether the icon is decorative (hidden from screen readers)
          * @default false
         */
        "decorative": boolean;
        /**
          * Alias for color (for compatibility with legacy svg-icon components)
          * @default undefined
         */
        "fill"?: string;
        /**
          * Flip the icon horizontally
          * @default false
         */
        "flipH": boolean;
        /**
          * Flip the icon vertically
          * @default false
         */
        "flipV": boolean;
        /**
          * Height of the icon (overrides size)
         */
        "height"?: number | string;
        /**
          * The name of the icon from the built-in library. Supports both 'name' and 'icon-name' formats for compatibility.
         */
        "name"?: string;
        /**
          * Rotation angle in degrees
         */
        "rotate"?: number;
        /**
          * Size of the icon in pixels
          * @default 24
         */
        "size": number | string;
        /**
          * Whether the icon should spin (useful for loading icons)
          * @default false
         */
        "spin": boolean;
        /**
          * URL to a custom SVG icon (alternative to name)
         */
        "src"?: string;
        /**
          * Stroke width for outline icons
         */
        "strokeWidth"?: number;
        /**
          * Width of the icon (overrides size)
         */
        "width"?: number | string;
    }
    /**
     * @component sg-skeleton
     * @description Skeleton loading placeholder component for SagedUI
     * @example <sg-skeleton variant="text" width="200px" height="1rem"></sg-skeleton>
     * <sg-skeleton variant="rect" width="100%" height="200px"></sg-skeleton>
     * <sg-skeleton variant="circle" width="48px" height="48px"></sg-skeleton>
     */
    interface SgSkeleton {
        /**
          * Animation type - shimmer: Gradient animation (default) - pulse: Opacity pulse animation - none: No animation
          * @default 'shimmer'
         */
        "animation": 'shimmer' | 'pulse' | 'none';
        /**
          * The height of the skeleton
          * @default '1rem'
         */
        "height": string;
        /**
          * The shape variant of the skeleton - text: Slightly rounded, good for text placeholders - rect: More rounded, good for cards/images - circle: Fully rounded, good for avatars
          * @default 'text'
         */
        "variant": 'text' | 'rect' | 'circle';
        /**
          * The width of the skeleton
          * @default '100%'
         */
        "width": string;
    }
}
export interface SgArticleEditorCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSgArticleEditorElement;
}
export interface SgButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSgButtonElement;
}
export interface SgDropdownCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSgDropdownElement;
}
declare global {
    interface HTMLSgArticleEditorElementEventMap {
        "editorChange": EditorChangeEvent;
        "editorModeChange": EditorModeChangeEvent;
        "mediaLibraryOpen": void;
        "mediaInsert": MediaItem;
    }
    /**
     * SagedUI - Article Editor Component
     * A headless-ready article editor supporting HTML and Markdown modes
     * with live preview, formatting toolbar, and optional media library integration.
     * @example ```html
     * <sg-article-editor
     *   value="<p>Hello World</p>"
     *   mode="html"
     *   placeholder="Start writing..."
     * ></sg-article-editor>
     * ```
     */
    interface HTMLSgArticleEditorElement extends Components.SgArticleEditor, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSgArticleEditorElementEventMap>(type: K, listener: (this: HTMLSgArticleEditorElement, ev: SgArticleEditorCustomEvent<HTMLSgArticleEditorElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSgArticleEditorElementEventMap>(type: K, listener: (this: HTMLSgArticleEditorElement, ev: SgArticleEditorCustomEvent<HTMLSgArticleEditorElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSgArticleEditorElement: {
        prototype: HTMLSgArticleEditorElement;
        new (): HTMLSgArticleEditorElement;
    };
    /**
     * @example ### Angular
     * ```html
     * <sg-badge variant="success">Active</sg-badge>
     * <sg-badge variant="error" size="sm" dot>Offline</sg-badge>
     * <sg-badge variant="info" pill>New Feature</sg-badge>
     * <sg-badge variant="warning">
     *   <sg-icon slot="icon" name="alert-triangle" size="12"></sg-icon>
     *   Warning
     * </sg-badge>
     * ```
     * ### React
     * ```jsx
     * <sg-badge variant="primary" outlined>Beta</sg-badge>
     * <sg-badge variant="success" pulse>Live</sg-badge>
     * ```
     * ### Vanilla JS
     * ```html
     * <sg-badge variant="info" size="lg">Featured</sg-badge>
     * <sg-badge variant="neutral" removable id="tag1">Tag 1</sg-badge>
     * <script>
     *   document.querySelector('#tag1').addEventListener('sgRemove', (e) => {
     *     e.target.remove();
     *   });
     * </script>
     * ```
     */
    interface HTMLSgBadgeElement extends Components.SgBadge, HTMLStencilElement {
    }
    var HTMLSgBadgeElement: {
        prototype: HTMLSgBadgeElement;
        new (): HTMLSgBadgeElement;
    };
    interface HTMLSgButtonElementEventMap {
        "sgClick": MouseEvent;
    }
    /**
     * @component sg-button
     * @description A versatile button component with multiple variants, sizes, and states.
     * Framework-agnostic: works with Angular, React, Vue, and vanilla JS without wrappers.
     * @example <!-- ═══════════════════════════════════════════════════════════════════════════════
     *      VANILLA HTML / JS
     *      ═══════════════════════════════════════════════════════════════════════════════ -->
     * <sg-button>Click me</sg-button>
     * <sg-button variant="primary">Primary</sg-button>
     * <sg-button variant="outline" size="lg">Large Outline</sg-button>
     * <sg-button variant="success" leading-icon="check">Save</sg-button>
     * <sg-button loading>Loading...</sg-button>
     * <sg-button disabled>Disabled</sg-button>
     * <sg-button shape="pill" variant="secondary">Pill Button</sg-button>
     * <script>
     *   document.querySelector('sg-button').addEventListener('sgClick', (e) => {
     *     console.log('Button clicked!', e.detail);
     *   });
     * </script>
     * <!-- ═══════════════════════════════════════════════════════════════════════════════
     *      ANGULAR (no wrapper needed, add CUSTOM_ELEMENTS_SCHEMA)
     *      ═══════════════════════════════════════════════════════════════════════════════ -->
     * <sg-button
     *   variant="primary"
     *   [attr.loading]="isLoading || null"
     *   [attr.disabled]="isDisabled || null"
     *   (sgClick)="handleClick($event)">
     *   Save Changes
     * </sg-button>
     * <!-- ═══════════════════════════════════════════════════════════════════════════════
     *      REACT (use kebab-case attributes)
     *      ═══════════════════════════════════════════════════════════════════════════════ -->
     * <sg-button
     *   variant="primary"
     *   leading-icon="save"
     *   loading={isLoading}
     *   onSgClick={(e) => handleClick(e.detail)}>
     *   Save Changes
     * </sg-button>
     * @fires sgClick - Emitted when button is clicked (not disabled/loading)
     * @cssprop --sg-btn-bg - Button background color
     * @cssprop --sg-btn-color - Button text color
     * @cssprop --sg-btn-border-color - Button border color
     * @cssprop --sg-btn-radius - Button border radius
     * @cssprop --sg-btn-shadow - Button box shadow
     */
    interface HTMLSgButtonElement extends Components.SgButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSgButtonElementEventMap>(type: K, listener: (this: HTMLSgButtonElement, ev: SgButtonCustomEvent<HTMLSgButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSgButtonElementEventMap>(type: K, listener: (this: HTMLSgButtonElement, ev: SgButtonCustomEvent<HTMLSgButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSgButtonElement: {
        prototype: HTMLSgButtonElement;
        new (): HTMLSgButtonElement;
    };
    interface HTMLSgDropdownElementEventMap {
        "sgOpen": void;
        "sgClose": void;
        "sgToggle": boolean;
    }
    /**
     * @example ### Angular
     * ```html
     * <sg-dropdown align="start" position="bottom">
     *   <button slot="trigger">Open Menu</button>
     *   <div slot="header">Settings</div>
     *   <button>Option 1</button>
     *   <button>Option 2</button>
     *   <div slot="footer">Logged in as Admin</div>
     * </sg-dropdown>
     * ```
     * ### React
     * ```jsx
     * <sg-dropdown align="start" closeOnSelect={false}>
     *   <button slot="trigger">Menu</button>
     *   <div>Content here</div>
     * </sg-dropdown>
     * ```
     * ### Vanilla JS
     * ```html
     * <sg-dropdown id="myDropdown" align="end" close-on-select="false">
     *   <button slot="trigger">Options</button>
     *   <ul>
     *     <li>Item 1</li>
     *     <li>Item 2</li>
     *   </ul>
     * </sg-dropdown>
     * <script>
     *   const dropdown = document.querySelector('#myDropdown');
     *   dropdown.addEventListener('sgOpen', (e) => console.log('Opened'));
     *   dropdown.addEventListener('sgClose', (e) => console.log('Closed'));
     * </script>
     * ```
     */
    interface HTMLSgDropdownElement extends Components.SgDropdown, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSgDropdownElementEventMap>(type: K, listener: (this: HTMLSgDropdownElement, ev: SgDropdownCustomEvent<HTMLSgDropdownElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSgDropdownElementEventMap>(type: K, listener: (this: HTMLSgDropdownElement, ev: SgDropdownCustomEvent<HTMLSgDropdownElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSgDropdownElement: {
        prototype: HTMLSgDropdownElement;
        new (): HTMLSgDropdownElement;
    };
    /**
     * @component sg-icon
     * @description SVG Icon component for SagedUI - A flexible, accessible icon system
     * @example <!-- Basic usage with built-in icons -->
     * <sg-icon name="home"></sg-icon>
     * <sg-icon name="icon-home"></sg-icon>
     * <!-- With custom size -->
     * <sg-icon name="settings" size="32"></sg-icon>
     * <!-- With custom color (fill is an alias for color) -->
     * <sg-icon name="heart" color="#ff0000"></sg-icon>
     * <sg-icon name="heart" fill="#ff0000"></sg-icon>
     * <!-- Custom icon via src (fetches SVG file) -->
     * <sg-icon src="/assets/custom-icon.svg"></sg-icon>
     */
    interface HTMLSgIconElement extends Components.SgIcon, HTMLStencilElement {
    }
    var HTMLSgIconElement: {
        prototype: HTMLSgIconElement;
        new (): HTMLSgIconElement;
    };
    /**
     * @component sg-skeleton
     * @description Skeleton loading placeholder component for SagedUI
     * @example <sg-skeleton variant="text" width="200px" height="1rem"></sg-skeleton>
     * <sg-skeleton variant="rect" width="100%" height="200px"></sg-skeleton>
     * <sg-skeleton variant="circle" width="48px" height="48px"></sg-skeleton>
     */
    interface HTMLSgSkeletonElement extends Components.SgSkeleton, HTMLStencilElement {
    }
    var HTMLSgSkeletonElement: {
        prototype: HTMLSgSkeletonElement;
        new (): HTMLSgSkeletonElement;
    };
    interface HTMLElementTagNameMap {
        "sg-article-editor": HTMLSgArticleEditorElement;
        "sg-badge": HTMLSgBadgeElement;
        "sg-button": HTMLSgButtonElement;
        "sg-dropdown": HTMLSgDropdownElement;
        "sg-icon": HTMLSgIconElement;
        "sg-skeleton": HTMLSgSkeletonElement;
    }
}
declare namespace LocalJSX {
    /**
     * SagedUI - Article Editor Component
     * A headless-ready article editor supporting HTML and Markdown modes
     * with live preview, formatting toolbar, and optional media library integration.
     * @example ```html
     * <sg-article-editor
     *   value="<p>Hello World</p>"
     *   mode="html"
     *   placeholder="Start writing..."
     * ></sg-article-editor>
     * ```
     */
    interface SgArticleEditor {
        /**
          * Available modes (comma-separated or array)
          * @default 'html,markdown,preview,split'
         */
        "availableModes"?: string;
        /**
          * Custom translations to override defaults
         */
        "customTranslations"?: Partial<EditorTranslations>;
        /**
          * Disabled state
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Custom accent color (buttons, links)
         */
        "editorAccent"?: string;
        /**
          * Custom background color for the editor
         */
        "editorBg"?: string;
        /**
          * Custom secondary background color
         */
        "editorBgSecondary"?: string;
        /**
          * Custom tertiary background color
         */
        "editorBgTertiary"?: string;
        /**
          * Custom border color
         */
        "editorBorder"?: string;
        /**
          * Custom border radius
         */
        "editorBorderRadius"?: string;
        /**
          * Custom font family for code
         */
        "editorFontMono"?: string;
        /**
          * Custom font family for text
         */
        "editorFontSans"?: string;
        /**
          * Custom font size
         */
        "editorFontSize"?: string;
        /**
          * Custom text color
         */
        "editorText"?: string;
        /**
          * Custom secondary text color
         */
        "editorTextSecondary"?: string;
        /**
          * Enable external preview window
          * @default true
         */
        "enableExternalPreview"?: boolean;
        /**
          * Locale for UI text (en, es, fr, de, pt, it, zh, ja, ko, ar)
          * @default 'en'
         */
        "locale"?: SupportedLocale;
        /**
          * Minimum height in pixels
          * @default 400
         */
        "minHeight"?: number;
        /**
          * Current editor mode
          * @default 'html'
         */
        "mode"?: EditorMode;
        /**
          * Emitted when the content changes
         */
        "onEditorChange"?: (event: SgArticleEditorCustomEvent<EditorChangeEvent>) => void;
        /**
          * Emitted when the mode changes
         */
        "onEditorModeChange"?: (event: SgArticleEditorCustomEvent<EditorModeChangeEvent>) => void;
        /**
          * Emitted when a media item should be inserted
         */
        "onMediaInsert"?: (event: SgArticleEditorCustomEvent<MediaItem>) => void;
        /**
          * Emitted when media library is requested
         */
        "onMediaLibraryOpen"?: (event: SgArticleEditorCustomEvent<void>) => void;
        /**
          * Placeholder text when editor is empty
          * @default 'Start writing...'
         */
        "placeholder"?: string;
        /**
          * Read-only state
          * @default false
         */
        "readonly"?: boolean;
        /**
          * Show word/character count
          * @default true
         */
        "showWordCount"?: boolean;
        /**
          * Enable spell checking
          * @default true
         */
        "spellcheck"?: boolean;
        /**
          * The content value of the editor
          * @default ''
         */
        "value"?: string;
    }
    /**
     * @example ### Angular
     * ```html
     * <sg-badge variant="success">Active</sg-badge>
     * <sg-badge variant="error" size="sm" dot>Offline</sg-badge>
     * <sg-badge variant="info" pill>New Feature</sg-badge>
     * <sg-badge variant="warning">
     *   <sg-icon slot="icon" name="alert-triangle" size="12"></sg-icon>
     *   Warning
     * </sg-badge>
     * ```
     * ### React
     * ```jsx
     * <sg-badge variant="primary" outlined>Beta</sg-badge>
     * <sg-badge variant="success" pulse>Live</sg-badge>
     * ```
     * ### Vanilla JS
     * ```html
     * <sg-badge variant="info" size="lg">Featured</sg-badge>
     * <sg-badge variant="neutral" removable id="tag1">Tag 1</sg-badge>
     * <script>
     *   document.querySelector('#tag1').addEventListener('sgRemove', (e) => {
     *     e.target.remove();
     *   });
     * </script>
     * ```
     */
    interface SgBadge {
        /**
          * Make the badge clickable/interactive
          * @default false
         */
        "clickable"?: boolean;
        /**
          * Show a status dot indicator
          * @default false
         */
        "dot"?: boolean;
        /**
          * Custom icon name (if using sg-icon internally)
         */
        "icon"?: string;
        /**
          * Display as outlined style (transparent background with border)
          * @default false
         */
        "outlined"?: boolean;
        /**
          * Display as pill shape (fully rounded)
          * @default false
         */
        "pill"?: boolean;
        /**
          * Apply pulse animation to the dot
          * @default false
         */
        "pulse"?: boolean;
        /**
          * Size of the badge
          * @default 'md'
         */
        "size"?: BadgeSize;
        /**
          * Size of the badge
         */
        "size"?: "xs" | "sm" | "md" | "lg";
        /**
          * Display as soft/subtle style (lighter background)
          * @default false
         */
        "soft"?: boolean;
        /**
          * Color variant of the badge
          * @default 'primary'
         */
        "variant"?: BadgeVariant;
        /**
          * Color variant
         */
        "variant"?: "primary" | "secondary" | "success" | "warning" | "error" | "info" | "neutral" | "purple" | "cyan";
    }
    /**
     * @component sg-button
     * @description A versatile button component with multiple variants, sizes, and states.
     * Framework-agnostic: works with Angular, React, Vue, and vanilla JS without wrappers.
     * @example <!-- ═══════════════════════════════════════════════════════════════════════════════
     *      VANILLA HTML / JS
     *      ═══════════════════════════════════════════════════════════════════════════════ -->
     * <sg-button>Click me</sg-button>
     * <sg-button variant="primary">Primary</sg-button>
     * <sg-button variant="outline" size="lg">Large Outline</sg-button>
     * <sg-button variant="success" leading-icon="check">Save</sg-button>
     * <sg-button loading>Loading...</sg-button>
     * <sg-button disabled>Disabled</sg-button>
     * <sg-button shape="pill" variant="secondary">Pill Button</sg-button>
     * <script>
     *   document.querySelector('sg-button').addEventListener('sgClick', (e) => {
     *     console.log('Button clicked!', e.detail);
     *   });
     * </script>
     * <!-- ═══════════════════════════════════════════════════════════════════════════════
     *      ANGULAR (no wrapper needed, add CUSTOM_ELEMENTS_SCHEMA)
     *      ═══════════════════════════════════════════════════════════════════════════════ -->
     * <sg-button
     *   variant="primary"
     *   [attr.loading]="isLoading || null"
     *   [attr.disabled]="isDisabled || null"
     *   (sgClick)="handleClick($event)">
     *   Save Changes
     * </sg-button>
     * <!-- ═══════════════════════════════════════════════════════════════════════════════
     *      REACT (use kebab-case attributes)
     *      ═══════════════════════════════════════════════════════════════════════════════ -->
     * <sg-button
     *   variant="primary"
     *   leading-icon="save"
     *   loading={isLoading}
     *   onSgClick={(e) => handleClick(e.detail)}>
     *   Save Changes
     * </sg-button>
     * @fires sgClick - Emitted when button is clicked (not disabled/loading)
     * @cssprop --sg-btn-bg - Button background color
     * @cssprop --sg-btn-color - Button text color
     * @cssprop --sg-btn-border-color - Button border color
     * @cssprop --sg-btn-radius - Button border radius
     * @cssprop --sg-btn-shadow - Button box shadow
     */
    interface SgButton {
        /**
          * Accessible label
          * @attr aria-label
         */
        "ariaLabel"?: string;
        /**
          * Disable the button
          * @attr disabled
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Leading icon name (from sg-icon)
          * @attr leading-icon
         */
        "leadingIcon"?: string;
        /**
          * Show loading spinner
          * @attr loading
          * @default false
         */
        "loading"?: boolean;
        /**
          * Loading text (replaces content while loading)
          * @attr loading-text
         */
        "loadingText"?: string;
        /**
          * Click event (emitted when not disabled/loading)
         */
        "onSgClick"?: (event: SgButtonCustomEvent<MouseEvent>) => void;
        /**
          * Button shape
          * @attr shape
          * @default 'default'
         */
        "shape"?: ButtonShape;
        /**
          * Button size
          * @attr size
          * @default 'md'
         */
        "size"?: ButtonSize;
        /**
          * Trailing icon name (from sg-icon)
          * @attr trailing-icon
         */
        "trailingIcon"?: string;
        /**
          * Button type attribute
          * @attr type
          * @default 'button'
         */
        "type"?: 'button' | 'submit' | 'reset';
        /**
          * Button color variant
          * @attr variant
          * @default 'primary'
         */
        "variant"?: ButtonVariant;
    }
    /**
     * @example ### Angular
     * ```html
     * <sg-dropdown align="start" position="bottom">
     *   <button slot="trigger">Open Menu</button>
     *   <div slot="header">Settings</div>
     *   <button>Option 1</button>
     *   <button>Option 2</button>
     *   <div slot="footer">Logged in as Admin</div>
     * </sg-dropdown>
     * ```
     * ### React
     * ```jsx
     * <sg-dropdown align="start" closeOnSelect={false}>
     *   <button slot="trigger">Menu</button>
     *   <div>Content here</div>
     * </sg-dropdown>
     * ```
     * ### Vanilla JS
     * ```html
     * <sg-dropdown id="myDropdown" align="end" close-on-select="false">
     *   <button slot="trigger">Options</button>
     *   <ul>
     *     <li>Item 1</li>
     *     <li>Item 2</li>
     *   </ul>
     * </sg-dropdown>
     * <script>
     *   const dropdown = document.querySelector('#myDropdown');
     *   dropdown.addEventListener('sgOpen', (e) => console.log('Opened'));
     *   dropdown.addEventListener('sgClose', (e) => console.log('Closed'));
     * </script>
     * ```
     */
    interface SgDropdown {
        /**
          * Horizontal alignment of the dropdown content relative to trigger
          * @default 'start'
         */
        "align"?: 'start' | 'end' | 'center';
        /**
          * Horizontal alignment of the dropdown
         */
        "align"?: "start" | "end" | "center";
        /**
          * Whether to close the dropdown when an item is selected/clicked
          * @default true
         */
        "closeOnSelect"?: boolean;
        /**
          * Whether the dropdown is disabled
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Maximum height of the dropdown content for scrolling
          * @default '320px'
         */
        "maxHeight"?: string;
        /**
          * Minimum width of the dropdown content (e.g., "200px", "12rem")
          * @default '200px'
         */
        "minWidth"?: string;
        /**
          * Emitted when the dropdown closes
         */
        "onSgClose"?: (event: SgDropdownCustomEvent<void>) => void;
        /**
          * Emitted when the dropdown opens
         */
        "onSgOpen"?: (event: SgDropdownCustomEvent<void>) => void;
        /**
          * Emitted when the open state changes
         */
        "onSgToggle"?: (event: SgDropdownCustomEvent<boolean>) => void;
        /**
          * Whether the dropdown is currently open
          * @default false
         */
        "open"?: boolean;
        /**
          * Vertical position of the dropdown content
          * @default 'bottom'
         */
        "position"?: 'bottom' | 'top';
        /**
          * Position of the dropdown relative to trigger
         */
        "position"?: "bottom" | "top";
        /**
          * Show a backdrop overlay (useful on mobile)
          * @default false
         */
        "showBackdrop"?: boolean;
        /**
          * Size variant
          * @default 'md'
         */
        "size"?: 'sm' | 'md' | 'lg';
    }
    /**
     * @component sg-icon
     * @description SVG Icon component for SagedUI - A flexible, accessible icon system
     * @example <!-- Basic usage with built-in icons -->
     * <sg-icon name="home"></sg-icon>
     * <sg-icon name="icon-home"></sg-icon>
     * <!-- With custom size -->
     * <sg-icon name="settings" size="32"></sg-icon>
     * <!-- With custom color (fill is an alias for color) -->
     * <sg-icon name="heart" color="#ff0000"></sg-icon>
     * <sg-icon name="heart" fill="#ff0000"></sg-icon>
     * <!-- Custom icon via src (fetches SVG file) -->
     * <sg-icon src="/assets/custom-icon.svg"></sg-icon>
     */
    interface SgIcon {
        /**
          * Accessible label for screen readers
         */
        "ariaLabel"?: string;
        /**
          * Color of the icon (CSS color value)
          * @default 'currentColor'
         */
        "color"?: string;
        /**
          * Whether the icon is decorative (hidden from screen readers)
          * @default false
         */
        "decorative"?: boolean;
        /**
          * Alias for color (for compatibility with legacy svg-icon components)
          * @default undefined
         */
        "fill"?: string;
        /**
          * Flip the icon horizontally
          * @default false
         */
        "flipH"?: boolean;
        /**
          * Flip the icon vertically
          * @default false
         */
        "flipV"?: boolean;
        /**
          * Height of the icon (overrides size)
         */
        "height"?: number | string;
        /**
          * The name of the icon from the built-in library. Supports both 'name' and 'icon-name' formats for compatibility.
         */
        "name"?: string;
        /**
          * Rotation angle in degrees
         */
        "rotate"?: number;
        /**
          * Size of the icon in pixels
          * @default 24
         */
        "size"?: number | string;
        /**
          * Whether the icon should spin (useful for loading icons)
          * @default false
         */
        "spin"?: boolean;
        /**
          * URL to a custom SVG icon (alternative to name)
         */
        "src"?: string;
        /**
          * Stroke width for outline icons
         */
        "strokeWidth"?: number;
        /**
          * Width of the icon (overrides size)
         */
        "width"?: number | string;
    }
    /**
     * @component sg-skeleton
     * @description Skeleton loading placeholder component for SagedUI
     * @example <sg-skeleton variant="text" width="200px" height="1rem"></sg-skeleton>
     * <sg-skeleton variant="rect" width="100%" height="200px"></sg-skeleton>
     * <sg-skeleton variant="circle" width="48px" height="48px"></sg-skeleton>
     */
    interface SgSkeleton {
        /**
          * Animation type - shimmer: Gradient animation (default) - pulse: Opacity pulse animation - none: No animation
          * @default 'shimmer'
         */
        "animation"?: 'shimmer' | 'pulse' | 'none';
        /**
          * The height of the skeleton
          * @default '1rem'
         */
        "height"?: string;
        /**
          * The shape variant of the skeleton - text: Slightly rounded, good for text placeholders - rect: More rounded, good for cards/images - circle: Fully rounded, good for avatars
          * @default 'text'
         */
        "variant"?: 'text' | 'rect' | 'circle';
        /**
          * The width of the skeleton
          * @default '100%'
         */
        "width"?: string;
    }
    interface IntrinsicElements {
        "sg-article-editor": SgArticleEditor;
        "sg-badge": SgBadge;
        "sg-button": SgButton;
        "sg-dropdown": SgDropdown;
        "sg-icon": SgIcon;
        "sg-skeleton": SgSkeleton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * SagedUI - Article Editor Component
             * A headless-ready article editor supporting HTML and Markdown modes
             * with live preview, formatting toolbar, and optional media library integration.
             * @example ```html
             * <sg-article-editor
             *   value="<p>Hello World</p>"
             *   mode="html"
             *   placeholder="Start writing..."
             * ></sg-article-editor>
             * ```
             */
            "sg-article-editor": LocalJSX.SgArticleEditor & JSXBase.HTMLAttributes<HTMLSgArticleEditorElement>;
            /**
             * @example ### Angular
             * ```html
             * <sg-badge variant="success">Active</sg-badge>
             * <sg-badge variant="error" size="sm" dot>Offline</sg-badge>
             * <sg-badge variant="info" pill>New Feature</sg-badge>
             * <sg-badge variant="warning">
             *   <sg-icon slot="icon" name="alert-triangle" size="12"></sg-icon>
             *   Warning
             * </sg-badge>
             * ```
             * ### React
             * ```jsx
             * <sg-badge variant="primary" outlined>Beta</sg-badge>
             * <sg-badge variant="success" pulse>Live</sg-badge>
             * ```
             * ### Vanilla JS
             * ```html
             * <sg-badge variant="info" size="lg">Featured</sg-badge>
             * <sg-badge variant="neutral" removable id="tag1">Tag 1</sg-badge>
             * <script>
             *   document.querySelector('#tag1').addEventListener('sgRemove', (e) => {
             *     e.target.remove();
             *   });
             * </script>
             * ```
             */
            "sg-badge": LocalJSX.SgBadge & JSXBase.HTMLAttributes<HTMLSgBadgeElement>;
            /**
             * @component sg-button
             * @description A versatile button component with multiple variants, sizes, and states.
             * Framework-agnostic: works with Angular, React, Vue, and vanilla JS without wrappers.
             * @example <!-- ═══════════════════════════════════════════════════════════════════════════════
             *      VANILLA HTML / JS
             *      ═══════════════════════════════════════════════════════════════════════════════ -->
             * <sg-button>Click me</sg-button>
             * <sg-button variant="primary">Primary</sg-button>
             * <sg-button variant="outline" size="lg">Large Outline</sg-button>
             * <sg-button variant="success" leading-icon="check">Save</sg-button>
             * <sg-button loading>Loading...</sg-button>
             * <sg-button disabled>Disabled</sg-button>
             * <sg-button shape="pill" variant="secondary">Pill Button</sg-button>
             * <script>
             *   document.querySelector('sg-button').addEventListener('sgClick', (e) => {
             *     console.log('Button clicked!', e.detail);
             *   });
             * </script>
             * <!-- ═══════════════════════════════════════════════════════════════════════════════
             *      ANGULAR (no wrapper needed, add CUSTOM_ELEMENTS_SCHEMA)
             *      ═══════════════════════════════════════════════════════════════════════════════ -->
             * <sg-button
             *   variant="primary"
             *   [attr.loading]="isLoading || null"
             *   [attr.disabled]="isDisabled || null"
             *   (sgClick)="handleClick($event)">
             *   Save Changes
             * </sg-button>
             * <!-- ═══════════════════════════════════════════════════════════════════════════════
             *      REACT (use kebab-case attributes)
             *      ═══════════════════════════════════════════════════════════════════════════════ -->
             * <sg-button
             *   variant="primary"
             *   leading-icon="save"
             *   loading={isLoading}
             *   onSgClick={(e) => handleClick(e.detail)}>
             *   Save Changes
             * </sg-button>
             * @fires sgClick - Emitted when button is clicked (not disabled/loading)
             * @cssprop --sg-btn-bg - Button background color
             * @cssprop --sg-btn-color - Button text color
             * @cssprop --sg-btn-border-color - Button border color
             * @cssprop --sg-btn-radius - Button border radius
             * @cssprop --sg-btn-shadow - Button box shadow
             */
            "sg-button": LocalJSX.SgButton & JSXBase.HTMLAttributes<HTMLSgButtonElement>;
            /**
             * @example ### Angular
             * ```html
             * <sg-dropdown align="start" position="bottom">
             *   <button slot="trigger">Open Menu</button>
             *   <div slot="header">Settings</div>
             *   <button>Option 1</button>
             *   <button>Option 2</button>
             *   <div slot="footer">Logged in as Admin</div>
             * </sg-dropdown>
             * ```
             * ### React
             * ```jsx
             * <sg-dropdown align="start" closeOnSelect={false}>
             *   <button slot="trigger">Menu</button>
             *   <div>Content here</div>
             * </sg-dropdown>
             * ```
             * ### Vanilla JS
             * ```html
             * <sg-dropdown id="myDropdown" align="end" close-on-select="false">
             *   <button slot="trigger">Options</button>
             *   <ul>
             *     <li>Item 1</li>
             *     <li>Item 2</li>
             *   </ul>
             * </sg-dropdown>
             * <script>
             *   const dropdown = document.querySelector('#myDropdown');
             *   dropdown.addEventListener('sgOpen', (e) => console.log('Opened'));
             *   dropdown.addEventListener('sgClose', (e) => console.log('Closed'));
             * </script>
             * ```
             */
            "sg-dropdown": LocalJSX.SgDropdown & JSXBase.HTMLAttributes<HTMLSgDropdownElement>;
            /**
             * @component sg-icon
             * @description SVG Icon component for SagedUI - A flexible, accessible icon system
             * @example <!-- Basic usage with built-in icons -->
             * <sg-icon name="home"></sg-icon>
             * <sg-icon name="icon-home"></sg-icon>
             * <!-- With custom size -->
             * <sg-icon name="settings" size="32"></sg-icon>
             * <!-- With custom color (fill is an alias for color) -->
             * <sg-icon name="heart" color="#ff0000"></sg-icon>
             * <sg-icon name="heart" fill="#ff0000"></sg-icon>
             * <!-- Custom icon via src (fetches SVG file) -->
             * <sg-icon src="/assets/custom-icon.svg"></sg-icon>
             */
            "sg-icon": LocalJSX.SgIcon & JSXBase.HTMLAttributes<HTMLSgIconElement>;
            /**
             * @component sg-skeleton
             * @description Skeleton loading placeholder component for SagedUI
             * @example <sg-skeleton variant="text" width="200px" height="1rem"></sg-skeleton>
             * <sg-skeleton variant="rect" width="100%" height="200px"></sg-skeleton>
             * <sg-skeleton variant="circle" width="48px" height="48px"></sg-skeleton>
             */
            "sg-skeleton": LocalJSX.SgSkeleton & JSXBase.HTMLAttributes<HTMLSgSkeletonElement>;
        }
    }
}
