/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    /**
     * @component sg-date-picker
     * @description Calendar date picker with full i18n support.
     * Works as a standalone component or can integrate with form systems.
     * @example <sg-date-picker 
     *   value="2024-01-15" 
     *   placeholder="Select date..."
     *   locale="es"
     * ></sg-date-picker>
     */
    interface SgDatePicker {
        /**
          * Align dropdown to right
          * @default false
         */
        "alignRight": boolean;
        /**
          * Allow clearing the date
          * @default true
         */
        "clearable": boolean;
        /**
          * Close the date picker
         */
        "close": () => Promise<void>;
        /**
          * Disable the date picker
          * @default false
         */
        "disabled": boolean;
        /**
          * Show error state
          * @default false
         */
        "hasError": boolean;
        /**
          * Locale for date formatting ('es' | 'en')
          * @default 'es'
         */
        "locale": 'es' | 'en';
        /**
          * Maximum selectable date (ISO format)
         */
        "maxDate"?: string;
        /**
          * Minimum selectable date (ISO format)
         */
        "minDate"?: string;
        /**
          * Open the date picker
         */
        "open": () => Promise<void>;
        /**
          * Placeholder text for input
          * @default 'Seleccionar fecha...'
         */
        "placeholder": string;
        /**
          * Current date value in ISO format (YYYY-MM-DD)
          * @default null
         */
        "value": string | null;
    }
}
export interface SgDatePickerCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSgDatePickerElement;
}
declare global {
    interface HTMLSgDatePickerElementEventMap {
        "sgChange": string | null;
    }
    /**
     * @component sg-date-picker
     * @description Calendar date picker with full i18n support.
     * Works as a standalone component or can integrate with form systems.
     * @example <sg-date-picker 
     *   value="2024-01-15" 
     *   placeholder="Select date..."
     *   locale="es"
     * ></sg-date-picker>
     */
    interface HTMLSgDatePickerElement extends Components.SgDatePicker, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSgDatePickerElementEventMap>(type: K, listener: (this: HTMLSgDatePickerElement, ev: SgDatePickerCustomEvent<HTMLSgDatePickerElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSgDatePickerElementEventMap>(type: K, listener: (this: HTMLSgDatePickerElement, ev: SgDatePickerCustomEvent<HTMLSgDatePickerElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSgDatePickerElement: {
        prototype: HTMLSgDatePickerElement;
        new (): HTMLSgDatePickerElement;
    };
    interface HTMLElementTagNameMap {
        "sg-date-picker": HTMLSgDatePickerElement;
    }
}
declare namespace LocalJSX {
    /**
     * @component sg-date-picker
     * @description Calendar date picker with full i18n support.
     * Works as a standalone component or can integrate with form systems.
     * @example <sg-date-picker 
     *   value="2024-01-15" 
     *   placeholder="Select date..."
     *   locale="es"
     * ></sg-date-picker>
     */
    interface SgDatePicker {
        /**
          * Align dropdown to right
          * @default false
         */
        "alignRight"?: boolean;
        /**
          * Allow clearing the date
          * @default true
         */
        "clearable"?: boolean;
        /**
          * Disable the date picker
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Show error state
          * @default false
         */
        "hasError"?: boolean;
        /**
          * Locale for date formatting ('es' | 'en')
          * @default 'es'
         */
        "locale"?: 'es' | 'en';
        /**
          * Maximum selectable date (ISO format)
         */
        "maxDate"?: string;
        /**
          * Minimum selectable date (ISO format)
         */
        "minDate"?: string;
        /**
          * Emitted when date changes
         */
        "onSgChange"?: (event: SgDatePickerCustomEvent<string | null>) => void;
        /**
          * Placeholder text for input
          * @default 'Seleccionar fecha...'
         */
        "placeholder"?: string;
        /**
          * Current date value in ISO format (YYYY-MM-DD)
          * @default null
         */
        "value"?: string | null;
    }
    interface IntrinsicElements {
        "sg-date-picker": SgDatePicker;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * @component sg-date-picker
             * @description Calendar date picker with full i18n support.
             * Works as a standalone component or can integrate with form systems.
             * @example <sg-date-picker 
             *   value="2024-01-15" 
             *   placeholder="Select date..."
             *   locale="es"
             * ></sg-date-picker>
             */
            "sg-date-picker": LocalJSX.SgDatePicker & JSXBase.HTMLAttributes<HTMLSgDatePickerElement>;
        }
    }
}
